### ISSUE TITLE
Mirror pages across collectives

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/collectives#1006]
Hi,
is there anyone else who sees relevant use cases for mirroring pages across collectives?

I'm building up a couple of collectives that actually share same documentation, so an option to mirror pages would be really useful.

**Comment by mejo-** [comment]
Dear @hansimausisteffiwurstbrot, do you mean the ability to copy pages across collectives? This has just been added with the latest 2.9.0 release of Collectives. You can copy/move pages inside and between collectives now with the 'Move or copy' page action.

**Comment by mejo-** [comment]
Let's close this due to missing further information.

**Comment by hansimausisteffiwurstbrot** [comment]
Hey, sorry for not having answere until now.

No, I don't mean to topy sites, but rather link/mirror a page of collective A in collective B.
So when someone changes the site in collective A, the changes are automatically shown in the site collective B.

Might be a bis of a niche use case, but I'd find it useful for some collectives I'm active in.

**Comment by joeschi** [comment]
Hey @mejo- , I have the same issue. It might be useful share collective-pages between collectives.
We have collectives for different usergroups. Some audiences have overlapping contents. So the posiility to share certain pages would be nice. Copying is not effective because I would then have to maintain two different files.

**Comment by mejo-** [comment]
https://github.com/nextcloud/collectives/issues/2087 tracks the same feature request. Do you agree @hansimausisteffiwurstbrot @joeschi?

**Comment by mejo-** [comment]
We just had a discussion about the question on how to share parts of a collective with another collective, see https://github.com/nextcloud/collectives/issues/2595#issuecomment-4852368099.

I'd be curious what you think about it.

**Comment by joeschi** [comment]
> [#2087](https://github.com/nextcloud/collectives/issues/2087) tracks the same feature request. Do you agree [@hansimausisteffiwurstbrot](https://github.com/hansimausisteffiwurstbrot) [@joeschi](https://github.com/joeschi)?

Yes, agreed.
