### ISSUE TITLE
Issue with sharing collectives to groups

### ISSUE THREAD

**Issue by JonasH1989** [nextcloud/collectives#1021]
**Describe the bug**
When sharing a collective to the group "members", the collective is not visible for any user. Older collectives, that have been shared in earlier versions are visible. When sharing directly to a user, the collective appears immediatly.

**To Reproduce**
Open a collective an share it to any group. Noone in the group will see the collective.

**Expected behavior**
Would be great if groups could see the collective

**Screenshots**
![image](https://github.com/nextcloud/collectives/assets/104369032/cfab2150-0989-4154-86d2-0d8842ae2663)
![image](https://github.com/nextcloud/collectives/assets/104369032/9dc46e55-d583-41fb-84c6-0492b0b3d7a8)

**Server details:**
- Collectives app version:v 2.9.1
- Nextcloud version: 27.1.3
- PHP Version: 8.1 auf cloudpanel v2.3.2
- Database: MariaDB 10.6 auf cloudpanel v2.3.2

**Client details:**
 - OS: Windows/Android/iOS/any
 - Browser: Brave/Chromium/Firefox/any
 - Device: Desktop/Tablet/Smartphone/any

**Comment by NoobyNiceDev** [comment]
I don't know why, but this has to do that a group isn't a circle. occ circles:sync will be your goto workaround after adding (and maybe removing) groups from/to circles or collectives.

**Comment by soerpoers** [comment]
how to workaround on a shared host where the app WebOCC doesn't work?

**Comment by NoobyNiceDev** [comment]
I don't know.
Maybe ask the hoster to execute that task or move to another hoster. For example a hoster with ssh access (only as the webserver user). There are webhosters out there, which allows that. Maybe you are allowed to run cron tasks. Or you upload a PHP which executes occ.php. 

In the end, this should be part of cron.php.

**Comment by mejo-** [comment]
@ArtificialOwl are you aware of any recent issues in Circles that could be the reason here?

**Comment by mejo-** [comment]
Are people still experiencing this issue? If so, could you share the Nextcloud server version you're running?

**Comment by VETspert** [comment]
Why isn't this bug fixed? This is one of the basic functions for collaboration! And now we don't even know if it's circle/teams problem or this collective plugin. 

Version: Nextcloud Hub 8 (29.0.4)
<details><summary>App List</summary>
<p>

Name	Version
Activities for shared file downloads	1.17.0
Activity	2.21.1
Announcement center	6.8.1
Antivirus for files	5.5.7
Approval	1.3.0
Auditing / Logging	1.19.0
Auto Groups	1.5.3
Automated kitinerary parsing	1.5.0
Automated PDF conversion	1.14.0
Brute-force settings	2.9.0
Calendar	4.7.15
Call summary bot	1.2.0
Collabora Online - Built-in CODE Server	24.4.502
Collaborative tags	1.19.0
Collectives	2.14.0
Comments	1.19.0
Contacts	6.0.0
Contacts Interaction	1.10.0
Dashboard	7.9.0
Deleted files	1.19.0
Federation	1.19.0
File access control	1.19.1
File actions	4.1.0
File reminders	1.2.0
File sharing	1.21.0
Files automated tagging	1.19.0
Files download limit	2.0.0
Forms	4.2.4
Full text search - Elasticsearch Platform	29.0.1
Group folders	17.0.2
Local Image Generation with Stable Diffusion	1.1.0
Mail Notifier	0.0.3
Monitoring	1.19.0
Nextcloud Assistant	1.1.0
Nextcloud Office	8.4.4
Notifications	2.17.0
OCC Web	0.2.0
OpenAI and LocalAI integration	2.0.3
Password policy	1.19.0
PDF viewer	2.10.0
Privacy	1.13.0
Recommendations	2.1.0
Related Resources	1.4.0
Share by mail	1.19.0
Suspicious Login	7.0.0
Tables	0.7.5
Talk	19.0.7
Tasks	0.16.1
Teams	29.0.0-dev
Terms of service	2.5.0
Text	3.10.1
TimeManager	0.3.15
Two-Factor TOTP Provider	11.0.0-dev
Unrounded Corners	1.1.3
Versions	1.22.0
Workflow external scripts	1.14.1
Workflow OCR	1.29.0
</p>
</details>

**Comment by mejo-** [comment]
To those who still experience this bug, could you please do the following:

```
$ occ circles:manage:list | grep "<collective-name>"
```

This should list the circle/team for the collective in question. Use the Circle Single Id for the following command:

```
$ occ circles:members:list --inherited <circle-single-id>
```

Does it list the group (source "Nextcloud Group") as a member? Does it list the user members of the problematic group?

**Comment by u2h5** [comment]
It lists the Group as a member, but only the users since the last `occ circles:sync`. New users who are Members of the group are not listed :/

**Comment by mejo-** [comment]
@u2h5 thanks for the additional info. Could you try to run `occ circles:memberships --all` and see whether this changes the situation?

**Comment by MoonBite666** [comment]
> @u2h5 thanks for the additional info. Could you try to run `occ circles:memberships --all` and see whether this changes the situation?

Everything gets OK on my env ( Docker Nextcloud 28 )

**Comment by mejo-** [comment]
Glad to hear that we found a solution to this problem. Let's close it for now. Please don't hesitate to comment if you still experience this issue.
