### ISSUE TITLE
UI: make header (sections) collapsible

### ISSUE THREAD

**Issue by kizm0** [nextcloud/collectives#1030]
**Is your feature request related to a problem? Please describe.**
i do have page with structured headers and in each header the text/section is quite long, it would be helpful to hide some sections which are not interesting 

**Describe the solution you'd like**
click on the header and all items underneath (section) are getting collapsed / not displayed

**Describe alternatives you've considered**

**Additional context**

**Comment by mejo-** [comment]
Dear @kizm0, thanks for your feedback. This feature request is already tracked in the Nextcloud Text app where this change would need to happen: https://github.com/nextcloud/text/issues/1841
