### ISSUE TITLE
Option to delete attachments without going into Files app

### ISSUE THREAD

**Issue by Jeefongithub** [nextcloud/collectives#1034]
**Is your feature request related to a problem? Please describe.**

When trying to delete an attachment from a page I need to go into the files app to delete the item

**Describe the solution you'd like**

In the menu option for attachment having an option to delete file with a confirmation to avoid accidental clicks would be perfect

**Describe alternatives you've considered**

Going into files and deleting attachment

**Additional context**

Menu referenced in above answer

![image](https://github.com/nextcloud/collectives/assets/53583661/93023106-743f-43c2-ac59-5cdaab21e441)

**Comment by mejo-** [comment]
Dear @Jeefongithub, thanks for your feedback.

The list of attachments in the page sidebar lists all attachments for the displayed text document. If you remove an attachment from the document, it should get listed under "Recently deleted" with an option to restore the attachment. Once the document session got closed once, all attachments that are no longer referenced in the document will get removed. So they should vanish from the list of attachments as well.

If I understand your request correctly, you're confused about the situation of opening a document and seeing an attachment listed that no longer exists in the text document, right?

**Comment by mejo-** [comment]
@Jeefongithub as written above, this is kind of expected. The cleanup job will take care of deleting unused attachments later on. But we cannot do this straight away as this would mean restoring the attachment would be impossible.
