### ISSUE TITLE
when sorting by title pages are unable to be dragged under other pages

### ISSUE THREAD

**Issue by Jeefongithub** [nextcloud/collectives#1049]
**Describe the bug**

When not using the default sorting option, sort by custom order, the pages are unable to be dragged under additional pages

**To Reproduce**

1. go to collection
2. set sorting to title
3. drag page under a different page

**Expected behavior**

When dragging the expected result is the parent page the new page is attempted to be dragged under would be highlighted showing the dragged page will be placed underneath 

**Screenshots**

**Server details:**
- Collectives app version: 2.9.2
- Nextcloud version: 27.1.5 RC1
- PHP Version: 8.2.13
- Database: MariaDB 10.5.21

**Client details:**
 - OS: Debian 12
 - Browser: Floorp (firefox fork)
 - Browser version: 11.6.1
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment]
Dear @Jeefongithub. This is intended behaviour. We intentionally disable drag+drop when sorting pages alphabetically or chronologically because the custom order is not in place then. So we don't know how to actually order pages in these cases when people would move them around.

**Comment by Jeefongithub** [comment]
gotcha. I might be using the wrong term instead of under other pages I guess it would be dragging a page to become a subpage. Is that also intended behavior since it would be changing the order of the subpages? I'm just trying to figure out what workflow I'll need to use since I mostly work in sort by title

**Comment by mejo-** [comment]
If we allowed moving pages while displaying search order by title/time, we wouldn't know where in the page order to place a subpage after moving it to a new parent. That's why moving by drag & drop is only allowed in custom search order view for now.

**Comment by Jeefongithub** [comment]
ok. if thats the intended behavior I'll close this and just adjust how I'm working
