### ISSUE TITLE
Different group name if searching or viewing members

### ISSUE THREAD

**Issue by robake1** [nextcloud/collectives#1070]
**Describe the bug**
Groupname shown when searching for new members should be the same as the list of members, this happens on groups in Nextcloud that has different GroupID and DisplayName for example when the group is created by the Workspace app.

**To Reproduce**
Steps to reproduce the behavior (when having a group with different GroupID and DisplayName as shown in OCC command under screenshots) :
1. Add member to a collective
2. Search for a group , note the name shown (DisplayName attribute in Nextcloud)
3. Add group from above
4. See the members in the collective and note that the name of the added group is not correct (it shows groupID attribute from Nextcloud)

**Expected behavior**
To see the same attribute (Displayname) of the group in both the search field and the members field of the collective.

**Screenshots**
Screenshot when searching group "U-Test Editors" :
![Search-group](https://github.com/nextcloud/collectives/assets/120456693/d122ae15-9f17-4675-9a89-f718133f5c09)
Screenshot when viewing members it show "SPACE-U-3" (GroupID) :
![Members](https://github.com/nextcloud/collectives/assets/120456693/daf9c3f3-6590-40ef-a0fc-ecf4c3d1aaf7)

OCC command group:info showing difference on GroupID and DisplayName : 

sudo -u wwwrun php occ group:info SPACE-U-3
  - groupID: SPACE-U-3
  - displayName: U-Test Edtitors
  - backends:
    - Database

**Server details:**
- Collectives app version: 2.9.2
- Nextcloud version: 27.1.4
- PHP Version: 8.0.28
- Database: MariaDB

**Client details:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Browser version: 120.0.2210.121 
 - Device: Desktop

**Comment by mejo-** [comment]
This should be finally fixed by https://github.com/nextcloud/circles/pull/1682.

You'll have to run `occ circles:maintenance --level=5 --force-refresh` in order to update the displayname of existing users/gorups.

**Comment by mejo-** [comment]
> Update after trying Nextcloud 29.0.8 and the newest Circles app , and the newest version of Workspace 2.14.4 (also downgraded to 2.14.3 for test) to date .

Unfortunately the patch didn't make it into Nextcloud 29.0.8 either, but it is merged now and will be shipped along with Nextcloud 29.0.9. Could you please upgrade once this got released, run the `occ` command from above afterwards and report if you still run into the same problem afterwards?
