### ISSUE TITLE
PHP Error - Trying to access array offset on value of type null at /var/www/nextcloud/apps/collectives/vendor/teamtnt/tntsearch/src/Support/Highlighter.php#

### ISSUE THREAD

**Issue by kevinkuan1969** [nextcloud/collectives#1081]
**Describe the bug**
The error message has been appeared on and off in log reader.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server details:**
- Collectives app version:  2.9.2
- Nextcloud version: 28.0.1
- PHP Version: 8.2
- Database:  MariaDB 10.11.4

**Client details:**
 - OS: [Windows  11
 - Browser: Edge
 - Browser version: 
 -
<details>
<summary>Logs</summary>

![image](https://github.com/nextcloud/collectives/assets/80019930/fdb2121c-b971-4eb0-a616-4d030c2b8414)

**Comment by mejo-** [comment]
Dear @kevinkuan1969, do you still encounter this problem with latest Collectives? Given that we migrated to a new major version of TNTSearch in the meantime and I never saw this error message myself, I wonder whether it still happens? :thinking:

**Comment by mejo-** [comment]
Will close this due to lack of information.
