### ISSUE TITLE
Search page content when using the page filter in the left navigation

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/collectives#1094]
**Is your feature request related to a problem? Please describe.**
This came up in design discussions with @marcoambrosini 

We should think about providing page content search results when filtering in the page list of the left navigation.

**Describe the solution you'd like**
My initial suggestion would be to still list page title matches first by filtering the page list (as it currently works) but provide content matches in a second list below.

**Describe alternatives you've considered**
None so far

**Additional context**
This is also how the search in the Talk mobile app works for example, though I don't think we have a similar pattern yet on the web anywhere.

**Comment by alexanderdd** [comment]
Also it would be great to then highlight the search term when you go to the page, as it is done in https://docs.nextcloud.com/server/latest/user_manual/en/ (which runs read the docs?)

But I think this also needs a higher-level discussion: There is the unified search in the top right, which is supposed to be THE way to find anything (right?). Afaik it already searches in collectives page contents. Then we don't need the same functionality in two places, right? But then how can users easily discover that the left search bar is just a page title filter, and the real search in in the top right?
Don't want to hijack this thread. If this discussion is already ongoing somewhere, please post a link.

**Comment by juliushaertl** [comment]
Thanks for your feedback @alexanderdd 

> Also it would be great to then highlight the search term when you go to the page, as it is done in [docs.nextcloud.com/server/latest/user_manual/en](https://docs.nextcloud.com/server/latest/user_manual/en/) (which runs read the docs?)

Yes, though this is a separate issue. We are looking into providing search/highlight functionality in the text app which we first need to be able to use this to highlight results within Collectives then. https://github.com/nextcloud/collectives/issues/648

> But I think this also needs a higher-level discussion: There is the unified search in the top right, which is supposed to be THE way to find anything (right?). Afaik it already searches in collectives page contents. Then we don't need the same functionality in two places, right? But then how can users easily discover that the left search bar is just a page title filter, and the real search in in the top right?

While we already have the unified search it has quite a few design issues https://github.com/nextcloud/server/issues/24056 especially when it comes to providing quick access within the current visible app context. When discussing this in the past with the design team we came to the conclusion that local filtering also makes sense separately. I don't see why having the unified search would contradict with showing useful results also when performing local filtering in the current collective.
