### ISSUE TITLE
[printing] Collective title on blank first page (Firefox only?)

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/collectives#1110]
This is the same issue as https://github.com/nextcloud/collectives/issues/543 that might have been solved, but which is still occurring on our side.

**Describe the bug**
**On Firefox**, when printing a collective the title is always printed as the only element on the first page, and the main collective content is printed starting from page 2. This is not the case on Chromium

**To Reproduce**
1. Go to collective
2. Press `ctrl` + `p`
3. See first page only contains the title

**Expected behavior**
 Title and collective are on the same page / first page not wasted.

**Screenshots**
![2024-02-10-123350_893x646_scrot](https://github.com/nextcloud/collectives/assets/34077099/4ac5ada4-36ae-45e6-9782-6dfdc48d12d9)

**Server details:**
- Collectives app version: 2.9.2
- Nextcloud version: 27.1.6

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox
 - Browser version: 122
 - Device: desktop

**Comment by NL-CCMLM** [comment]
The same with 

    Collectives app version: 2.9.2
    Nextcloud version: 28.0.2

Client details:

    OS:  Linux Mint
    Browser: Firefox
    Browser version: 122.0.1
    Device: desktop

Working with all the others browsers....

**Comment by mejo-** [comment]
Fixed by #1561
