### ISSUE TITLE
pasting inline pictures from clipboard - collective show random pictures from other articles

### ISSUE THREAD

**Issue by Ancii200** [nextcloud/collectives#1112]
**Describe the bug**
It's about displaying newly created images saved in the clipboard and pasted into a page in the collective

**To Reproduce**
1. Go to Collectives
2. Create two new pages (page1 and page2) in collective
3. take a screenshot and save it in the clipboard
4. paste the first picture in page1 
5. do the same for the second page (take a new screenshot save it in the clipboard and paste it in page2)

**Expected behavior**
The images should be saved correctly and displayed accordingly

**Actual behavior**
Due to the same distribution of names, the images are not displayed correctly. 
When editing it will still display normally, but from the moment you save it, it will show the other image at page 1. 

**Server details:**
- Collectives app version: 2.9.2
- Nextcloud version: 27.1.5
- PHP Version: 8.1
- Database: MySql

**Client details:**
 - OS:  Windows
 - Browser: Firefox, Chrome
 - Device: Desktop

**Comment by Githopp192** [comment]
Same to me .. 

- NC 27.1.7 
- app version: 2.9.2
- PHP Version:8.2
- Database: MariaDB

Client details:

OS: Windows Pro 11
Browser: MS Edge / newest version
Device: Desktop

I had created a lot of articlles - unfortunately i noticed too late, that a lot of images (which were important Knowledge articles) now are lost.

Thinking to switch the whole content to JOPLIN.

**Comment by Aveyron-RetD** [comment]
You should put it in edit mode it is the only workaround i found

**Comment by mejo-** [comment]
Dear all, thanks for the report. So far I failed to reproduce the issue. A clear and reliable reproducer would be helpful.

Some background information: when uploading an image or attachment to a collectives page, the file gets stored in a dedicated attachments folder. I don't see how images/attachments from different pages could get mixed here.

If you still have a page with the described problem, could you please check whether the correct images are in the attachments directory of the page? You can do this by following these steps:

1. Find out the fileId of the page in question. You can find it in the URL of the page (the `fileId=<id>` query string parameter).
2. Select 'Open in files' in the three-dot menu of the respective page (three-dot menu can be found in the top right corner)
3. In the Files app, select 'Show hidden files' in the settings (settings can be found in the bottom left corner)
4. Open the directory `.attachments.<fileId>` - which is the attachments directory for the page in question.
5. See whether the expected images/attachments are in this directory, or whether the erroneously displayed ones are there.

**Comment by mejo-** [comment]
> => In view mode => random => looks like they from another assets from fileID=8470

Thanks a lot @Aveyron-RetD! Could you open the network tab in the developer tools of your browser, clear it and then reload the page (in view mode) and see whether there's requests to any other attachments folders than `.attachments.8470`?

**Comment by Aveyron-RetD** [comment]
Wonder if it's linked as well to comments section, https://github.com/nextcloud/server/issues/43239. Looks like they are linked to the wrong file.

**Comment by Aveyron-RetD** [comment]
Ok i manage to reproduce.

Maybe people could confirm i am on 28.0.3
collectives on 2.10.0

Create a test collectives named Nouveau collectif
create two subpages :
Janvier 2024
février 2024

Paste a screenshot of something  in Janvier 2024
Paste a screenshot of something  else in février 2024.

Click on View mode in janvier 2024 . its the wrong screenshot.

**Comment by mejo-** [comment]
Thanks, I'm able to reproduce the issue now. If you change from one page to another and both include images with the same filename, then in view mode the image from former page is displayed. Clicking on the image or changing to edit mode displays the correct image.

**Comment by mejo-** [comment]
This is a bug in Nextcloud Text. nextcloud/text#5484 fixes it. We'll take care that this lands in the upcoming Nextcloud 27 and 28 bugfix releases.
