### ISSUE TITLE
Heading anchors point to `#undefined` in view mode

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#1114]
**Describe the bug**
Heading anchors point to `#undefined` in view mode.

**To Reproduce**
1. Create a document with headings
2. Switch to view mode
3. Hover over the `#` symbol left to a heading and see the URL.

**Server details:**
- Collectives app version: latest
- Nextcloud version: 27.1.5

**Comment by Koc** [comment]
not reproducible for me in current main branch after running `npm ci && npm run watch`

**Comment by AngryNui** [comment]
I have the same problem. Only in view mode anchor points to #undefined. In edit mode the anchor points to the correct position. 
When view-mode is set as default and you open a link with the correct anchor it wont show the correct position. 

Collectives app version: 2.10.0
Nextcloud: 28.0.3

**Comment by grnd-alt** [comment]
#### Findings
I looked into this issue, couldn't quite figure it out but still possibly made some findings.
The Links for headings are created in extractor.js
and called by either onUpdate or onCreate in nodes/Heading/index.js

the links rendering as undefined most likely has something to do with the lifecycle hooks not beeing called in the way they are ment to be. Somehow the setupReader and setupEditor functions in collectives that start those editors make it so the reader and editor influence one another.

Inspecting the stack trace with breakpoints it was visible that addNode in nodes/Heading/index.js was called before the onCreated Hook which could possibly cause issues. Another possibility would be that the influence of different orders of setContent-calls in collectives affects the link-values, which would bring up the question why setContent calls don't all trigger the same update cycle.

I don't know if any of that will be helpful but I did my best.

**Comment by mejo-** [comment]
This finally got fixed in Text with nextcloud/text#5893.
