### ISSUE TITLE
Is there any plan to implement Notion-like database?

### ISSUE THREAD

**Issue by NikoKS** [nextcloud/collectives#1125]
Or is there any Nextcloud modules similar to it?

**Comment by NikoKS** [comment]
hello @mejo- , so in Notion, you could create a Table like this which are called databases
<img width="842" alt="Screenshot 2024-02-23 at 10 34 55" src="https://github.com/nextcloud/collectives/assets/24285511/9b61aaab-14f1-4528-8582-a748a117cb69">

The table has the ability to be filtered, and has different views. It is somewhat similar to Nextcloud Deck, but it seems that nextcloud deck is only viewable as a card deck.

**Comment by mejo-** [comment]
Thanks @NikoKS. I have good news: [Nextcloud Tables](https://github.com/nextcloud/tables) should be exactly what you're looking for :blush: 

Closing this as out of scope for the Collectives app.

**Comment by NikoKS** [comment]
@mejo- , Very Nice! Exactly what's needed. Just a quick question. Is this table embed-able into a collective page?

**Comment by mejo-** [comment]
You can reference a table inside a Collectives page by using the smart picker (type `/` at the beginning of a new line in the document). This doesn't list the full table though.

We're currently working on more advanced possibilities to embed interactive objects.
