### ISSUE TITLE
Link to website in mermaid node is not working properly

### ISSUE THREAD

**Issue by AngryNui** [nextcloud/collectives#1135]
**Describe the bug**
Links in mermaid to external websites won't open when opening .md in collectives.
Links in mermaid fail to open new tab when using `_blank` (also in markdown editor not only in collective). 

**To Reproduce**
1. Create collective/.md with a mermaid-codeblock and add
```
%%{init: {'securityLevel':'loose'}}%%
flowchart
	Nextcloud --> 2 --> 3 ---> Nextcloud

click Nextcloud href "https://nextcloud.com/" _blank 
```
3. Click on the nextcloud-node in mermaid diagram
4. See no external website will open nor a new tab 
5. Go to filebrowser open .md and click on the nextcloud-node in mermaid diagram
6. See external website will load but won't open in a new tab

**Expected behavior**
open new tab with external website when using `_blank` like described in
[Mermaid Docs](https://mermaid.js.org/syntax/flowchart.html#interaction)

**Server details:**
- Collectives app version: [2.9.2]
- Nextcloud version: [28.0.3]

**Client details:**
 - OS: [Windows]
 - Browser: [Firefox]
 - Browser version: [123.0.1]
 - Device: [desktop]

**Comment by AngryNui** [comment]
same behavior after update
- Collectives app version: [2.10.0]

**Comment by AngryNui** [comment]
same behavior after update

- Collectives app version: [2.10.1]
- Nextcloud version: [28.0.4]

**Comment by AngryNui** [comment]
same behavior after update

    Collectives app version: [2.12.0]
    Nextcloud version: [29.0.3]

**Comment by mejo-** [comment]
Thanks for your report. I was able to reproduce. A fix for broken link handling is incoming in https://github.com/nextcloud/text/pull/6575, it will have to get backported to the Nextcloud Text stable branches and will be shipped with the Nextcloud server releases afterwards.

Link targets are another story. To support them, we'd have to initialize mermaid.js with `securityLevel: 'loose'` which is not planned currently for security reasons. So unfortunately out of scope for now to make this working.
