### ISSUE TITLE
clicking on some of the sub-pages ends-up with showing an empty page (shortly popp-up for 1 second)

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/collectives#1144]
Describe the bug

clicking on some of the sub-pages ends-up with showing an empty page.

To Reproduce

* Go to Collective
* choose a sub-page from a page
* after clicking on that, the already entered text will shortly popp-up (for 1 second), but then dissappears.
* empty page shown - also edit mode does not change the context (no text anymore)

It seem, that this text cannot be recovered in any way, which could be a DATA LOSS situation for users !

Server details:

Collectives app version: 2.9.2
Nextcloud version: 27.1.7
PHP Version: 8.2
Database: MariaDB 
Client details:

OS: RHEL 8.9
Browser: MS Edge 
Browser version: Version 122.0.2365.66 (Offizielles Build) (64-Bit)
Device: desktop

**Comment by mejo-** [comment]
Dear @Githopp192,

in the three-dots menu on the top right there's an option "Open in Files". If you go there and download the markdown file, does it contain the expected content?

It seems that for some reason the editing session got reset with empty content. You should be able to recover this state by resetting the editing session for the pages in question via `occ text:reset -f <fileId>`. Make sure that you downloaded a backup of the file in question though to be on the safe side before doing so.

Do you experience the problem with one particular page, or with several pages? Do they have something in common? Also, are you the only user who uses this Collective? Or is it used (simultaneously) by more users?

**Comment by Githopp192** [comment]
Dear Jonas

Thanks for your hints.

I could recover the md file:

- switch to file context
- download the file to the my computer
- the file is not empty - full content is consistent

To your questions:

- how to get the appropr. <file-id> ?
- till now - got this issue 'only' one time (particula page)
- no commen view, pattern seen so far
- user: not the only user - but - i think that one, who does extensively use this app
- simultaneously used by more users? - no - topic is not shared - i'm the only user

**Comment by Githopp192** [comment]
one other (not un-important) thing is : saved pictures via (ctrl-v):

![image](https://github.com/nextcloud/collectives/assets/32612067/5a019861-65bf-408e-9b15-e07d0521590a)

When clicking on this image: 

a complete other picture is shown:

![image](https://github.com/nextcloud/collectives/assets/32612067/34c1cd14-ccf8-4bea-9c84-51af509d8e4d)

other pictures are not there anymore.

Jonas, I don't want to be rude - I develop software myself and I know it's quite demanding.
Yes - and I really appreciate your work!

On the other hand, people like me are using this app very intensively and then see that certain data, images etc. are no longer available. This should not happen under any circumstances. This should be better tested before such an important core app goes live.

**Comment by mejo-** [comment]
> how to get the appropr. file-id ?

When opening the page in question, the URL contains `fileId=<number>` in the query part. That's the fileId in question.

> simultaneously used by more users? - no - topic is not shared - i'm the only user

And did you open the page in question with several clients/browsers simultaneously? E.g. on mobile and desktop at the same time? Just trying to understand which usage pattern brought the empty content.

By the way, that's a bug in the Nextcloud Text app and it's already tracked here: https://github.com/nextcloud/text/issues/5215

> On the other hand, people like me are using this app very intensively and then see that certain data, images etc. are no longer available. This should not happen under any circumstances. This should be better tested before such an important core app goes live.

I get your point. I can reassure you that we're testing extensively, but as you know as a software developer it's hard to spot all corner cases. Regarding the attachments bug, could you open a separate issue to track and debug this?

**Comment by Githopp192** [comment]
Thx Jonas, 

occ text:reset did work

& thx for confirming the bug in the "text app".

regarding the attachments bug - yes, did open another issue on this context.

**Comment by Aveyron-RetD** [comment]
To add to the bug report i have defaulted to EDIT mode.
What i can observe when scrolling through different pages of collectives, is you see  briefly the view mode before the edit mode is displayed. The rendering of the view mode is currently broken.

**Comment by max-nextcloud** [comment]
@Githopp192 Do you have a rough idea of when you last edited the page in question before it showed as empty - or more precisely which version of Nextcloud you were running at that time?

We fixed a bug recently that could lead to this state. However the fix would not recover from the state automatically - it just avaoids creating it. So maybe the page got into that state during your last edit and only now it showed. Is that possible?

**Comment by max-nextcloud** [comment]
@Githopp192 The fix was in 27.1.7. - so this is most likely a leftover from the old bug. I will close this issue. Please reopen / open another one in case you observe this again with a page saved on 27.1.7 or later.
