### ISSUE TITLE
Updated to Collectives 2.10.0 and it broke nextcloud

### ISSUE THREAD

**Issue by ancashoria** [nextcloud/collectives#1146]
**Describe the bug**
Nextcloud 28.0.2:
<img width="789" alt="Screenshot 2024-03-08 at 1 50 06 PM" src="https://github.com/nextcloud/collectives/assets/4144110/0cf2ab25-d301-4536-a123-9e81176dbdb6">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server details:**
- Collectives app version: [e.g. 2.8.2; see Nextcloud apps page]
- Nextcloud version: [e.g. 26.0.1]
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by juliushaertl** [comment]
Thanks for reporting. Can you please check the Nextcloud log for errors? That should give a clear hint on what went wrong.

**Comment by ancashoria** [comment]
False alarm, I just needed to wait one minute. Everything is back and working.
