### ISSUE TITLE
v2.10.0: Add support public page shares: public page is empty

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/collectives#1147]
Tested this new function. I can generate the link, but the page is always empty, only the title is there.

**Comment by mejo-** [comment]
Dear @jakobroehrl, thanks for your report. Did you use the functionality to share a collective via link beforehands? Did this work? Could you try and see whether sharing a complete collective via link has the same issue?

Also, could you open the browser console while trying to open the share link and see whether any error messages are logged there?

**Comment by jakobroehrl** [comment]
Thanks for you reply. 
Sharing a complete collective works. 
Sharing only one page does not work. I use 27.1.7 on this server. 
If I test the one page sharing on a server with 28.0.3, there it works.
Here the error message on 27.1.7
![grafik](https://github.com/nextcloud/collectives/assets/24530680/8876b7ba-87e5-4790-8c14-cf00bd6dd77f)

**Comment by jakobroehrl** [comment]
I still have the problem on one server. It's not the version 27.1.7, the problem still remains after the update to 28.0.3:

![grafik](https://github.com/nextcloud/collectives/assets/24530680/912889a6-d1cb-4e4b-81c2-14c55cc97729)
![grafik](https://github.com/nextcloud/collectives/assets/24530680/9dfb2f95-147d-4b70-82e9-141d2d35482e)

**Comment by mejo-** [comment]
Could you paste a screenshot of the network tab? There should be unsuccessful requests, right?

**Comment by mejo-** [comment]
Also, you wrote that you have this problem on *one* instance? Do you have other instances where it works as expected?

Since I failed to reproduce this locally and know about several instances where it works, it would be helpful to get a better understanding of what is different on your instance. Would you mind to share your config dump (`occ config:list`) with me privately? You can reach me at jonas at freesources dot org.

**Comment by jakobroehrl** [comment]
Found the bug! 
Sharing a page directly under the collective works but not, if it's in a sub dir:

![grafik](https://github.com/nextcloud/collectives/assets/24530680/2e0a6ff9-9b79-426e-a5d5-1f39b49d5f54)

![grafik](https://github.com/nextcloud/collectives/assets/24530680/ad39fb01-2d68-44b1-b9cf-d914c47e64d8)

**Comment by Ornanovitch** [comment]
I have the same problem, can confirm that!

**Comment by mejo-** [comment]
Thanks @jakobroehrl, now I was able to reproduce this. Fix incoming.
