### ISSUE TITLE
Lack of space between elements in left sidebar

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/collectives#1170]
on current beta4 of Nextcloud 29 with collectives v1.19.0

<img width="394" alt="2024-03-21 17_15_37-Nextcloud Handbook - Collectives - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/collectives/assets/1315170/c080f617-5b89-46f6-b77b-fe71093be503">

* hamburger menu overlaps with text field
* no space between textfield and first item in the list of items

**Comment by mejo-** [comment]
Thanks for reporting :)

This already got fixed as part of #1155 :blush:

**Comment by AndyScherzinger** [comment]
Sorry for the noise @mejo- yet happy top read it already got resolved! Nice work 😃
