### ISSUE TITLE
Delete collective dialogue - text truncated

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/collectives#1189]
**Describe the bug**
The text on the UI buttons are truncated.

**To Reproduce**
1. Delete a collective. This sends it to the recycle bin / `Deleted collectives` area
2. Click `Deleted Collectives`
3. click `...` on collective, select `Delete permanently`
4. "Permanently Delete" dialogue appears

**Expected behavior**
Able to read ALL text on buttons

**Screenshots**
![image](https://github.com/nextcloud/collectives/assets/7018928/36f758cf-e33c-4b87-9c9d-a37b5a8281e0)

**Server details:**
- Collectives app version: 2.10.1
- Nextcloud version: 29.0.0 RC2 
- PHP Version: 8.1.2
- Database: 	PostgreSQL 10.15

**Client details:**
 - OS: Linux/NixOS
 - Browser: Chromium 123.0.6312.86, Firefox 124.0.1
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment]
This is fixed now with #1253
