### ISSUE TITLE
Search pages box doesn't find subpages anymore

### ISSUE THREAD

**Issue by dickselis** [nextcloud/collectives#1191]
**Describe the bug**
With Previous versions also subpages wich matches the search our displayed.
Now it only find the master pages.

**To Reproduce**
1. type a part of a the subpage title
2. the subpage is not found

**Expected behavior**
All pages AND subpages which matches the search keywords are displayed.

**Screenshots**

**Server details:**
- Collectives app version: 2.10.1
- Nextcloud version: [Nextcloud Hub 7] (28.0.4) 
- PHP Version: 8.2.1
- Database: PostgreSQL 14.11

**Client details:**
 - OS: Ubuntu
 - Browser: Chrome,Firefox,Edge,DuckDuckGo...
 - Browser version: chrome 123.0.6312.86
 - Device: Desktop

<details>
<summary>Logs</summary>

#### Browser log

</details>

**Comment by pjrobertson** [comment]
I came here with the same problem, and can confirm that #1193 fixes the issue 👍
