### ISSUE TITLE
Image fails to load with 403 after insertion

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/collectives#1201]
**Describe the bug**
After editing a new page and inserting a new image the image won't render and displays a 403 error in view mode:

![grafik](https://github.com/nextcloud/collectives/assets/97337118/370b4a71-c09f-449a-8cdd-3a883167580f)

**To Reproduce**
1. Create a new page in a collective
2. Insert an image
3. Click done
4. See failed image rendering with 403 error
5. Reload the page to see that the image upload was successful.

**Expected behavior**
Show the image right away.

**Server details:**
* local cypress run against current master
* cloud.nextcloud.com on 29.0.0.rc4

**Failed network request**

The failed network request actually seems to come before even inserting the image.
![grafik](https://github.com/nextcloud/collectives/assets/97337118/c804dfa1-580e-4ef9-9376-2f9a7e1c2a4b)

**Comment by max-nextcloud** [comment]
I noticed this while working on the `Supports page content editing and switching to read mode` pages spec. So it looks like we may have a failing test for it already.

**Comment by Aveyron-RetD** [comment]
This also affects 28.0.4.

**Comment by sen4git** [comment]
Noticed the same behavior under 28.0.3 and 29.0.0

![JPG_2024-05-28](https://github.com/nextcloud/collectives/assets/170460098/0dfda2bc-5124-4a11-8a44-a59e4ee5240d)


Server details:

    Collectives app version: [2.11.0]
    Nextcloud version: [29.0.0] and [28.0.3]

Client details:

    OS: [Linux Mint 21.3]
    Browser: [Firefox 126.0, Chromium 124.0.6367.201]
    Device: [desktop]

**Comment by sen4git** [comment]
Sorry - I'm not admin and have to wait for upgades ...

**Comment by LeutholdF** [comment]
Hello,
We have same issue on our nextcloud instance.

Server details:
Nexcloud version: [28.0.5]
Collectives version : [2.11.0]

**Comment by chmac** [comment]
We're just getting hit with this recently. Has anyone found a workaround? Does re-uploading the image help?

**Comment by mejo-** [comment]
To me it seems like this happens when opening the document creates a new editing session for the document. For documents that already have an editing session, I cannot reproduce the issue.

How to check: when you face this issue, please navigate to another page and then go back to the page where you hit this problem. Now the images should load even in view mode. Could those that still face this issue please check if this is true for you?

**Comment by mejo-** [comment]
> @mejo- seems that this has been fixed. What's the release schedule for this fix?

This should be fixed with nextcloud 29.0.3 and 28.0.8.
