### ISSUE TITLE
[Bug] Collectives not working at all on iPad - Blank Screen

### ISSUE THREAD

**Issue by hilltopmediadesign** [nextcloud/collectives#1209]
**Describe the bug**
Viewing Collectives version 2.10.1 on iPad shows blank screen. Working properly on desktop and Android mobile.

**To Reproduce**
1. Click on Collectives link from navigation on iPad

**Expected behavior**
Collectives app appears

**Screenshots**
[
![IMG_3332](https://github.com/nextcloud/collectives/assets/659569/9250102b-4ac8-4e31-aaaf-7e7cbcaed097)
](url)

**Server details:**
- Collectives app version: 2.10.1
- Nextcloud version: 28.0.1 - 28.0.4
- PHP Version: 8.2
- Database:  MariaDB 10.5

**Client details:**
 - OS: iPad OS 16.3.1
 - Browser: Safari
 - Device: iPad 6th Gen

**Comment by hilltopmediadesign** [comment]
Confirming this issue is fixed when updating to ipadOS 17 or higher.

**Comment by hilltopmediadesign** [comment]
Here’s my safari js debug for future reference:

[Error] SyntaxError: Invalid regular expression: invalid group specifier name
(anonymous function) (updatenotification-init.js:1)
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
RegExp (core-common.js:2:3485291)
(anonymous function) (core-common.js:2:3485291)
r (core-unified-search.js:2:43840)
(anonymous function) (core-unified-search.js:2:7196)
r (core-unified-search.js:2:43840)
(anonymous function) (core-unified-search.js:2:44137)
(anonymous function) (core-unified-search.js:2:45355)
Global Code (core-unified-search.js:2:45360)
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
RegExp (viewer-main.mjs:2067)
Module Code (viewer-main.mjs:2067)
evaluate
moduleEvaluation
[Error] TypeError: undefined is not an object (evaluating 'OCA.Viewer.registerHandler')
(anonymous function) (files_pdfviewer-main.js:2:378748)
(anonymous function) (files_pdfviewer-main.js:2:378856)
Global Code (files_pdfviewer-main.js:2:378860)
[Error] [ERROR] text: Viewer app is not installed
Object

app: "text"

level: 2

uid: "michael"

Object Prototype
value (text-viewer.js:2:11066)
value (text-viewer.js:2:11536)
(anonymous function) (text-viewer.js:2:75251)
(anonymous function) (text-viewer.js:2:76132)
Global Code (text-viewer.js:2:76136)
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
RegExp (collectives-main.js:2:2984963)
(anonymous function) (collectives-main.js:2:2984963)
o (collectives-main.js:2:4241986)
(anonymous function) (collectives-main.js:2:4261697)
(anonymous function) (collectives-main.js:2:4550250)
Global Code (collectives-main.js:2:4550254)

**Comment by mejo-** [comment]
Dear @hilltopmediadesign, thanks for your report. Good to know that it has been fixed after upgrading to iPad OS 17.
