### ISSUE TITLE
"Share with guests" menu entry on collective page is not consistent with guests meaning in Nextcloud (Guests app)

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/collectives#1225]
**Describe the bug**
"Share with guests" menu entry on collective page is not consistent with guests meaning in Nextcloud (Guests app)

"Share with guests" menu entry on collective page allows you to create a public link to a collective page. As it is public link, theoretically, the user accessing the page is anonymous to Nextcloud.

In Nextcloud, Guests accounts are specials user accounts. But from a Nextcloud standpoint, it is a known and registered user.

The naming "Share with guests" is confusing in that regard.
@mejo- @jancborchardt 

**To Reproduce**
1. Go to a collective
2. Click on the three dot menu
4. Click "Share with guests"
5. What you can do is create a public link, not sharing with a guest (user) in the sense of Nextcloud.

**Expected behavior**
I would rename Share with Guests to generate public link, or share publicly.

**Screenshots**

**Server details:**
- Collectives app version: [e.g. 2.8.2; see Nextcloud apps page]
- Nextcloud version: [e.g. 26.0.1]
- PHP Version: [e.g. 8.2]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 22]
 - Device: [e.g. iPhone6, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by jancborchardt** [comment]
Yep, to be consistent with how it is in Files, the correct wording would be "Share link".

We never use the wording "public" since it sounds like publishing something globally, which is not what is happening since the link is still quite private (and has a lot of security options too).
