### ISSUE TITLE
When app is enabled, in calendar app links to create a calendar from subscription and to create a new rendez-vous are not visible

### ISSUE THREAD

**Issue by unteem** [nextcloud/collectives#1244]
**Describe the bug**
When app is enabled, in calendar app links to create a calendar from subscription and to create new appointments  are not visible
If disabled we can see those links

See below this screenshot

![20240503_17h25m41s_grim](https://github.com/nextcloud/collectives/assets/5905254/e028eacf-0e11-4cde-8d2c-ae3df92b1922)

**Server details:**
- Collectives app version:  2.9.2
- Nextcloud version: 27.1.9

**Comment by arnowelzel** [comment]
Works fine here with Nextcloud 29.0.0 and collectives 2.10.1. Maybe you should update to the latest versions.

![image](https://github.com/nextcloud/collectives/assets/6613614/f8248b37-982e-4745-bb48-bee1135bbd50)

**Comment by mejo-** [comment]
@unteem I'm also unable to reproduce this issue with Collectives 2.10.1 and Nextcloud 28 and 29. Please update to latest Collectives version and ideally to Nextcloud 28 and see if this solves the issue for you.
