### ISSUE TITLE
It is impossible to change the sort order of pages within a level

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/collectives#1246]
**Describe the bug**
Originally it was possible to move pages in the list on the left side up and down to change their order.

**To Reproduce**
1. Create multiple pages.
2. Make sure, that "Sort by custom order" is enable for the list of pages on the left.
3. Try to drag a page in the list to change its position in the list.
4. Realize, that it is impossible to change the position, you can only move a page into another one as child or back to the top so it will become the first page below the start page of the collective.

**Expected behavior**
It should be possible to move a page between two other pages to change the position in the list.

**Screenshots**

https://github.com/nextcloud/collectives/assets/6613614/f3f0b403-2a43-4301-80db-75a6758ef9b9

**Server details:**
- Collectives app version: 2.10.1
- Nextcloud version: 29.0.0
- PHP Version: 8.3.6
- Database: MariaDB 10.6

**Client details:**
 - OS: Windows
 - Browser: Chrome (but also happens with Firefox)
 - Browser version: 24.0.6367.119
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
```

#### Browser log
```
```

</details>

**Comment by mejo-** [comment]
Thanks for the report @arnowelzel. #1258 will fix this issue.
