### ISSUE TITLE
top left search finds only some pages, not others

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/collectives#1247]
**Describe the bug**
top left search finds only some pages, not others

**To Reproduce**
see internal report https://github.com/nextcloud-gmbh/sysadmin/issues/1389
basically, search "keyword", results include some pages that have "keyword" in the title, but not all of them

**Expected behavior**
all page titles that have the search term in them should be listed

**Server details:**
NC 29, cloud.nextcloud.com on May 2, 2024

Tell me if you need more info.

**Comment by mejo-** [comment]
Dear @alexanderdd, this should be fixed by now. There was a bug that resulted in only top-level pages being searched. Could you check back and report if the problem still exists for you?

**Comment by alexanderdd** [comment]
@mejo- thank you, works as expected now :partying_face: (NC  29.0.3)
