### ISSUE TITLE
Leaving a collective does not work

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/collectives#1259]
I created so test collectives with only me as a user. 
But now I can't delete them. 
Leave collective works but the collective shows up again after a page reload
Latest NC and collective version, tested on two different servers.
Console error message:

`
Failed to leave collective 
Object { stack: "r@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3264207\nr@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3271038\nC@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3257904\nEventHandlerNonNull*6672/_</<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3258073\n6672/_<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3256956\nc@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3269390\n_request@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3263384\nrequest@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3261918\n5411/</t/<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3263864\n6524/a/<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:3275412\nLEAVE_CIRCLE@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4537651\nE/</<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4253770\nv.prototype.dispatch@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4255534\nv/this.dispatch@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4250991\nB</</n[a]@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4258161\nleaveCollectiveWithUndo/this.leaveTimeout<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4307255\nsetTimeout handler*leaveCollectiveWithUndo@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4307233\nclick@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:4309119\ncn@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1588150\nn@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1580943\ncn@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1588150\n144/e.prototype.$emit@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1610020\nonClick@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:2328244\nhandleClick@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:2329627\ncn@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1588150\nn@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1580943\n144/Pr/i._wrapper@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1621065\nEventListener.handleEvent*Pr@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1621091\nTt@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1581230\nIr@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1621472\n_@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1630345\nh@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1629651\nf@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1630102\nh@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1629636\n144/Di@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1633645\n144/e.prototype._update@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1610172\na@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1641153\n144/e.prototype.get@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1591686\ne@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1591599\n144/Pa.prototype.$mount/<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1641177\n144/Pa.prototype.$mount@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1641395\ninit@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1596477\n144/h/<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1629245\nh@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1629522\nf@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1630102\nh@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1629636\n144/Di@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1633645\n144/e.prototype._update@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1610172\na@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1641153\n144/e.prototype.get@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1591686\ne@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1591599\n144/Pa.prototype.$mount/<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1641177\n144/Pa.prototype.$mount@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1641395\ninit@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1596477\n144/h/<@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1629245\nh@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1629522\nf@https://nc.server.de/custom_apps/collectives/js/collectives-main.js?v=e6816f56-16:2:1630102\n", message: "Request failed with status code 400", name: "AxiosError", code: "ERR_BAD_REQUEST", config: {…}, request: XMLHttpRequest, response: {…} }
​
code: "ERR_BAD_REQUEST"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​​
adapter: Array [ "xhr", "http" ]
​​
data: undefined
​​
env: Object { FormData: (), Blob: () }
​​
headers: Object { Accept: "application/json, text/plain, */*", "Content-Type": null, requesttoken: "dQ/e27musdLX7G+Rh87N8RErDqZG+WxZHtA9bgRFHZg=:PEDnmNbcgb6uojfVwpyMuWgcN5AttTkKT+B+I1cUdKw=" }
​​
maxBodyLength: -1
​​
maxContentLength: -1
​​
method: "put"
​​
timeout: 0
​​
transformRequest: Array [ transformRequest(e, t)
 ]
​​
transformResponse: Array [ transformResponse(e)
 ]
​​
transitional: Object { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }
​​
url: "https://nc.server.de/ocs/v2.php/apps/circles/circles/TXgsE1mSwYWHbtMESpfKHQFoCZuwYWK/leave"
​​
validateStatus: function validateStatus(e)
​​
xsrfCookieName: "XSRF-TOKEN"
​​
xsrfHeaderName: "X-XSRF-TOKEN"
​​
<prototype>: Object { … }
​
message: "Request failed with status code 400"
​
name: "AxiosError"
`

**Comment by mejo-** [comment]
>  But now I can't delete them.

In the settings for the collective you should find an option to delete it.
