### ISSUE TITLE
Internal links don't work with public shares

### ISSUE THREAD

**Issue by chmac** [nextcloud/collectives#1275]
**Describe the bug**
When sharing a collective publicly, internal links within the collective do not work.

**To Reproduce**
1. Create a collective with 2 pages
2. Add a link on page 1 to page 2
3. Share the collective
4. Open the shared link in a private window

**Expected behavior**
I would expect internal links to work with the same sharing permissions as the shared link.

**Server details:**
- Collectives app version: 2.11.0
- Nextcloud version: 29.0.0

**Comment by estux** [comment]
Hello, I'm experiencing the same bug. 
I have a public share and have a page with some links to other pages of the same Collective.
Whenever I click on the links the result is a blank page (with only Nextcloud background visible).
But if I reload the page (using the browser "Reload page" feature) the destination page is shown.
I hope this helps

**Comment by xavi-GH** [comment]
> **Describe the bug** When sharing a collective publicly, internal links within the collective do not work.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Create a collective with 2 pages
> 
>     2. Add a link on page 1 to page 2
> 
>     3. Share the collective
> 
>     4. Open the shared link in a private window
> 
> 
> **Expected behavior** I would expect internal links to work with the same sharing permissions as the shared link.
> 
> **Server details:**
> 
>     * Collectives app version: 2.11.0
> 
>     * Nextcloud version: 29.0.0

As a workaround,  one can select directly the .md file:
 Clip icon -> Link to file or folder ->  select directly the ".md" file of the page:
(tested in NCv27, Collectives: 2.12.0)

Find attached this small screencap. : 

https://github.com/nextcloud/collectives/assets/168458684/db6c557b-0f8c-4944-ac16-f401abf38bf7


In "Other methods", the first 3 produce this output:
![Screenshot_20240711_180727](https://github.com/nextcloud/collectives/assets/168458684/1ce4feac-e5be-4bb3-9138-0c96c681992a)

**Comment by chmac** [comment]
@mejo- Thanks for fixing this, that's awesome. Do you know when the changes will land in Nextcloud? I've just updated and I'm still seeing this issue, so I figure maybe it's not yet in the release I'm running?

**Comment by mejo-** [comment]
@chmac unfortunately this will only work with Nextcloud 30 or newer. Nextcloud 30 is about to be released on 14. September.

**Comment by chmac** [comment]
@mejo- Sweet, thanks for the clarification. It will be a big help to our use case, happy to wait a bit for the release. 🧡

**Comment by chmac** [comment]
@mejo- We're live on Nextcloud 30 now, and I have Collectives v2.14.3, but I'm not sure if this change is included in that version or not. I've tried to check the commit log on main, but I can't figure it out. This fix is in main, but I don't know enough about how the app is built to know if main is now v2.14.3 or not. Do you know which version of Collectives will have this fix in it?

**Comment by mejo-** [comment]
@chmac this should work with Nextcloud 30.0.0 and latest Collectives. If not, could you take a look at the network tab in your developer tools and the console if there's any errors? Also, did you force-reload to make sure the client cache got cleared?

**Comment by chmac** [comment]
@mejo- Okay, I think that it's working! I realise I might have been creating the wrong kind of links. My links were like `/f/{ID}`. But now I tried the "smart picker" and then I could choose the same page and the inserted link was completely different. That style of link works now. Thanks a lot. 🧡

**Comment by Jerome-Herbinet** [comment]
Same problem for me currently with : 

- Nextcloud 33.0.9
- Text : 7.0.1
- Collectives : 4.7.0
