### ISSUE TITLE
Reuse an existing team

### ISSUE THREAD

**Issue by oculos** [nextcloud/collectives#1276]
**Is your feature request related to a problem? Please describe.**

I have a team from before. It would be nice to be able to create a collective for that team, rather than creating a new team when creating a collective

**Describe the solution you'd like**
When creating a collective, that an option could be offered to attach it to an existing team.

**Comment by mejo-** [comment]
Dear @oculos, this should already be possible. When creating a new Collective, you can press the teams icon button right to the name field and select an existing team. That's only possible for teams that don't have a collective associated yet though.

**Comment by oculos** [comment]
> Dear @oculos, this should already be possible. When creating a new Collective, you can press the teams icon button right to the name field and select an existing team. That's only possible for teams that don't have a collective associated yet though.

Hi @mejo- 

I don't see that button. Is there a bug?

<img width="573" alt="Screenshot 2024-05-18 at 14 42 01" src="https://github.com/nextcloud/collectives/assets/6791923/8f0afda9-4751-4dbc-a9f4-d5d4b3e2b60e">

**Comment by mejo-** [comment]
@oculos could you try to manually create another team with the same user and see whether the button appears afterwards? Are you sure that your user is member of the team that you want to create a collective for? Also, are you sure that there's no collective for this team yet?

| Screenshot |
| --- |
| ![grafik](https://github.com/nextcloud/collectives/assets/3582805/61ff9588-886f-489c-97ce-eadae81fc2ce) |

**Comment by oculos** [comment]
Yes, it worked that way. I created another team, and suddenly the button was there.
Best,
Francis
