### ISSUE TITLE
Responsive Writing not work

### ISSUE THREAD

**Issue by Wfpx** [nextcloud/collectives#1293]
**Describe the bug**
When trying to edit a notebook page in responsive mode from a mobile device, neither the keyboard nor the blinking cursor appears for typing. However, if I rotate the phone to landscape mode, it starts allowing input again.

**To Reproduce**
1. Go to 'Collectives and create a new page'
2. Click on 'browse this page from the mobil or responsive mode whit developer options '
4. See error: try to write 

**Expected behavior**

**Screenshots**

**Server details:**
- Collectives app version: [2.11.0]
- Nextcloud version: [ 29.0.1]
- PHP Version: [all supported]
- Database: [Mysql]

**Client details:**
 - OS: [Windows/macOS and Ubuntu]
 - Browser: [e.g. Firefox, Chrome ]
 - Browser version: [vaious]
 - Device: [S20FE Iphone15]

A viedo here: [errorcollectivesapp.webm](https://github.com/nextcloud/collectives/assets/170772881/54bfd5f8-902d-4c04-b060-10767f7df6f0)

**Comment by mejo-** [comment]
Probably same problem as https://github.com/nextcloud/collectives/issues/1232.

It seems like the problem starts with a screen width of 511px or less. With 512px it's still working. So far I failed to identify the culprit. Maybe something focus-trap related? :thinking:

**Comment by mejo-** [comment]
Tthis is due to NcAppSidebar being open all the time. Fix incoming.
