### ISSUE TITLE
Content previews don't work at all

### ISSUE THREAD

**Issue by br4yd** [nextcloud/collectives#1298]
## Description
**In the Nextcloud App Store the preview image of Collectives shows link / live previews for the content you're relating to.**
![A screenshot of the preview of the Collectives app in the Nextcloud App Store](https://github.com/nextcloud/collectives/assets/116094473/2a06cb2b-5446-45fd-9ea3-663d5f86c5e3)

**I can also add a link using the linking tool via "/" command and set it to show a preview like seen on the screenshot below.**
![A screenshot of the link insert dialogue coming from Nextcloud Collectives](https://github.com/nextcloud/collectives/assets/116094473/819cb008-917e-4db1-ab32-eda614a3a38e)

**However as soon as I paste it, it is like seen here:**
![A screenshot showing that the inserted link is shown as a raw link without any content preview](https://github.com/nextcloud/collectives/assets/116094473/f58daabf-d176-4a6e-b902-0b9f2b43278c)

So there's no preview at all. Same for every other link or embed...

**Expected behavior**
Previews should be shown as they are in the Nextcloud App Store.

**Server details:**
- Collectives app version: 2.11.0
- Nextcloud version: 29.0.1 RC1
- PHP Version: 8.2.18
- Database: PostgreSQL 15.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit

**Client details:**
 - OS: Windows
 - Browser: Firefox
 - Browser version: 126.0
 - Device: Laptop

**Comment by mejo-** [comment]
Thanks for your report @br4yd.

> So there's no preview at all. Same for every other link or embed...

Is there a three-dot menu next to the inserted link? If so, what happens if you select "Preview" from it?

**Comment by br4yd** [comment]
![A screenshot of the pop up that opens up when clicking on the link](https://github.com/nextcloud/collectives/assets/116094473/5ff38075-531c-4975-8210-68ef05e8647c)
No, there's only this when clicking on the link but no preview as there should be.

**Comment by br4yd** [comment]
Ah yes, this way it is working. Thank you! But maybe when inserting the link and when selecting here preview, it should be inserted with the preview. Otherwise why give an option to choose between Text only and preview if this setting isn't respected and have to be set via the 3 dots to work?

**Comment by mejo-** [comment]
Great to hear it's working for your @br4yd. I agree that inserting a link via the smart picker should insert it as preview by default. Let's track this in a new issue and discuss it there: https://github.com/nextcloud/text/issues/5838
