### ISSUE TITLE
Copying text from collective page copies it as markdown when text is expected

### ISSUE THREAD

**Issue by pascalBokBok** [nextcloud/collectives#1300]
**Describe the bug**
When you copy text from e.g. an instruction page with bullets you will get the formatting as part of it `1. 1. * * cp file.txt folder-name` which makes unconvenient for storing text that can be copied.
This is a new behaviour. It used to copy fine on an earlier release.
I assume it was added to easily keep formatting when copying around in collectives. I suspect that the mimetype text/markdown should also be used when copy pasting within collectives.
something akin to:
`event.clipboardData.setData('text/plain', selectedText);
    event.clipboardData.setData('text/html', htmlContent);
    event.clipboardData.setData('text/markdown', markdownContent);`

**To Reproduce**
1. In a page with bullets.
2. mark the text of one of the bullets and copy it.
3. paste into text editor
4. See markdown formatting.

**Expected behavior**
text without markdown formatting.

**Screenshots**

**Server details:**
- Collectives app version: 2.11.0
- Nextcloud version: 28
- PHP Version: 8.1
- Database: Postgresql

**Client details:**
 - OS: Linux
 - Browser: Chrome
 - Browser version: 124
 - Device: desktop

**Comment by mejo-** [comment]
Dear @pascalBokBok, which Nextcloud version to you run? With Nextcloud 28.0.5, we added some related fixes. We discussed this behaviour extensively and decided to copy markdown in most cases but skip marks (like bold, italic, ...). In cases like bulletin lists or numbered lists, markdown actually makes more sense than just the plain text.

See https://github.com/nextcloud/text/pull/5487 for some further context.

**Comment by pascalBokBok** [comment]
Dear @mejo- 
We're on 28.0.3. I didn't realize that it would influence this copy/paste in collectives. Will update that.

But, if I may ask, since it's part fixed. Why is it that you don't just store the both text/raw and text/markdown in the copy event instead of putting a hybrid into text/raw? 
(also you store text/html already)
It's up to the receiving application to choose which of the mimetypes it prefer for the paste event.

**Comment by mejo-** [comment]
> We're on 28.0.3. I didn't realize that it would influence this copy/paste in collectives. Will update that.

Good news then, upgrading will solve your issue :blush: 

> But, if I may ask, since it's part fixed. Why is it that you don't just store the both text/raw and text/markdown in the copy event instead of putting a hybrid into text/raw?

The reason is that `text/markdown` is not used by anyone, so storing data there would not help much. We want to have a readable text version in `text/plain`. It's not about copying between collectives pages. There we can rely on `text/html` which transfers all the formatting details. It's about copying to places that consume `text/plain`, like textfields on websites, some messaging clients, etc..
