### ISSUE TITLE
Links to Videos stored on Nextcloud broken after Update to NC 29

### ISSUE THREAD

**Issue by andrtau** [nextcloud/collectives#1301]
**Describe the bug**
I have linked multiple Videos in collective Pages to give a guide on how to do things.
Before the update i linked them using the add link "clamp".
After the Update the links do not open the video directly, instead there is now some sort of "dropdown" dialog. It offers copy, change or remove link. 
Clicking the link willl open a new tab within nextcloud that says file not found.
Coping the link will only copy the "path" of the file: /Schulungsvideos/Profacto/Rechnungsadresse%20in%20Kunden%20anlegen.mp4?fileId=556192 missing the Domain and apps part of the domain.

Adding new links or deleting and linking it new "solves" the issue. 
It are some 100 links that need to be redone...

**To Reproduce**
1. Go to collectives page with linked video
2. Click on a linked video
3. See error

**Expected behavior**
Open the linked video in videoplayer.

**Screenshots**

**Server details:**
- Collectives app version: 2.11.0
- Nextcloud version: 29.0 Docker
- PHP Version: ? shipped with docker 
- Database: 1:11.2.2+maria~ubu2204

**Client details:**
 - OS: Windows 10 +11
 - Browser: Firefox, Edge

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by sen4git** [comment]
Maybe related problem with videos and PDF:
Videos and PDFs were added to a collective page by drag&drop under v28.0.3.
After Upgrade to v29.0.0 the videos and PDFs c an only be downloaded by a normal member. But they should be displayed.

**Comment by mejo-** [comment]
Dear @andrtau, sorry to hear that your old links broke. We indeed refactored the "link to file" function with Nextcloud 29 due to issues with the old way it worked. We tried to make sure that old links are still working, but apparently they're not in all cases.

Would it be an option for you to migrate the links by downloading the file and running a terminal script over it? If so, I could try to provide you with a simple `sed` command to replace the broken links.

**Comment by andrtau** [comment]
> Dear @andrtau, sorry to hear that your old links broke. We indeed refactored the "link to file" function with Nextcloud 29 due to issues with the old way it worked. We tried to make sure that old links are still working, but apparently they're not in all cases.
> 
> Would it be an option for you to migrate the links by downloading the file and running a terminal script over it? If so, I could try to provide you with a simple `sed` command to replace the broken links.

i have ssh acces to the nextcloud server. 
What files do i need to download? the .md of the collectives page?  and then reupload it? or can the script be run on the server over all files?

**Comment by mejo-** [comment]
> i have ssh acces to the nextcloud server.

You can even edit the files in-place - you just have to make sure to reset the editing sessions and rescan the files afterwards.

You find the markdown files on the server below `data/appdata_<instance-id>/collectives/<collective_id>/`.

Running the following `sed` command should migrate the links in your markdown files. I only did rough tests, so please be careful yourself!

`sed -E -e 's#\(/[^ ?]+\?fileId=([0-9]+)\)#(https://cloud.example.org/index.php/f/\1)#g`

You have to replace `https://cloud.example.org/index.php` with your base url.

Maybe test this with one file first (make a backup before!) and see if the result looks reasonable.

After doing the changes, you have to run `occ text:reset -a -f` to reset all editing sessions and `occ files:scan-app-data` to scan the appdata directory for changes.

I hope that this helps you with the migration. I'll close the ticket as there's nothing to do from our side.
