### ISSUE TITLE
Last changed time of a page updated without editing

### ISSUE THREAD

**Issue by estux** [nextcloud/collectives#1322]
**Describe the bug**
I was just navigating a Collective (where I'm the owner) as a logged in user. I was opening some pages in Read Mode and stopped in one page for more time to read thoroughly the content. Later I just opened the right sidebar and checked all the tabs before closing it again (without modifications). After that I continued navigating through other pages (without editing). 
I went to Activity and checked that the system registered a file edit action for that opened page. Also going again to that page in the Collective I saw the "Last Changed by" time updated.

I admit this bug is a bit tricky as it seems to not always happen "after something" and it appears apparently randomly. I'm still trying to understand a possible trigger action.

**To Reproduce**
1. Go to one Collective
2. Navigate some pages in Read Mode
3. Open the right sidebar to just check settings and don't edit them.
4. Continue navigating through other pages
5. Check Activity module to see if a file edit action was registered.

**Expected behavior**
No edit action registered as I didn't edit any file.

**Screenshots**

**Server details:**
- Collectives app version: 2.12.0
- Nextcloud version: 28.0.6
- PHP Version: 8.2.14
- Database: mysql 10.5.23

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Browser version: 127.0
 - Device: laptop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment]
There was a bug that resulted in the last changed timestamp being updated when pages got moved around. Could this have been the culprit? Are you still able to reproduce with latest Collectives and Nextcloud 28?

**Comment by estux** [comment]
Hello @mejo- nice to hear you again! 
I saw that bug but this one is not related as it happens without doing any active action.
Sometimes just opening the Collective and staying for some time in a page to read it triggers something to update the timestamp of the last edit session of the page. 
I admit this bug is a bit tricky to catch!
I'm using the last stable version of Nextcloud 28 and last version of Collectives.
Thanks for your work!
