### ISSUE TITLE
Read Permissions for Subpages only

### ISSUE THREAD

**Issue by mirisbowring** [nextcloud/collectives#1329]
**Is your feature request related to a problem? Please describe.**

We are documenting our Infrastructure and Services within a Collective.  Below our "Company-Collective" we have multiple Top Level Pages like "Admin Docs", "User Docs", "Harware Docs", etc.

While it is OK for the Moderators to have access to all pages, we would like to grant users only access to the Users Section.

**Describe the solution you'd like**
Ideally I would like to have the Option to grant Permissions to Users/Groups for Subsections.

**Describe alternatives you've considered**
The alternative solution would be to migrate all top level sections to dedicated collectives I think.

**Additional context**
Probably this is also a general Question on how this App was designed.

Thanks!

**Comment by mejo-** [comment]
Dear @mirisbowring, thanks for your report. We currently don't have plans to allow fine-grained permissions per page in Collectives, as this would add quite some complexity to the app. The recommended solution would be to use separate collectives for content that needs different permission settings.
