### ISSUE TITLE
Missing option in menu to return to normal text from title

### ISSUE THREAD

**Issue by pascald0210** [nextcloud/collectives#1354]
An option is missing in the menu: if you choose a title, there is no possibility of returning to normal text.

**Comment by mejo-** [comment]
Hey @pascald0210. Do you mean removing the heading (h1-h6) style? You can just unselect the current heading style in the menu. E.g. if you selected 'h3', just click on 'Heading 3' again. Does this work for you?

**Comment by pascald0210** [comment]
Yes it works.
