### ISSUE TITLE
Page listing performance

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/collectives#1357]
For tracking and discussing some ideas on performance improvements for loading the collective list.

Currently one of our collectives with 571 pages has a loading time of 3-5 seconds, mostly due to iterating over all pages in the collective and listing them.

Long term some kind of lazyer/paginated loading might be nice,  but maybe there are some quick wins.

<img width="2374" alt="Screenshot 2024-07-08 at 09 03 58" src="https://github.com/nextcloud/collectives/assets/3404133/3ffa9871-2c3b-4739-8e97-c4cfbf1aa563">

Zoomed in for one call:
<img width="2373" alt="Screenshot 2024-07-08 at 09 07 37" src="https://github.com/nextcloud/collectives/assets/3404133/f7110306-7ba6-49ea-9bb7-ff5d00ee386b">

**Comment by juliushaertl** [comment]
Looking at https://github.com/nextcloud/collectives/blob/d47ffd2ecb84322d221ccbb7d6769251f12fcb77/lib/Service/PageService.php#L379 briefly it seems we could at least avoid getting the index page separately and instead detect it within the existing getDirectoryListing loop.

In addition maybe getPageByFile usages could be optimized in a way that we first fetch all files for the collective listing and then do one query to get all page infos by the fileids.

**Comment by mejo-** [comment]
This got implemented with https://github.com/nextcloud/collectives/pull/1403
