### ISSUE TITLE
Configure path like most other plugins

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/collectives#1379]
As far as I understand it, I can only store collectives in the main folder. I can't move them to a subfolder.

It would be cool to be able to move them into any folder - like here for example in Calendar:
![Screenshot 2024-07-23 at 12-20-59 Juli 2024 - Kalender - plan neo cloud](https://github.com/user-attachments/assets/e216c166-925b-4e72-b8c7-66d6b467ca13)

Moreover it would be cool, if the folder was hidden by default to not confuse new users.

See: https://github.com/nextcloud/server/issues/46309

**Comment by mejo-** [comment]
@kaffeeringe thanks for your report. This is already tracked in https://github.com/nextcloud/collectives/issues/514, closing this one as duplicate therefore.
