### ISSUE TITLE
Design review notes 2024-07-30

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/collectives#1397]
**Bold items are considered high priority**

- [x] New collective dialog
  - [x] Name too short should be left aligned, color max contrast, debounce 
  - [x] New collective should move from NcModal to NcDialog
  - [x] Title on the empty content should not have a title on the icon
  - [x] **In the user picker the text is not fully centered, check mark is not fully on the right**
  - [x] Own user should be primary highlight
  - [x] Can we show and suggest some users, like in talk
- [x] Manage members dialog
  - [x] Has two scrollbars
  - [x] Three dots is not fully right aligned
  - [x] Remove member should be red (maybe as a standard)
  - [x] (admin) and moderator text can be regular instead of light
- [x] **Title placeholder should be same size as the text and max contrast without opacity**
- [x] **Emoji in the page title header is not full opacity**
- [ ] **Maybe make the Test collective rather bold?**
- [x] **Make the collective title / page title regular h2 style**
- [x] Navigation icon for collective (emoji) is too big, should be 20px
- [ ] Team overview button should open in a new tab
- [x] "New Page" and "Team Overview" should have lower case letter on the second word
- [x] Sharing sidebar
  - [x] **Check error on daily**  @[Julius Härtl](mention://user/julius)  
  - [x] Jumping when clicking the button
- [x] Attachments sidebar
  - [x] Info text can replace the empty content message
- [x] Page menu (top right)
  - [x] **Open page sidebar can be removed (quick fix)**
  - [x] Full witdth checkbox out of place, mabye using the old component
- [ ] Collectives settings
  - [ ] Too much whitespace before headings (section element)

**Comment by mejo-** [comment]
Thanks for collecting the feedback. While addressing the items, a few questions came up @juliushaertl @jancborchardt @nimishavijay:

>  Maybe make the Test collective rather bold?

Some time back we purposely changed the collective title from bold to a slightly bigger font in the pagelist due to negative user feedback about the bold title. Users thought it would mean "unread" and described the urge to click on it to mark it read. So I don't think it's a good idea to change this to bold again.

> Make the collective title / page title regular h2 style

What's the background here? Currently the whole titleform is inside a `h1` element.

> Sharing sidebar -> Check error on daily @Julius Härtl

What does this mean?

> Attachments sidebar -> Info text can replace the empty content message

What's meant here? Here's how an empty attachments sidebar currently looks. What can replace what?

![grafik](https://github.com/user-attachments/assets/af26c3ab-0a9f-4eb0-9b08-a08ee2b9892e)

**Comment by mejo-** [comment]
> Collectives settings -> Too much whitespace before headings (section element)

This is the default of `NcAppSettingsSection`. It looks the same in the settings for talk rooms.

**Comment by jancborchardt** [comment]
> > Maybe make the Test collective rather bold?
> 
> Some time back we purposely changed the collective title from bold to a slightly bigger font in the pagelist due to negative user feedback about the bold title. Users thought it would mean "unread" and described the urge to click on it to mark it read. So I don't think it's a good idea to change this to bold again.

From an information hierarchy point, comparing the two solutions, with bigger text or bold heading style, the bold heading style just makes it much clearer that it is the collective title.


> > Make the collective title / page title regular h2 style
> 
> What's the background here? Currently the whole titleform is inside a `h1` element.

Same here, when testing the two against each other, normal h2 style with bold text just looks much better than simply increasing the size and keeping it grey, which doesn’t make it look like a heading.
Also regarding accessibility and semantics, it should not be h1 but instead h2. The "Nextcloud" logo and text in the top navigation is the only allowed h1.

**Comment by mejo-** [comment]
> From an information hierarchy point, comparing the two solutions, with bigger text or bold heading style, the bold heading style just makes it much clearer that it is the collective title.

I see your point. But given that this change feels controverse, I'd rather prefer to discuss this again and postpone it for now.

> Same here, when testing the two against each other, normal h2 style with bold text just looks much better than simply increasing the size and keeping it grey, which doesn’t make it look like a heading.
> Also regarding accessibility and semantics, it should not be h1 but instead h2. The "Nextcloud" logo and text in the top navigation is the only allowed h1.

Thanks for the additional context. Makes sense, changed to `h2` with default `h2` style now.
