### ISSUE TITLE
Enhanced smartphone swipe support

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#140]
We should allow swiping between the components `Nav`, `PagesList` and `Page`.

`nextcloud-vue` already has the property `allowSwipeNavigation` for component `AppContent` ([Link to code](https://github.com/nextcloud/nextcloud-vue/blob/b1d53388b6aaae47a5609f2dc5fe476aca821c1f/src/components/AppContent/AppContent.vue#L43-L76)). Unfortunately, it doesn't support changing the property after being mounted yet.

**Comment by max-nextcloud** [comment]
The way collectives currently handles this is consistent with what other apps do.
