### ISSUE TITLE
Useful Collectives Features Request

### ISSUE THREAD

**Issue by ddaviscomsec** [nextcloud/collectives#1419]
Hi,

I work for a international development organisation called "The Commonwealth Secretariat" (www.thecommonwealth.org).

We are planning to use next cloud to launch a collaborative platform for some of our member states.

We believe the following features would be very useful in collectives and were wondering if you would consider including them:

1. Permissions at eh pages level not only the collective level so we can create pages and provide only a subset of users to access it.
2. Collectives within collectives. (if this is possible then the first feature request would be unnecessary because I presume there would already be unique or inherited permissions at the collective level)
3. The possibility to embed iframes into collectives. We would like to embed power bi visualisations into the pages.
4. The ability to restrict who can create collectives. Perhaps tie collective creation to a group or team.

We believe the addition of these features would make the collective application much more robust and useful.

Thanks for considering these!

**Comment by mejo-** [comment]
Dear @ddaviscomsec, thanks for your feedback. It's easier for us to track each idea in a separate issue though. Let me close this issue therefore as not planned, but please don't hesitate to open individual issues for the ideas you have.

Some comments on your thoughts:

1. We currently don't have plans to allow fine-grained permissions per page in Collectives, as this would add quite some complexity to the app. The recommended solution would be to use separate collectives for content that needs different permission settings.
3. How does it look like if you add a link to a 'power bi visualisation' and configure the link as preview? I think this should be the proper way to embed objects these days.
4. Why would you disallow your users to create collectives on their own for self-organizing?
