### ISSUE TITLE
Top titlebar is too high and leaving a gap to the bar below

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/collectives#1426]
**Describe the bug**
The title bar is positioned too high and thus leaving a blank space to the next line where the content is displayed when scrolling a page up.

**To Reproduce**
1. Create a page.
2. Add enough content that scrolling is neccessary.
3. Scroll the page up
4. See the text from the page displayed partly between the top title bar and the document info/edit bar.

**Expected behavior**
The title bar is positioned correctly.

**Screenshots**

Page in view mode:

![image](https://github.com/user-attachments/assets/94e1eaff-1fb3-4151-b884-1c113664d630)

Page in edit mode:

![image](https://github.com/user-attachments/assets/315fe785-e722-49f5-a229-7947f8e249dc)

**Server details:**
- Collectives app version: 2.13.0
- Nextcloud version: 29.0.3
- PHP Version: 8.3
- Database: MariaDB 10.6

**Client details:**
 - OS: Windows 11
 - Browser: Firefox, Chrome, Vivaldi, Edge
 - Browser version: latest versions as of 2024-08-18
 - Device: desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)

(not relevant)

#### Browser log

```
```
</details>

**Comment by mejo-** [comment]
Hey @arnowelzel, thanks for the report. This got fixed with the latest 2.14.0 release of Collectives.

**Comment by arnowelzel** [comment]
Ok, there is no visible text any longer. But the bar is still higher as it should be. In older versions, there was an 8px padding to the top, now it still looks like the bar is nearly stuck at the top border - this is the original reason, why the text was visible at all:

![image](https://github.com/user-attachments/assets/74dd67c5-d3fe-4614-8f3a-3e26c3e74c93)

Just moving that to to 8px padding from the top would have fixed it as well.

For comparison - the "Search" box on the left is also not that close to the border:

![image](https://github.com/user-attachments/assets/35622bd4-92ec-4fe2-9ac8-27081f0afefe)

I fixed this by applying a custom style in my own instance:

```
.app-collectives #titleform {
  padding-top: 8px !important
}
```

Result:

![image](https://github.com/user-attachments/assets/effb7071-8ccd-4a90-ae8e-54479ca233ca)

**Comment by mejo-** [comment]
Thanks @arnowelzel. The reason for the title bar being too close to the top header bar is some refactoring that was necessary for the Nextcloud 30 design changes. I've pushed a fix in https://github.com/nextcloud/collectives/pull/1430.
