### ISSUE TITLE
Search footer shows all the time

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/collectives#1428]
**Describe the bug**

![image](https://github.com/user-attachments/assets/d822a438-58ec-42cb-b967-47f998442941)

**To Reproduce**
1. Open an existing collectives page

**Expected behavior**

No search bar

**Screenshots**

See above

**Server details:**
- Collectives app version: [e.g. 2.10.1; see Nextcloud apps page]
- Nextcloud version: 30
- PHP Version: [e.g. 8.3]
- Database: [e.g. MariaDB 10.6]

**Client details:**
 - OS: [e.g. Windows/macOS/Ubuntu]
 - Browser: [e.g. Firefox, Chrome]
 - Browser version: [e.g. 112]
 - Device: [e.g. iPhone13, desktop]

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment]
Hey Christoph, thanks for the report. This already got fixed with the latest Collectives 2.14.0 release.
