### ISSUE TITLE
Type error (due to null versus bool) from patch for #1431

### ISSUE THREAD

**Issue by manumitted** [nextcloud/collectives#1435]
**Describe the bug**
I'm not sure if I need to open a new bug, or somehow re-open the other one, but the fix for #1431 appears to be incomplete.

From version 2.14.1, the following log message occurs, and the trash message still exists:

 TypeError OCA\Collectives\Model\PageInfo::fromFile(): Argument #7 ($fullWidth) must be of type bool, null given, called in /var/www/nextcloud/apps/collectives/lib/Service/PageService.php on line 233
Collectives App Error: OCA\Collectives\Model\PageInfo::fromFile(): Argument #7 ($fullWidth) must be of type bool, null given, called in /var/www/nextcloud/apps/collectives/lib/Service/PageService.php on line 233 

I think the patch kicked the can down the road a bit, but not all the way?

(Thanks for the quick support, by the way.  I'm sorry but I don't know PHP very well.  I'm more of a C++ guy.)

**Comment by manumitted** [comment]
OK, I tried adding "== true" to the patched statement, and the error went away.  I think this might be a PHP-ism that works.
```
$page?->getFullWidth() == true
```

**Comment by mejo-** [comment]
Thanks a lot, @manumitted. Indeed when `$page` is null, the former fix is incomplete. I've pushed a follow-up fix to https://github.com/nextcloud/collectives/pull/1439

**Comment by mejo-** [comment]
Fixed by #1439
