### ISSUE TITLE
Unable to remove team created by collective

### ISSUE THREAD

**Issue by andynameistaken** [nextcloud/collectives#1443]
**Describe the bug**
If you remove collective, you can't remove Team that was created by collective
**To Reproduce**
1. Create collective, for example with name tmp
2. Go to settings of collective and remove it via remove button
3. Go to contacts app
4. Remove team `tmp`
5. Error: Unable to delete team {circleId}

**Expected behavior**
Team should be deleted 

**Screenshots**
<img width="384" alt="image" src="https://github.com/user-attachments/assets/e29cc0cc-18bd-4b0f-9721-b7743b071143">

**Server details:**
- Collectives app version: 2.14.2
- Nextcloud version: [e.g. 29.0.1]
- PHP Version: 8.2.21
- Database: PostgreSQL 16.3

**Client details:**
 - OS: macOS Ventura and ArchLinux
 - Browser: Vivaldi 
 - Browser version: 6.8.3381.53 (Stable channel) (x86_64) 
 - Device: desktop

**Comment by mejo-** [comment]
Thanks for your report @andynameistaken. Does "Permanently remove" -> "Collective and team" work for you? When you remove a collective it gets moved to the collective trash first. You have to remove it permanently from there. In the trash, you can select whether you only want to remove the collective, or also the corresponding team. If you do the former, the team should be removable afterwards.

Background is that team that are used for a collective are marked as "app managed" to prevent accidental removals of these teams.

**Comment by mejo-** [comment]
Closing due to lack of further information.

**Comment by mejo-** [comment]
> Hi sorry for not answering, I had to take care for myself a bit in recent time. Where is this "Permanently remove" option?

Hey @andynameistaken, no worries. At the bottom of the collectives list, you should find "Deleted collectives", which opens the collectives trash. There in the three-dot-menu for a collective you can select "Delete permanently".

**Comment by andynameistaken** [comment]
> > Hi sorry for not answering, I had to take care for myself a bit in recent time. Where is this "Permanently remove" option?
> 
> Hey @andynameistaken, no worries. At the bottom of the collectives list, you should find "Deleted collectives", which opens the collectives trash. There in the three-dot-menu for a collective you can select "Delete permanently".

Oh, I see it, it works!

Hmm, maybe then it would be good idea when in Contacts app user want to delete Team of the collective that is in trash that this is the reason of not being able to remove it from here, instead of vague "Unable to delete team {circleID}"
