### ISSUE TITLE
Outside the Collective, users should be anonymized to the collective name.

### ISSUE THREAD

**Issue by Aveyron-RetD** [nextcloud/collectives#1466]
**Is your feature request related to a problem? Please describe.**

Inside the collective, users are individuals and contributions are individuals. But when a document is shared outside the collective, the users should be anonymized to the collective name

I think this kind of behaviour could help with https://github.com/nextcloud/tables/issues/1340

Similar as of #1361 but with a suggestion

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mejo-** [comment]
Thanks @Aveyron-RetD. As you mentioned, this is already tracked in #1361, so let's continue the discussion there :blush:
