### ISSUE TITLE
changes in edit mode don't show after saving

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/collectives#1472]
**To Reproduce**
1. edit a page
2. click save
3. the changes are not shown

also interesting:
5. click edit again
6. the changes are there
7. click save again
8. changes not displayed

page reload also does not help

**Expected behavior**
Changes are shown after clicking save

**Server details:**
this is on c.nc.com so I cant check the app version
NC 30.0.0 RC4

It still works as expected in NC 29.0.6 - Collectives 2.14.2

**Comment by mejo-** [comment]
Thanks @alexanderdd. The problem already got reported in https://github.com/nextcloud/collectives/issues/1437 and fixed in https://github.com/nextcloud/collectives/pull/1450. I'll publish a bugfix release of Collectives soon.
