### ISSUE TITLE
Scrolling text up will hide title and "edit"/"done" button

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/collectives#1483]
**Describe the bug**
When you have a longer page and scroll down the title and the "edit"/"done" button will start moving up and eventually become invisible.

**To Reproduce**
1. Create a new page which is at least twice as high as the current browser viewport.
2. Scroll down the page.
4. See the title bar and "edit"/"done" button disappearing when scrolling down further.

**Expected behavior**
The title bar and "edit"/"done" button stay where they are.

**Screenshots**

Normal view with everything as it should be:

![image](https://github.com/user-attachments/assets/55e55303-ff1f-476d-8424-d1ecabcb314d)

Now scrolling down a bit - still ok:

![image](https://github.com/user-attachments/assets/19ba28cf-8fb8-4546-9106-397309d93192)

Scrolling down further - title bar and "edit"/done" button start moving up:

![image](https://github.com/user-attachments/assets/7d190ed2-3b70-418a-bb3f-1574e2931c25)

Scrolling down further - now the title bar and "edit"/"done" button is gone:

![image](https://github.com/user-attachments/assets/77484604-c0dc-4e05-ad7a-f49f15ef02ec)

**Server details:**
- Collectives app version: 2.14.3
- Nextcloud version: 30.0.0
- PHP Version: 8.3
- Database: MariaDB 10.0

**Client details:**
 - OS: Windows
 - Browser: Vivaldi, Chrome, Firefox
 - Browser version: 6.9.3447.44, 128.0.6613.138, 130.0
 - Device: Desktop

**Comment by mejo-** [comment]
Thanks for your report. This got fixed with 7daae34b52f321113736b53593395b068e7c5455.
