### ISSUE TITLE
Federated sharing

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/collectives#1486]
**Is your feature request related to a problem? Please describe.**
I have got a project with some external users who have got their own nextcloud. I want to share a collective with them.

**Describe the solution you'd like**
I can now invite users, teams and groups to a collective. It would be cool, if I can also invite someone with their fed-ID.

**Describe alternatives you've considered**
I can share the files of the collective with them. I didn't test that, but maybe they would be able to move the shared folder to their collective folder and thus have the files in their collective. But that isn't the smoothest solution.

**Comment by mejo-** [comment]
@kaffeeringe fully agree with the feature request. We already track this in https://github.com/nextcloud/collectives/issues/351 though. Closing as a duplicate therefore.
