### ISSUE TITLE
Internal links don't work anymore in existing collective

### ISSUE THREAD

**Issue by thopanX** [nextcloud/collectives#1490]
**Describe the bug**
I created a collective about 2 years ago with working links to other (sub-)pages. I came back to the collective to look through it in view mode and noticed that internal links didn't work anymore. On click I got a small pop-over in which I can copy the page adress and/or click on it which opens a new browser tab. (Is that the new default for clicking a link in view mode?) The structure of links is https://[domain]/apps/collectives/Organisationen/Readme.md?fileId=21324 – the collective name, DreiDinge, is omitted in internal links after /collectives/, /Organisationen/ is a parent page with subpages.

Links in the left sidebar of the collective are structured like https://[domain]/apps/collectives/DreiDinge/Orte/Borne?fileId=22585 and work fine. If I add internal links via the link button today, the structure of links is https://[domain]/f/21393. If I use the Smart Picker links are correct. I'm pretty confused. How do I get the collective working again?

**To Reproduce**
I don't know how to reproduce this. My Nextcloud instance got updated during the past two years including the Collectives app.

**Expected behavior**
I'd expect internal links in view mode to function properly and take me to the linked collective page.

**Server details:**
- Collectives app version: 2.14.3
- Nextcloud version: 30.0.0
- PHP Version: 8.1
- Database: ?
- 
**Client details:**
 - OS: Fedora Linux and macOS 14.7
 - Browser: Firefox
 - Browser version: 130.0.0
 - Device: desktop

**Comment by mejo-** [comment]
Dear @thopanX, thanks for your report. We indeed refactored the link handling quite a bit in recent releases of Text and Collectives, as there were many issues with the old way it worked.

The biggest change you already discovered: clicking on a link will open a popover now, where you can either edit, copy or open the link. This is the new behaviour and it was added for accessibility reasons.

Regarding adding a link, there's several ways to insert a link to a collective page:
1. Drag & drop from the page sidebar inserts the link to the page in the format `/apps/collectives/<collective>/<page>?fileId=<id>`, which means the page will will open inside Collectives
2. Adding a collectives page with the Smartpicker will result in the same.
3. Adding a link via the "Insert link -> Link to file or folder" menu action will link to the *file* (in Files app), not to the Collective page. This means, the file will be opened in the Viewer (in an overlay modal). We're aware that this is confusing. See the first item of https://github.com/nextcloud/collectives/issues/1026 where it is tracked.

The remaining question would be why your old links broke. Could you please paste the markdown content of the page with broken links, so I can have a closer look?

**Comment by estux** [comment]
Hello, I confirm that internal links are completely broken! @mejo- 
I tried to make them work in every way is possible (and also encountered at least 5 different bugs and UI issues that I will list here as all are related to internal links broken).

1) About the **Popup that appears clicking on a link**
- UI To improve: it doesn't make clear where people should click as it has a preview with the same text of the link on the second line. 
- bug: the link to another Collective page, created with Smart Linker, **only text mode**, when clicked in the popup from the desktop and also mobile view brings you to a login page
- bug: on mobile the button in the popup to copy link text is not visible as it goes too far on the right

2) Link inside a Callout box
- bug: if a put a link with Smart Linker (both Preview or Text-only mode) in the middle of a text inside a callout box, it "breaks" the box in 2 parts, one above the link and one under the link and the link seems outside of the box, in the middle.

3) About Preview and Text-only views
- bug: the link to another Collective page, created with Smart Linker, **preview mode**, is not clickable at all from both desktop and mobile view
- bug: every time I can see the long link (as simple text, not clickable) above the Preview box (this feels like clutter from UI point of view)
- bug: on mobile the preview box is so small that the link inside is not properly shown
- UI To improve: (In my opinion) The Preview view is too big and risks breaking the "visual balance" of the pages in Collectives, especially if links are inserted inline, in the middle of the text.
- Feature/UI To improve: In Text-only view I cannot add a Placeholder for the link (like in classic Markdown syntax) as I can do with the "Insert link" button, so I always have to see long links here and there in the middle of the text.

Nextcloud version: 29.0.8
Collectives version: 2.14.4

**Comment by mejo-** [comment]
Thanks @estux, for your comments. I copied them as a new issue at https://github.com/nextcloud/collectives/issues/1573 as they're not the same as the issue reported by @thopanX.

**Comment by mejo-** [comment]
> bug: the link to another Collective page, created with Smart Linker, only-text mode, when clicked in the popup from the desktop and also mobile view brings you to a login page

Could you test whether the patch in #1572 helps here?

**Comment by estux** [comment]
> > bug: the link to another Collective page, created with Smart Linker, only-text mode, when clicked in the popup from the desktop and also mobile view brings you to a login page
> 
> Could you test whether the patch in [#1572](https://github.com/nextcloud/collectives/pull/1572) helps here?

I would gladly do but I don't have a dev environment ready to test it, I'm sorry!

**Comment by estux** [comment]
> Thanks [@estux](https://github.com/estux), for your comments. I copied them as a new issue at [#1573](https://github.com/nextcloud/collectives/issues/1573) as they're not the same as the issue reported by [@thopanX](https://github.com/thopanX).

thank you so much! I hope it wasn't a problem to list them all together as I didn't know where to put them (one or separate issues)!

**Comment by mejo-** [comment]
> thank you so much! I hope it wasn't a problem to list them all together as I didn't know where to put them (one or separate issues)!

No worries @estux. In general we prefer one Github issue per problem, but I'll work through them step by step and maybe at some point close the meta issue and split out remainers into new issues. As always: thanks for reporting!
