### ISSUE TITLE
Collective activitys - a statistic for administrators

### ISSUE THREAD

**Issue by Gerepos** [nextcloud/collectives#1507]
Dear Nextcloud Team, 
i work in a small Business that uses Nextcloud as a Wiki for internal Processes and a few other gerneral Information.
We were trying to find out whom of the Users use the collektives efficiently but we could not find a way to find out about the Usage of collectives. 
Though we don't want to extract single User Usage from the Logs, we thought of the Idea of some kind of Activity Integration within Collectives.

We would like to review the Usage per Site of our Users.

Thanks for considering!

**Comment by mejo-** [comment]
Dear @Gerepos, thanks for your suggestion. This is already tracked in https://github.com/nextcloud/collectives/issues/1185, so closing this one as duplicate. Feel free to vote on the issue with a thumbs up reaction.
