### ISSUE TITLE
Internal share of Collective pages

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/collectives#1514]
**Is your feature request related to a problem? Please describe.**
Today you are able to share a page by link (public share), but you can't share the same page with Nextcloud users/groups/teams.

**Describe the solution you'd like**
Extend the sharing module with internal shares (like Notes, Deck, Files...)

**Describe alternatives you've considered**
You can share an entire Collective, but then you can't filter precisely who can view/edit what inside it.

**Comment by SprickW** [comment]
I very much support this request, as it would be great to share a collective as a a whole with just read access (FAQ).

An alternative could be to add memebers with just read access.

**Comment by mejo-** [comment]
Thanks for your report @Ornanovitch. Unfortunately we don't have plans to allow internal sharing of a collective via the Nextcloud sharing mechanism. Collectives are already shared automatically with all its members, and you have three member levels (member, moderator, admin) at hand to configure who is able to edit and publically share the collective.

If you need some data to be available to a subgroup only, I'd suggest to create a dedicated collectives for this data.

@SprickW it's already possible to allow editing in a collective to only admins (or admins & moderators). You can do so in the collective settings.

**Comment by Ornanovitch** [comment]
Thanks for those inputs @mejo- !

I understand those statements, but I still feel that something that could be discussed. As I said in my OP, the feature I miss is not to be able to share _a collective_ via the Nextcloud sharing mechanism, but to share specific collective _sub-pages_ via this mechanism. As of today, here is the state of the sharing possibilities within a collective:

| Location              | Internal | Public |
| ------------------ | -------- | ------- |
| Whole collective | ✅ (this is of course the core feature of this app) | ✅ (public link) |
| Sub-pages          | 🛑 impossible       |  ✅ (public link) |

I'm ok if all of this is meant by design, but I feel this kind of choice makes gaps into the app itself but also between apps. For e.g into a group-folder you can share some specific nodes via the Nextcloud sharing mechanism. In table you can share a whole table but you can also share a vue or an app

An alternative would be to be able to create sub-collectives, but this sounds like too much work for a poor UX design.
