### ISSUE TITLE
Bad request when changing collective folder path

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/collectives#1515]
**Describe the bug**
When using the new option which allows to change the Collective folder path, I got the following errors:

From the UI (toast): `Could not update collectives folder: [object Object]`

From the browser logs : 

```log
XHRPOST
https://{masked}/ocs/v2.php/apps/collectives/api/v1.0/settings/user
[HTTP/2 400  202ms]

ocs Object { data: "Invalid collectives folder path", meta: {…} }
```

I can't see anything relevant into the Nextcloud logs

**To Reproduce**
1. Go to the Collectives folder parameter
2. Select a new path (an empty new folder in my case)
3. See error

**Expected behavior**
Collectives folder is successfully updated

**Server details:**
- Collectives app version: [2.14.4](https://github.com/nextcloud/collectives/releases/tag/v2.14.4)
- Nextcloud version: 29.0.7
- PHP Version: 8.2
- Database: MariaDB 10.5

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox
 - Browser version: 130
 - Device: laptop

**Comment by mejo-** [comment]
@Ornanovitch I was unable to reproduce your issue on both Nextcloud 29 and 30. Could it be that you still had an old version of the collectives app loaded while experiencing this bug?

Could you please try to reproduce the bug again after force-reloading the collectives app (<kbd>Ctrl</kbd>-<kbd>F5</kbd> on most browsers)?

**Comment by Ornanovitch** [comment]
Sorry for the lack of update on this issue, I just tried with the latest stable versions of both Nextcloud and Collective and I am not able to reproduce anymore :)

Thanks!
