### ISSUE TITLE
Blank pages on shared collective

### ISSUE THREAD

**Issue by estux** [nextcloud/collectives#1530]
**Describe the bug**
After upgrading to Nextcloud 28.0.11 (with Collectives 2.14.4) I created a new Collective, edited 6 pages and then shared it. I checked the link from a private tab (so without login) and the content of all the pages (landing page included) is not visible!

➡ [HERE's](https://github.com/nextcloud/collectives/issues/1530#issuecomment-2411567416) (below) my workaround to make it temporarily work!

**To Reproduce**
1. Have an updated Nextcloud 28.0.11 server with an updated Collectives app (2.14.4)
2. Create a Collective with some pages and some content in every page.
3. Share the Collective
4. Open the Collective link in a private tab of the browser
5. all the pages are empty

**Expected behavior**
I should see the content in all the pages.

**Screenshots**

**Server details:**
- Collectives app version: 2.14.4
- Nextcloud version: 28.0.11
- PHP Version: 8.2.14
- Database: mysql 10.5.26

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Browser version: 131.0.2
 - Device: laptop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"qYT8Gvv3I18gXmkQgqxa","level":3,"time":"2024-10-14T01:48:13+02:00","remoteAddr":"IP address hidden","user":"--","app":"collectives","method":"GET","url":"/apps/collectives/_api/p/FqnZxY2fcxi4zxH/_pages/227240/backlinks","message":"Collectives App Error: ","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0","version":"28.0.11.1","exception":{"Exception":"OCP\\Files\\GenericFileException","Message":"","Code":0,"Trace":[{"file":"/data/www/nextcloud614/apps/collectives/lib/Fs/NodeHelper.php","line":110,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/data/www/nextcloud614/apps/collectives/lib/Service/PageService.php","line":1079,"function":"getContent","class":"OCA\\Collectives\\Fs\\NodeHelper","type":"::"},{"file":"/data/www/nextcloud614/apps/collectives/lib/Controller/PublicPageController.php","line":308,"function":"getBacklinks","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/data/www/nextcloud614/apps/collectives/lib/Controller/ErrorHelper.php","line":28,"function":"OCA\\Collectives\\Controller\\{closure}","class":"OCA\\Collectives\\Controller\\PublicPageController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/data/www/nextcloud614/apps/collectives/lib/Controller/PublicPageController.php","line":302,"function":"handleErrorResponse","class":"OCA\\Collectives\\Controller\\PublicPageController","type":"->"},{"file":"/data/www/nextcloud614/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getBacklinks","class":"OCA\\Collectives\\Controller\\PublicPageController","type":"->"},{"file":"/data/www/nextcloud614/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/data/www/nextcloud614/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/data/www/nextcloud614/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/data/www/nextcloud614/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/data/www/nextcloud614/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/data/www/nextcloud614/lib/private/Files/Node/File.php","Line":56,"message":"Collectives App Error: ","exception":[],"CustomMessage":"Collectives App Error: "},"id":"670c5fdcced00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

EDITED: this seems to happen also on Nextcloud 29.0.8 (see below).

**Comment by pascald0210** [comment]
Same problem, same versions except PHP 8.1
When I create public link this Error 404 appear on shared page
![Image](https://github.com/user-attachments/assets/aa3e62f3-507c-4dbd-ab40-6beb771a11cd)
![Image](https://github.com/user-attachments/assets/6e647a9a-e83b-4539-bd5a-63b9d9c0ad0a)

**Comment by max-nextcloud** [comment]
Trace from the initial report formatted a bit:

```json
{
  "reqId": "qYT8Gvv3I18gXmkQgqxa",
  "level": 3,
  "time": "2024-10-14T01:48:13+02:00",
  "remoteAddr": "IP address hidden",
  "user": "--",
  "app": "collectives",
  "method": "GET",
  "url": "/apps/collectives/_api/p/FqnZxY2fcxi4zxH/_pages/227240/backlinks",
  "message": "Collectives App Error: ",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0",
  "version": "28.0.11.1",
  "exception": {
    "Exception": "OCP\\Files\\GenericFileException",
    "Message": "",
    "Code": 0,
    "Trace": [
      {
        "file": "/data/www/nextcloud614/apps/collectives/lib/Fs/NodeHelper.php",
        "line": 110,
        "function": "getContent",
        "class": "OC\\Files\\Node\\File",
        "type": "->"
      },
      {
        "file": "/data/www/nextcloud614/apps/collectives/lib/Service/PageService.php",
        "line": 1079,
        "function": "getContent",
        "class": "OCA\\Collectives\\Fs\\NodeHelper",
        "type": "::"
      },
      {
        "file": "/data/www/nextcloud614/apps/collectives/lib/Controller/PublicPageController.php",
        "line": 308,
        "function": "getBacklinks",
        "class": "OCA\\Collectives\\Service\\PageService",
        "type": "->"
      },
      {
        "file": "/data/www/nextcloud614/apps/collectives/lib/Controller/ErrorHelper.php",
        "line": 28,
        "function": "OCA\\Collectives\\Controller\\{closure}",
        "class": "OCA\\Collectives\\Controller\\PublicPageController",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/data/www/nextcloud614/apps/collectives/lib/Controller/PublicPageController.php",
        "line": 302,
        "function": "handleErrorResponse",
        "class": "OCA\\Collectives\\Controller\\PublicPageController",
        "type": "->"
      },
      {
        "file": "/data/www/nextcloud614/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 230,
        "function": "getBacklinks",
        "class": "OCA\\Collectives\\Controller\\PublicPageController",
        "type": "->"
      },
      {
        "file": "/data/www/nextcloud614/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 137,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/data/www/nextcloud614/lib/private/AppFramework/App.php",
        "line": 184,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/data/www/nextcloud614/lib/private/Route/Router.php",
        "line": 315,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/data/www/nextcloud614/lib/base.php",
        "line": 1069,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/data/www/nextcloud614/index.php",
        "line": 39,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/data/www/nextcloud614/lib/private/Files/Node/File.php",
    "Line": 56,
    "message": "Collectives App Error: ",
    "exception": [],
    "CustomMessage": "Collectives App Error: "
  },
  "id": "670c5fdcced00"
}

```

**Comment by estux** [comment]
> Same problem under 29.0.8 here - this is a severe issue for us.![Image](https://github.com/user-attachments/assets/e42cd827-cfcc-4b36-8ccf-0ed71b375552)

same for us, this makes it quite unusable. 
But I trust the devs will find the solution soon.

Thanks @max-nextcloud for formatting my log entry 🙏

**Comment by bentuna** [comment]
> So it could be something related to both the latest updates (for 28.0.x and 29.0.x)

Yes, probably. With 30.0.0 the issue is not existent.

**Comment by estux** [comment]
UPDATE: I think I found the culprit and also a possible workaround (waiting for a proper solution tough).
Disclaimer: I'm only a geek/advanced user but not a full stack dev.

I tried changing some related settings here and there until I found something interesting! 

NOT WORKING (other details about the problem)
I start adding that my Collective had originally this permissions settings:

- editing permission: only Admin and Mods
- sharing permission: only Admin and Mods

I'm the creator of the Collective so Admin of it but generally speaking my user is not a server admin.

--------

WORKING (temporary workaround to make it work and show the pages publicly)
I changed the Collective permissions to:

- editing permission: All
- sharing permission: All

Setting them to All means that all the Collective members can edit and share it.
With this workaround the pages are shown publicly without problems.
Hope this works for you too :)

**Comment by max-nextcloud** [comment]
I tried to reproduce this on cloud.nextcloud.com which runs Nextcloud 30 and failed. Will try 29 (and maybe 28) next.

**Comment by max-nextcloud** [comment]
Also failed to reproduce this on 29.

@bentuna @pascald0210 @estux Could you provide a list of all apps you have installed? Looks like some file read is not working - which might be blocked by another app such as terms of services.
`occ app:list` will create such a list.

Thanks!

**Comment by bentuna** [comment]
> [@bentuna](https://github.com/bentuna) [@pascald0210](https://github.com/pascald0210) [@estux](https://github.com/estux) Could you provide a list of all apps you have installed?

```
Group folders
	17.0.4 	
	
Account retention (formerly User retention)
	1.13.0 		
	
Activity
	2.21.1 	
	
Auditing / Logging
	1.19.0 	
	
Calendar
	4.7.16 	
	
Client Push
	0.7.0 		
	
Collaborative tags
	1.19.0 	
	
Collectives
	2.14.4 	
	
Comments
	1.19.0 	
	
Contacts
	6.0.0 	
	
Custom CSS
	1.17.0 		
	
Deck
	1.13.2 	
	
Deleted files
	1.19.0 	
	
Federation
	1.19.0 	
	
File reminders
	1.2.0 	
	
File sharing
	1.21.0 	
	
Files download limit
	2.0.0 	
	
Forms
	4.3.1 	
	
Full text search
	29.0.1 		
	
Full text search - Elasticsearch Platform
	29.0.1 		
	
Full text search - Files
	29.0.1 		
	
Impersonate
	1.16.0 		
	
Log Reader
	2.14.0 	
	
Monitoring
	1.19.0 	
	
Nextcloud Office
	8.4.7 	
	
Notes
	4.11.0 	
	
Notifications
	2.17.0 	
	
Password policy
	1.19.0 	
	
PDF viewer
	2.10.0 	
	
Polls
	7.2.4 		
	
Privacy
	1.13.0 	
	
Recommendations
	2.1.0 	
	
Registration
	2.5.0 		
	
Related Resources
	1.4.0 	
	
Share by mail
	1.19.0 	
	
Sketch picker
	1.0.2 		
	
Tables
	0.8.1 	
	
Talk
	19.0.10 	
	
Teams
	29.0.0-dev 	
	
Text
	3.10.1 	
	
Two-Factor TOTP Provider
	11.0.0-dev 	
	
Update notification
	1.19.1 	
	
User status
	1.9.0 	
	
Versions
	1.22.0 	
	
Whisper Speech-To-Text
	1.0.8 		
```

**Comment by pascald0210** [comment]
Nextcloud 28.0.11
PHP 8.1.30
Mysql 8.0.39

Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - announcementcenter: 7.0.1
  - bruteforcesettings: 2.8.0
  - calendar: 4.7.16
  - cfg_share_links: 5.1.3
  - circles: 28.0.0
  - cloud_federation_api: 1.11.0
  - collectives: 2.14.4
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.2
  - deck: 1.12.5
  - end_to_end_encryption: 1.14.5
  - event_update_notification: 2.4.0
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.1
  - files_antivirus: 5.6.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_retention: 1.17.2
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - forms: 4.3.1
  - geoblocker: 0.5.15
  - groupfolders: 16.0.11
  - guests: 3.0.1
  - keeweb: 0.6.20
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.7.9
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.4
  - onlyoffice: 9.4.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 7.2.4
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.20.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.12
  - support: 1.11.1
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tasks: 0.16.1
  - text: 3.9.2
  - theming: 2.3.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_retention: 1.13.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.17.0)
  - files_external: 1.20.0
  - files_mindmap: 0.0.30 (installed 0.0.30)
  - files_rightclick: 0.15.1 (installed 0.15.1)
  - user_ldap: 1.19.0 (installed 1.11.0)
  - weather_status: 1.8.0 (installed 1.0.0)

**Comment by estux** [comment]
Here's my list of apps:

Enabled:
 - activity: 2.20.0
 - bookmarks: 14.2.6
 - bruteforcesettings: 2.8.0
 - calendar: 4.7.16
 - camerarawpreviews: 0.8.5
 - circles: 28.0.0
 - cloud_federation_api: 1.11.0
 - collectives: 2.14.4
 - comments: 1.18.0
 - contacts: 5.5.3
 - contactsinteraction: 1.9.0
 - cospend: 1.6.1
 - dashboard: 7.8.0
 - dav: 1.29.2
 - deck: 1.12.5
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - firstrunwizard: 2.17.0
 - forms: 4.3.1
 - groupfolders: 16.0.10
 - guests: 3.0.1
 - impersonate: 1.15.0
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - maps: 1.4.0
 - nextcloud_announcements: 1.17.0
 - notes: 4.11.0
 - notifications: 2.16.0
 - oauth2: 1.16.4
 - password_policy: 1.18.0
 - photos: 2.4.0
 - polls: 7.2.4
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - richdocuments: 8.3.11
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - spreed: 18.0.12
 - support: 1.11.1
 - survey_client: 1.16.0
 - suspicious_login: 6.0.0
 - systemtags: 1.18.0
 - tables: 0.8.1
 - tasks: 0.16.1
 - text: 3.9.2
 - theming: 2.3.0
 - twofactor_backupcodes: 1.17.0
 - updatenotification: 1.18.0
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - welcome: 1.2.0
 - workflowengine: 2.10.0
Disabled:
 - admin_audit: 1.10.0
 - encryption
 - files_external
 - files_rightclick: 1.6.0
 - talk_matterbridge: 1.26.0
 - twofactor_totp
 - unsplash: 3.0.1
 - user_ldap

**Comment by pascald0210** [comment]
Upgrade to 29.0.8 : bug is still present

**Comment by codito** [comment]
This happens on 30.0.1 for me. I can confirm that the XHR request to fetch the `md` file is successful, don't see any errors in browser console.

**Comment by mejo-** [comment]
Thanks all for reporting and the detailed analysis. I'm able to reproduce the issue and will look into a fix shortly.

**Comment by pascald0210** [comment]
It seems working ! 👍

**Comment by osm-frasch** [comment]
Here the same. 
Had created a page with many links. This ran perfectly for 2 months under NC 28. After upgrading to **29.0.9 Enterprise**, only the entry text is displayed. The rest is blank. When I click on edit, the page loads indefinitely. Editing is no longer possible


System Protocol: {"reqId":"XXXXXXXXXXXXX","level":2,"time":"2024-11-18T09:20:38+00:00","remoteAddr":"XXX.XX.XXX","user":"MaxMuster","app":"no app in context","method":"GET","url":"/ocs/v2.php/references/resolve?reference=https%3A%2F%2Fopendesk.eu%2F","message":"Could not detect host of open graph image URI for https://opendesk.eu/","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0","version":"29.0.9.3","data":[],"id":"673b0e51384ec"}


**I get many of this errors**
Firefox Konsole Log
[ERROR] text: Failed to push the queue with 1 steps to the server 
Object { app: "text", uid: "MaxMuster", level: 2 }
[ConsoleLogger.js:74:18](webpack:///text/node_modules/@nextcloud/logger/dist/ConsoleLogger.js)
    value ConsoleLogger.js:74
    value ConsoleLogger.js:100
    a WebSocketPolyfill.js:113


**and few errors of this**
TypeError: URL constructor: https://Nextcloud%20im%20Bildungswesen is not a valid URL.
