### ISSUE TITLE
Public Link doesn't work

### ISSUE THREAD

**Issue by thomaskor** [nextcloud/collectives#1559]
**Describe the bug**
I am working on Nextcloud 30.0.1. Recently the shared link stopped working. When using collectives with a public link, the error message appears. For a test page: "Could not fetch pages: No create permission for path “Readme.md”

**To Reproduce**
1. Go to 'https://nextcloud.kortuem-edv.de/index.php/apps/collectives/p/LGNMKGZqd77yZTy/Kortüm%20EDV-Beratung' you see the pages without content 

**Expected behavior**
The content of all pages is missing.

**Screenshots**
![Image](https://github.com/user-attachments/assets/29a438b9-2d4d-44f9-a241-d61e6b8ceba4)

**Server details:**
- Collectives app version: 2.14.4
- Nextcloud version: 30.0.1
- PHP Version:  8.2.24
- Database: Postgresql PostgreSQL 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)

**Client details:**
 - OS: Ubuntu 22.04
 - Browser: Firefox, Chrome, Opera
 - Browser version: current versions
 - Device: Android 14, Linux
<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by estux** [comment]
This is already tracked (and resolved) here: https://github.com/nextcloud/collectives/issues/1530
The fix is in the next release (to be announced).
