### ISSUE TITLE
add activity tab to sidebar (to see who edited the page and when)

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/collectives#1576]
**Is your feature request related to a problem? Please describe.**
I cannot see who has edited the page and when. (Only versions, in version tab)

**Describe the solution you'd like**
add the activity tab (which is already shown for the correspoding .md file in the Files view)

**Describe alternatives you've considered**
- currently, you can click "..." > open page in Files and open the activity tab there. But very hidden.
- alternatively, we could consolidate "versions" and "activity" into one view (should be done in Files as well then)

**Comment by mejo-** [comment]
Thanks @alexanderdd, this is already tracked in #1185

**Comment by alexanderdd** [comment]
@mejo- IMO this is different: I am talking about a (right) sidebar tab for activity for every collectives page, [this](https://github.com/nextcloud/collectives/issues/1185) is talking about a new left sidebar entry for the Activity App.

**Comment by mejo-** [comment]
@alexanderdd well, both would be covered by implementing activity app support into collectives. I updated the title and description of the other issue accordingly.
