### ISSUE TITLE
UX issue: Recent Pages section covering all the landing page on mobile

### ISSUE THREAD

**Issue by estux** [nextcloud/collectives#1578]
**Describe the bug**
On mobile the Recent Pages section covers the whole landing page making it near to impossible to read the landing page content. The problem is also that it's not intuitive enough to find out you should close the Recent page section to read the content. So every time I share a Collective link with someone new I should explain "please close the Recent Pages section with the arrow on the landing page if you want to see the content".

**To Reproduce**
1. On mobile open a Collective link with your browser, heading to the landing page
2. You can see only Recent Pages section and cannot understand there's some text to read below in the landing page.
3. People ask me why they cannot access the content/text on the landing page
4. I have to explain them to close the Recent Pages section with the arrow to access to content

**Expected behavior**
On mobile I should have be able to understand there's some text to read on the landing page, apart from the Recent Pages section. I should not remember to tell the people in advance to close that section (Recent Pages).

**Screenshots**

**Server details:**
- Collectives app version: from 2.14 to the newer releases
- Nextcloud version: 29.0.8
- PHP Version: 8.2.14
- Database: mysql 10.5.26

**Client details:**
 - OS: Android 13
 - Browser: Fennec (Firefox mobile)
 - Browser version: 132.0
 - Device: Samsung S20FE

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the RecentPagesWidget component to improve the mobile layout. The widget now collapses by default on mobile devices and shows a preview of the content below it.

I also created pull request: https://github.com/nextcloud/collectives/pull/1580


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
