### ISSUE TITLE
Export / Import Collectives

### ISSUE THREAD

**Issue by frake65** [nextcloud/collectives#1582]
When you have an already existing Nextcloud and wish to migrate to another one, I could not find any way to migrate the collective from the old one to the new one. If I transfer the files from the directory "collectives" that does not help. 

I would like to have a chance to either have a full re-index out of the files in the directory configured as collectives home or a native import/export functionality working with downloadable / uploadable files.

I am not sure about any extra information that is held within the database but not in the files residing in the file system for the collectives.

**Comment by mejo-** [comment]
Thanks for your report @frake65. Indeed a proper solution to transfer a collective to a new instance is missing so far.

This issue is already tracked in #375 though, and I just updated the description of the issue with a possible workaround.
