### ISSUE TITLE
Not valid URL inside a page preventing the page itself to load and preventing editing it

### ISSUE THREAD

**Issue by estux** [nextcloud/collectives#1605]
**Describe the bug**
A specific URL (not valid) apparently is preventing one page to load in Collectives (you can only see the first text line), showing a neverending circle loading when pressing Edit (the page). I cannot share the URL here but I'm available to help debug this thing. 
I found the reason only this specific page wasn't loading opening the browser console and searching for errors there.

EDIT: the page cannot be opened and edited with the Text app too.

**To Reproduce**
1. Open a specific page in the Collectives that contains a specific URL (the error in the console is saying it's not a valid URL)
2. the link has this problem: website.something--HelloSomething-some_random_ID (no / between the domain and the sub-page)
3. the page cannot load (you can see only the first line of text of a long page)
4. if you press Edit you can see a neverending loading circle

**Expected behavior**
The page should load and show there's a not valid URL.

**Screenshots**

**Server details:**
- Collectives app version: 2.15.1
- Nextcloud version: 29.0.8
- PHP Version: 8.2.14
- Database: mysql 10.5.26

**Client details:**
 - OS: Windows 10
 - Browser: Firefox
 - Browser version: 133.0
 - Device: laptop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
No traces left in the normal log.
```

#### Browser log
```
TypeError: URL constructor: "the not valid url here" is not a valid URL.
    renderHTML Link.js:63
    toDOM index.js:506
    create index.js:1197
    syncToMarks index.js:1781
    updateChildren index.js:1345
    updateChildren index.js:2014
    updateChildren index.js:1335
    addNode index.js:1900
    updateChildren index.js:1356
    updateChildren index.js:2014
    updateChildren index.js:1335
    updateInner index.js:1431
    update index.js:1423
    updateStateInner index.js:5296
    updateState index.js:5247
    dispatchTransaction index.js:3935
    dispatch index.js:5602
    52781/get commands/</< index.js:61
    updateContent MarkdownContentEditor.vue:167
    content MarkdownContentEditor.vue:109
    VueJS 5
vue.runtime.esm.js:3065:16
    VueJS 8
```

and also

```
Uncaught (in promise) TypeError: URL constructor: "the not valid URL here" is not a valid URL.
    renderHTML Link.js:63
    toDOM index.js:506
    create index.js:1197
    syncToMarks index.js:1781
    updateChildren index.js:1345
    updateChildren index.js:2014
    updateChildren index.js:1335
    addNode index.js:1900
    updateChildren index.js:1356
    updateChildren index.js:2014
    updateChildren index.js:1335
    updateInner index.js:1431
    update index.js:1423
    updateStateInner index.js:5296
    updateState index.js:5247
    dispatchTransaction index.js:3935
    dispatch index.js:5602
    _forceRerender sync-plugin.js:414
    mux mutex.js:35
    _forceRerender sync-plugin.js:393
    view sync-plugin.js:178
    updatePluginViews index.js:5365
    updateStateInner index.js:5319
    updateState index.js:5247
    createView index.js:3884
    ct index.js:3710
    X EditorFactory.js:74
    onLoaded Editor.vue:524
Link.js:63:14
```

and

```
[ERROR] text: Failed to push the queue with 1 steps to the server 
Object { app: "text", uid: "(username here)", level: 0 }
ConsoleLogger.js:74:18
    value ConsoleLogger.js:74
    value ConsoleLogger.js:100
    a WebSocketPolyfill.js:113

```

</details>

**Comment by mejo-** [comment]
Thanks for reporting this @estux. It should be fixed with https://github.com/nextcloud/text/pull/6794, which will get released along with the upcoming Nextcloud server point releases.
