### ISSUE TITLE
429: Too Many Requests

### ISSUE THREAD

**Issue by BugProg** [nextcloud/collectives#1607]
**Describe the bug**
Collective doesn't load all the images from links preview. Instead, get status code: 429 Too many requests.
I give you a Nextcloud URL for example: https://www.home-cloud.fr/apps/collectives/p/Br6CwGz7ZNXRfFG/TestImage

I get this kind of error only with collective or Nextcloud text app, not with memories or other apps that load many images.

**To Reproduce**
1. Go to `Collective` app
2. Create a new `Collective`
3. Add a lot of link with the image preview
4. Reload the page (delete the cache before) or share the public link and load it in a new tab

**Expected behavior**
To have all the link image preview.

**Screenshots**
![Image](https://github.com/user-attachments/assets/3a1d6657-69fb-4e22-99c8-18579067de04)

**Server details:**
- Collectives app version: 2.15.1
- Nextcloud version: 30.0.2
- PHP Version: 8.2
- Database: MariaDB

**Client details:**
 - OS: Linux
 - Browser: Firefox and Chrome
 - Device: Phone and desktop

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
{
    "message": "Request failed with status code 429",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 429\n    at ze (https://www.home-cloud.fr/apps/text/js/index-Br6XaFoY.chunk.mjs:2:46617)\n    at XMLHttpRequest.C (https://www.home-cloud.fr/apps/text/js/index-Br6XaFoY.chunk.mjs:2:51615)\n    at Z.request (https://www.home-cloud.fr/apps/text/js/index-Br6XaFoY.chunk.mjs:2:59323)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http",
            "fetch"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "requesttoken": "oilAEGyj6oAJwPhim+5LmEwHljPZe8LP4u09Kbz6F20=:8X8Ndgf2r9lrgaojy41z1wBd8kOXT/KW24NObtfNLwc=",
            "X-Requested-With": "XMLHttpRequest"
        },
        "method": "get",
        "url": "https://www.home-cloud.fr/ocs/v2.php/references/resolvePublic?reference=https%3A%2F%2Fwww.imdb.com%2Ftitle%2Ftt0116209%2F%3Fref_%3Dnv_sr_srsg_0_tt_1_nm_0_in_0_q_Le%252520patient%252520anglais&sharingToken=Br6CwGz7ZNXRfFG"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 429
}

</details>

**Comment by mejo-** [comment]
Thanks for the report @BugProg. Indeed the rate limit is a bit to strict for the public reference endpoint.
