### ISSUE TITLE
Find a clean way to reuse code from text app

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#18]
In GitLab by @azul on May 18, 2020, 15:59

* find a cleaner solution than importing the CSS from text app with relative links `(@import './../../apps/text/css/prosemirror';)`
* avoid copying all the css
* allow for defining our own Component that uses `EditorWrapper`.
* maybe use https://github.com/juliushaertl/nextcloud-text

Missing from !17

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/text/pull/3615 would be the upstream pull request for exposing text through an API

**Comment by mejo-** [comment]
Some stuff to cleanup when removing the current legacy Text integration (after migrating to the new editor API):

* Listeners for `collectives:text-image-node:*` can be removed, they're replaced by `text:image-node.*` events.
