### ISSUE TITLE
Add proper sidebar with comments, activity and versions (as in Files)

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#218]
In GitLab by @ya-d on Aug 4, 2021, 24:12

As Collectives operates on the same files it would be great to have the sidebar components of Files available. I don't know if it is technically possible to reuse the same components.

- Users want to discuss and comment changes before they apply changes to the document. → tab-comments
- Users want to see at a glance wich changes have been made to the page. → tab-activity
- Users want to revert changes. → tab-versions (already implemented in Collectives)
- (Talk and Share might not be necessary and maybe even confusing.)

Also the icon should be different from the left hand sidebar. NC typically uses an people/share indicator for right hand sidebars.

Thanks for considering and keep up the great work :-)

![image](https://gitlab.com/collectivecloud/collectives/uploads/13c3af0a304876df40f9d6c63f6ccecb/image.png)

**Comment by patricksebastien** [comment]
+1 for Comments! Would be super useful.

**Comment by max-nextcloud** [comment]
This ticket is kind of hard to process as it mixes different subjects:
* In terms of **comments** we'll aim for inline comments rather than per page comments.
* We're open to adding an **activity** tab and will create a ticket for it once we design the tab.
* Versions we already have.
