### ISSUE TITLE
FR: Collectives API

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#228]
In GitLab by @J.Soko on Aug 20, 2021, 14:11

Analog to the Deck-Api https://deck.readthedocs.io/en/latest/API/,
it would be fine to have a Collective API to get and write things witch are not accessible with the webdav api.

**Comment by arkhi** [comment]
> Do you have a concrete usecase in mind? Other software that wants to use our API might be a good motivation to stabilize and document our API 😁

I’m looking into Nextcloud APIs to manage the content of a website.

Based on eleventy, pulling the content of documents from a collective through an API would allow members to create and update content from Nextcloud without having to learn this or that CMS.

Just some wild ideas, but eleventy is a nice way to mashup different sources and Nextcloud Collectives could be one of them.

**Comment by arkhi** [comment]
> > Just some wild ideas, but eleventy is a nice way to mashup different sources and Nextcloud Collectives could be one of them.
> 
> Just to be sure... @arkhi you're referring to https://www.11ty.dev/ , right? Had not heard of it before. Can you point me to an api integration?

I am!

Would the following links answer your question?

* https://www.11ty.dev/docs/cms/
* https://docs.strapi.io/dev-docs/integrations/11ty
* https://www.webstoemp.com/blog/headless-cms-graphql-api-eleventy/

**Comment by max-nextcloud** [comment]
#690 is about having an easier to use api and superseeds this issue.
