### ISSUE TITLE
Width of the Collectives app (white space between page content and page list)

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#242]
On large screens, there's a lot of unusued white space between page content and page list.

We got the feedback a few times that this looks "wrong" and ugly.

**Comment by KaeTuuN** [comment]
Today, on a modern PC o Laptop with at least a 16:9 screen, this App is rather useless as a Wiki. Looking at a table that is larger than 2x2 is just a pain in the ***.

My suggestions are:
1. Increase the standard width at least by 25%!
2. Implement a Button to switch between "Full Width" an "Standard width" (like @theron29 wrote)
3. Think about a dynamic width based on the available Space (maybe width a min and max value)
All of these points could be developed and implemented separatly but I think this will increase the usability of Collectives a lot!

Greetings,
Kae
