### ISSUE TITLE
Case sensitive search in RU

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#246]
In GitLab by @temcher on Sep 19, 2021, 08:06

Сase sensitive search in NC by collectives in use RU lang.

**Comment by juliushaertl** [comment]
This might be something where configuring Nextcloud for the right database collation can be used to solve this:

https://dev.mysql.com/doc/refman/8.0/en/case-sensitivity.html
https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1883-L1899

**Comment by mejo-** [comment]
Will close this for now. If anybody runs into this issue in future, it'd be great if they could try the hints from Julius above.
