### ISSUE TITLE
Feature: Add support for mermaid diagrams

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#284]
In GitLab by @georgeivanovich on Feb 3, 2022, 08:54

Could you please add https://mermaid-js.github.io/mermaid/#/
This is good and easy way to make diagrams and it will be great to have it

**Comment by mejo-** [comment]
This is tracked upstream in Nextcloud Text: https://github.com/nextcloud/text/issues/163

**Comment by juliushaertl** [comment]
Initial draft is in https://github.com/nextcloud/text/pull/4614
