### ISSUE TITLE
Nextcloud Encryption for Collectives

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#285]
In GitLab by @jboehme on Feb 7, 2022, 13:17

Unfortunately the files on the hard drive are not encrypted, although this is set as the default in the nextcloud settings. Is there a way to enable this for the Collectives Data?

**Comment by mejo-** [comment]
Groupfolders implemented server-side encryption with this PR: https://github.com/nextcloud/groupfolders/pull/2057

Note from Vincent: test moving around files from encrypted Collectives storage to other storage (local encrypted and local not encrypted). There were bugs in groupfolders first due to shortcuts in server storage implementations. Better not to hit them with Collectives.

**Comment by PVince81** [comment]
looks good.
please note that the cross-storage issues are not fully resolved yet: https://github.com/nextcloud/server/pull/35894 https://github.com/nextcloud/server/pull/35961

the but in question might even already happen when moving encrypted files from outside a collectives folder into it where unencrypted
