### ISSUE TITLE
Favourite pages

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#300]
We should allow to pin a limited amount of pages (3 or 4) as favourites that are always listed on top of all other pages.

**Comment by matthiastaeschner** [comment]
Dear contributors. Is there a possibility to deactivate the display of recent pages and collective members? It's a nice feature for sure, but forcing it without any visible way for deactivation is not a very good approach.

**Comment by punkyard** [comment]
hi
how do we get rid of the automatically pinned pages?
this function appeared suddenly and we can't find how to get rid of it, especially on public pages
and the term "landing page"
we can't find any topic about this on the nc forum
thanks

**Comment by max-nextcloud** [comment]
The recent pages were introduced as part of #311 and then discussed in #835.

They are not related to favorite pages thus far.

**Comment by punkyard** [comment]
thanks @max-nextcloud 
so we'll have to wait to get rid of it?

**Comment by viktorix** [comment]
We use Collectives a lot, and it would be nice to have a favorites feature for quick and easy access to articles I go to often. Here's a quick mockup of what that might look like:

![image](https://github.com/user-attachments/assets/49574c85-8bbc-47e0-841a-9927a8f32e42)

**Comment by punkyard** [comment]
> We use Collectives a lot, and it would be nice to have a favorites feature for quick and easy access to articles I go to often. 

And it would be so nice to move 'team over view', 'landing page' and 'recent pages' to this side of the Collectives  ✌️

**Comment by mejo-** [comment]
For me there's still a few open questions how to approach favourites in Collectives:

* Are favourites personal or shared among the collective? I can see arguments for both: personal favourites help to pin pages that you often use (like pinning in Signal or like classic bookmarks), shared favourites help to pin pages that are important to the whole team (like important threads in discourse).
* Are favourites per collective or global to the collectives app (like the mockup by @viktorix suggested)? 

My current vision would be to pin favourites as first pages inside the collectives page list and somehow highlight them, and maybe limit the amount of allowed favourites (like Signal limits them to four). I don't have a clear preference on whether to make them personal or shared yet.

@nextcloud/designers what's your thoughts here?

**Comment by marcoambrosini** [comment]
My take: 
* Favourites should be personal, collective members can use order to prioritise certain pages
* Favourites should be on a per collective basis. This is consistent with Notion and Anytype. When you enter a team space, you're in, and everything in the UI is pertinent to that. We shouldn't require to open the sidebar to see the favourites. 
* I wouldn't limit the amount. Scroll is always available and users can decide for themselves how many they want (same as files, talk, notion, anytype, ...)

**Comment by nimishavijay** [comment]
I can imagine it being something similar to Notion as a collapsible section on top of the page list which is shown only if you have set at least one favourite page in that collective. We could also think about adding a hairline as a separator to distinguish it from the other "normal" pages. What do you think? :)

![image](https://github.com/user-attachments/assets/72385d65-1b28-4d88-aa55-3bb8aeef46d1)

**Comment by mejo-** [comment]
https://github.com/nextcloud/collectives/commit/b7f8d40e5a9f92b46c0f4d2f7ce4f889dba77e2e implements the backend side.

**Comment by mejo-** [comment]
Here's a screenshot from a first impementation that poses some questions:

* Shall favorites be displayed as expandable if they have subpages, or not? I'd vote for not allowing to expand favorites, and listing them as simple flat pages instead.
* When a favorite is opened, shall both representations of the page (in favorites and in normal page order) be highlighted (like page "Title" in the screenshot)?

Cc @nimishavijay @marcoambrosini 

| Actions of non-favorite page | Actions of favorite page |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/d1ed5fad-986a-408b-a685-751428518e56) | ![image](https://github.com/user-attachments/assets/3dd24bb9-ca31-44ae-9f45-2722e823a22b) |

**Comment by nimishavijay** [comment]
Nice! Looks great! To address your questions:

> Shall favorites be displayed as expandable if they have subpages, or not? I'd vote for not allowing to expand favorites, and listing them as simple flat pages instead.

- The pages themselves can be flattened, but since a person may have many favourites, it would be nice to be able to collapse them to view the other pages easily (similar to Notion) 

- This "Favorites" parent page can be similar to the favourites navigation item in Files (so that it can be distinguished from a regular page)
  - it would have a star Material Symbol instead of a page emoji and a chevron-down symbol on the right, both in `--color-main-text`. Something like this (rough mockup, do you get the idea?)

![Screenshot_20240926_221525_Firefox](https://github.com/user-attachments/assets/f49fac5d-58fd-4608-981a-71245a74e278)

> When a favorite is opened, shall both representations of the page (in favorites and in normal page order) be highlighted (like page "Title" in the screenshot)?

That's a great call! I agree. Nice catch there :) 

Some more small points: 
- In the favourites section the pages don't need to have the little yellow star in the corner as it gets repetitive 
- Instead, the favorited pages can have the star in the normal page list (so the first "Title" wouldn't have a star but the second "Title" would)
- Afaik we are using a darker color for the favourite star for a11y reasons, `--color-warning` if I'm not wrong (ref Files)

Super nice work! :) 🚀

**Comment by juliushaertl** [comment]
One additional suggestion, not sure where to put it but maybe it also makes sense to show favorites at the start page of collectives when you have not navigated to a specific collective?

**Comment by punkyard** [comment]
great idea! to me, it would make sens to see them in the left panel on top of the list of pages and folders - and to make this rubric only visible if a favourite has been chosen - otherwise it would be hidden not to add more distraction to the web page ✌️
