### ISSUE TITLE
Fallback to fileId for files that cannot be found

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#37]
In GitLab by @azul on Jul 11, 2020, 10:06

Links in the same folder and subfolders should always be correct (unless the file was moved)
But absolute links on the same domain and relative links that navigate out of the folder
may differ for different users.
In order to prevent these inconsistencies from breaking links all the time
find the file by fileid and open it in the location it has from the perspective of the user browsing.

**Comment by max-nextcloud** [comment]
Links still have a file id that we could use to resolve the link if it's not working.
