### ISSUE TITLE
Read view scrolls to end when opening a long page

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#392]
In GitLab by @max-nextcloud on Sep 15, 2022, 15:09

When opening a long page in collectives it scrolls to the end of the page.
Better stay on top so the page can be read top to bottom.

**Comment by max-nextcloud** [comment]
Should be fixed now with the merge of said PR. Will reopen if it happens again after the fix has been released in Jan 2023.

**Comment by mejo-** [comment]
I think we will have to release a new version of `@nextcloud/text` and update to it for the issue to be resolved in view mode.

**Comment by max-nextcloud** [comment]
ahh... good point.
