### ISSUE TITLE
Attachments are rendered as broken images in view mode on Nextcloud 25

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#396]
Attachments are not rendered correctly in view mode on Nextcloud 25.

The reason is that we don't pass a session to the attachment resolver in `RichTextReader.vue` and thus attachments are fetched via webdav instead of Text API.

Related upstream issue: https://github.com/nextcloud/text/issues/2919

**Comment by niklas-englert** [comment]
Upstream issue https://github.com/nextcloud/text/issues/2919 was closed five days ago and [Nextcloud 26.0.0](https://github.com/nextcloud/server/releases/tag/v26.0.0) dropped yesterday.  
But I have noticed that this issue still persists.

@mejo-, any news on how things are progressing?

**Comment by mejo-** [comment]
@niklas-englert this finally got solved in Collectives with #611 and will be fixed with the upcoming Collectives release.
