### ISSUE TITLE
Editable shares broken with editing permissions above member

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#398]
Editable shares are not exposed as editable when the minimum permission level to edit is above `LEVEL_MEMBER`. That's because we [force-set `level` to `LEVEL_MEMBER` for shares](https://gitlab.com/collectivecloud/collectives/-/blob/6a953a69579b68004235c269577dd6fd864af0f0/lib/Controller/PublicCollectiveController.php#L94), which [results in `canEdit: false`](https://gitlab.com/collectivecloud/collectives/-/blob/6a953a69579b68004235c269577dd6fd864af0f0/lib/Model/CollectiveInfo.php#L104-106).

**Comment by nomisge** [comment]
I can confirm that, if I set the setting to only allow editing for Admins or Moderators, I actually can't edit at all, unless I am the owner.
If editing is allowed for all members it works.

**Comment by mejo-** [comment]
That's expected behaviour and we even enforce this on file share level nowadays.
