### ISSUE TITLE
Link to subpage of other collective opened in Files app while editing

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#409]
In GitLab by @susnux on Oct 25, 2022, 11:46

First, this is different to https://gitlab.com/collectivecloud/collectives/-/issues/408 as it affects all browser and only happens in the "edit"-mode

---

When in the editing a page an clicking on a link, a new tab is opened, but instead of that other page the file list (root) is opened.
I think this is because the links are relative to collectives but on the files app the files are within the collectives directory.

Tested on NC 24.0.6 with Firefox 104 and Firefox for Android.

**Comment by mejo-** [comment]
@susnux :point_up:

**Comment by susnux** [comment]
Kind of fixed, tested this on NC25:

In edit mode the collective page is opened in the viewer / text app

Is this expected?

**Comment by mejo-** [comment]
Indeed, in edit mode Text opens any links with `fileId=...` in files app straight away due to https://github.com/nextcloud/text/pull/2268.

I opened issue https://github.com/nextcloud/text/issues/3857 to track this upstream.
