### ISSUE TITLE
Edit mode not working in Safarai on MacOS X High Sierra

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#426]
With Safari (on Mac OS X High Sierra 10.13.6), it's impossible to switch to edit mode. When hitting the Edit button, nothing happens and the following javascript error is logged:

```js
[Error] TypeError: undefined is not an object (evaluating 'e.$children[0].$children')
>...Ze (collectives-main.js:2:2630368)
>...Ve (collectives-main.js:2:2630304)
>...Ge (collectives-main.js:2:2629954)
>...We (collectives-main.js:2:2630156)
>...We (collectives-main.js:2:2630021)
>...n (collectives-main.js:2:2631863)
```

**Comment by mejo-** [comment]
We will not further investigate this. Mac OS X High Sierra is just too outdated.

**Comment by juliushaertl** [comment]
I also cannot reporduce on macOS Ventura
