### ISSUE TITLE
Attachments (other than image files) not working

### ISSUE THREAD

**Issue by t0mcat1337** [nextcloud/collectives#472]
**Describe the bug**
Just upgraded to Nextcloud 25 and Collectives 2.1.1 and wanted to try out the new file - attachment functionality in collectives.
NC is running in a Kubernetes Cluster as Nginx/fpm containers. 

When inserting an attachment other than image (pdf for example) in a collectives page everything seem to work, preview is shown in edit mode. But when leaving edit mode collectives in view mode sais "Error loading .attachments....."

**To Reproduce**
In a containerized installation of NC 25 / collectives 2.1.1:
1. Edit a collectives page
2. Insert a new attachment (no matter if uploaded or taken from NC files)
3. Notice the preview image
![image](https://user-images.githubusercontent.com/3826246/209850468-636955a1-c1f2-4973-abac-ab5ac6813b24.png)

4. leave edit mode
5. Notice error
![image](https://user-images.githubusercontent.com/3826246/209850566-86311b06-19a8-4556-ba25-2f452edef373.png)

7. Attachment is unusable (can't be clicked on, nothing happens)

When opening browsers dev-tools while loading the collective page with the attachment on it, I noticed a "403 - Forbidden" error as a response to this request:
![image](https://user-images.githubusercontent.com/3826246/209850707-5fcc2f5e-d584-48f5-8b0a-f941bc741c55.png)

For me it seems as if the URL Params are not filled with the correct values (SessionID a.s.o.)

BTW: Images are working fine:
![image](https://user-images.githubusercontent.com/3826246/209852065-9bb8c630-8080-44e5-b747-8bd17cb312b8.png)

**Expected behavior**
Attachments preview should be shown and attachment should be usable

**Client details:**
 - OS: Ubuntu 22.10
 - Browser: Firefox 108.0.1
 - Device: desktop

<details>
<summary>Server details</summary>

**Collectives app version:** (see Nextcloud apps page)
2.1.1

**Operating system:**
Kubernetes on Debian

**Web server:**
Nginx

**Database:**
MariaDB 10.7

**PHP version:**
8.1.13

**Nextcloud version:** (see Nextcloud admin page)
25.0.2

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
No Logs in nextcloud.log just corresponding NGInx log output:

10.42.15.207 - - [28/Dec/2022:17:40:14 +0000] "GET /apps/text/mediaPreview?documentId=%7BdocumentId%7D&sessionId=%7BsessionId%7D&sessionToken=%7BsessionToken%7D&mediaFileName=TEST.pdf HTTP/1.1" 403 2 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0" "192.168.42.130"

</details>

**Comment by mejo-** [comment]
Thanks for the feedback @t0mcat1337! This issue is already tracked in #396.
