### ISSUE TITLE
User Migration

### ISSUE THREAD

**Issue by ghost** [nextcloud/collectives#479]
**Is your feature request related to a problem? Please describe.**
When changing instances, collectives are not migrated and must be entered again.

**Describe the solution you'd like**
Support Migration with the user Migration App

**Describe alternatives you've considered**
-

**Additional context**
![export.png](https://user-images.githubusercontent.com/90777102/210185958-325bab17-b65b-43bf-9e6e-573ff122dbbf.png)

**Comment by juliushaertl** [comment]
Collectives probably doesn't fit very well into the user migration since the ownership is bound to a circle so it is not really owned by the user. Might be interesting how the files migration is handling the transfer of such items like groupfolders.

**Comment by max-nextcloud** [comment]
#375 covers the collective scenario better. Once we have that we can discuss if an integration with user migrations app would be helpful.
