### ISSUE TITLE
Allow to copy pages to another Collective

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#488]
**Is your feature request related to a problem? Please describe.**

The "move page" modal should allow to copy the page into another collective.

From design review call:
* Additionally would allow copying pages to another collective ("My collectives" -> "List of Collectives" in breadcrumbs?)

Follow-up from #478

**Comment by 42ske** [comment]
also moving to another collective would be nice (e.g. if you use one collective to develop a first version of pages in an inner circle an then move them in another one for more users).

**Comment by xplosionmind** [comment]
According to [this video](https://youtu.be/2WnHnWVhEgU), this issue has been resolved

**Comment by mejo-** [comment]
@xplosionmind unfortunately the video was wrong. It's not possible yet to move pages to another collective in the Collectives app.
