### ISSUE TITLE
An error occurred while searching for Collectives - Page Content  

### ISSUE THREAD

**Issue by kevinkuan1969** [nextcloud/collectives#492]
Describe the bug
The error message is always appeared when the keyword is entered in Unified Search. 
Anyway, the system can return the right result as expected.

To Reproduce
1. Go to Unfired Search and enter the keyword
2. The error message appears as well as return the right result 

Expected behavior
The error message should not be displayed every time the keyword is entered.

**Screenshots**
![image](https://user-images.githubusercontent.com/80019930/211157988-7030c769-0c5a-4952-8dae-b9311350ac22.png)

Client details:
•	OS - MS Windows 11
•	Browser - MS Edge
•	Version 108.0.1462.54 (Official build) (64-bit)
•	Device: Desktop

Server details
Operating system: Ubuntu 20.14
Web server:
Database: MySQL 8.0.31
PHP version: 8.1.13
Nextcloud version: 25.0.2

Collectives app version: 2.2.0

Log

<html>
<body>

Error | no app in context | Exception: Class "TeamTNT\TNTSearch\TNTSearch" not found in file '/var/www/nextcloud/apps/collectives/lib/Search/FileSearch/FileSearcher.php' line 14/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main()/var/www/nextcloud/ocs/v1.php - line 63:OC\Route\Router->match()/var/www/nextcloud/ocs/v2.php - line 23:require_once("/var/www/nextcloud/ocs/v1.php")Caused by Error: Class "TeamTNT\TNTSearch\TNTSearch" not found/var/www/nextcloud/lib/composer/composer/ClassLoader.php - line 571:include()/var/www/nextcloud/lib/composer/composer/ClassLoader.php - line 428:Composer\Autoload\includeFile()/var/www/nextcloud/apps/collectives/lib/Service/SearchService.php - line 70:Composer\Autoload\ClassLoader->loadClass()/var/www/nextcloud/apps/collectives/lib/Search/PageContentProvider.php - line 109:OCA\Collectives\Service\SearchService->searchCollective()/var/www/nextcloud/lib/private/Search/SearchComposer.php - line 160:OCA\Collectives\Search\PageContentProvider->search()/var/www/nextcloud/core/Controller/UnifiedSearchController.php - line 105:OC\Search\SearchComposer->search()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:OC\Core\Controller\UnifiedSearchController->search()/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:OC\AppFramework\Http\Dispatcher->executeController()/var/www/nextcloud/lib/private/AppFramework/App.php - line 172:OC\AppFramework\Http\Dispatcher->dispatch()/var/www/nextcloud/lib/private/Route/Router.php - line 298:OC\AppFramework\App::main()/var/www/nextcloud/ocs/v1.php - line 63:OC\Route\Router->match()/var/www/nextcloud/ocs/v2.php - line 23:require_once("/var/www/nextcloud/ocs/v1.php")
-- | -- | --

</body>
</html>

**Comment by mejo-** [comment]
Thank for your report @kevinkuan1969. Indeed full-text search is broken in Collectives 2.2.0 due to a bug in the release building script. I will release 2.2.1 with a fix shortly.

**Comment by kevinkuan1969** [comment]
Thank you.
