### ISSUE TITLE
It should be possible to share collectives with passwords enforced

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/collectives#505]
**Is your feature request related to a problem? Please describe.**
Currently, one can not share a collective when passwords are enforced for ecternal shares (via linl)

**Describe the solution you'd like**
Share collectives via a link, with password protection enabled, as discussed here:
https://help.nextcloud.com/t/why-can-collectives-not-be-shared-via-a-link-with-a-password

**Describe alternatives you've considered**
Share via a Circle with external contacts does not seem to work either.

**Additional context**
![grafik](https://user-images.githubusercontent.com/8102905/212719221-42fed6e3-590f-4274-a677-ebd085f8f86d.png)

**Comment by Gymnae** [comment]
+1 for this request

**Comment by max-nextcloud** [comment]
We need to figure out how to expose this in the user interface.
