### ISSUE TITLE
Add support for public shares of pages

### ISSUE THREAD

**Issue by 42ske** [nextcloud/collectives#515]
**Is your feature request related to a problem? Please describe.**
If you use collectives as cooperative knowledge base of your group/organization it’s a matter of time when the first member wants to share contents with non-members. This is easily possible at the level of collectives. For pages you can manage this a bit complicated via the files-app. 

**Describe the solution you'd like**
I want to be able to:
1. create a public link for pages according to the function of public links for entire collectives.
2. There should be an option if this link should also include all supages of a page or not.
3. The already existing sharing setting in the collectives’ settings should have an effect on the page links of course.

**Describe alternatives you've considered**
A detour is to share page via the files app, which is not very intuitive.

**Additional context**

**Comment by max-nextcloud** [comment]
Is there really a need for being able to share a page without its subpages?
I think it would be fine to only have a way to share both together. One could still fallback to sharing the single page file via files.

> The already existing sharing setting in the collectives’ settings should have an effect on the page links of course.
The only option i can think of right now is read-only vs. editable shares. I think they should be independent so i can share the entire collective as read only and a page with its subpages as editable - or the other way around. These links may go to different audiences anyway.

**Comment by 42ske** [comment]
> Is there really a need for being able to share a page without its subpages? I think it would be fine to only have a way to share both together. One could still fallback to sharing the single page file via files.

Being able to share a page with its subpages would be a very useful feature of course. There would be lot of scenarios where this would be enough. But I can imagine, there are also other scenarios in which a seperate possibility would be great. 

And yes you are right that you can use the files app for that, but I know for lot of users this ist not very intuitive (I handle it this way).

> > 3. The already existing sharing setting in the collectives’ settings should have an effect on the page links of course.
> 
> The only option i can think of right now is read-only vs. editable shares. I think they should be independent so i can share the entire collective as read only and a page with its subpages as editable - or the other way around. These links may go to different audiences anyway.

Yes, you are absolutely correct with this.

**Comment by hansimausisteffiwurstbrot** [comment]
to whom it may concern: If we can support this feature with some financial means let us know. :)

**Comment by max-nextcloud** [comment]
Ideas for implementation:
* provide a share tab in the page sidebar for sharing that particular page and its subpages.
* extend the `collectives_shares` database.
