### ISSUE TITLE
Collectives full text search not working 

### ISSUE THREAD

**Issue by Adures** [nextcloud/collectives#536]
**Describe the bug**
When trying to use search, it does not find text from files in Collectives app. 

**To Reproduce**
1. Go to 'search'
2. Try searching something
3. This is what is being returned

![image](https://user-images.githubusercontent.com/67986926/216770498-627b1791-aae7-4f27-ba30-6594ae1bafa7.png)

5. Error in logs:
Collectives full-text search is not operational, because the PDO SQLite driver is not available.

**Expected behavior**
I should see the file with word raptor in it

**Screenshots**
Provided in "steps to reproduce

**Client details:**
 - OS: Windows 10 22H2
 - Browser: Firefox 
 - Version: 109.0.1
 - Device: Desktop

<details>
<summary>Server details</summary>

**Collectives app version:** (see Nextcloud apps page)
2.2.1
**Operating system:**
Ubuntu 22.04
**Web server:**
Apache 2.4.52
**Database:**
MariaDB 10.6.11
**PHP version:**
8.1.2
**Nextcloud version:** 25.0.3

pdo_sqlite extension is enabled in php.ini

![image](https://user-images.githubusercontent.com/67986926/216771173-157de625-bfe3-4360-b3cb-206a054706ab.png)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
[collectives] Warning: Collectives full-text search is not operational, because the PDO SQLite driver is not available.

GET /ocs/v2.php/search/providers/collectives-page-content/search?term=raptor&from=%2Fapps%2Fcollectives%2Ftest%25203%2Flupa%3FfileId%3D7755
from xxx by Adrian at xxx

</details>

**Comment by juliushaertl** [comment]
This is expected. Please see https://github.com/nextcloud/collectives#requirements for the requirements.

**Comment by Adures** [comment]
Hello @juliushaertl 

I have checked the requirements and enabled pdo_sqlite i my php.ini file (attached it in server details) and have sqlite installed. 
I raised it as bug, because it was still giving me this error. Would it be possible for you to tell me if I missed any step?

**Comment by juliushaertl** [comment]
Can you check if it is actually loaded with `php -m`?

**Comment by Adures** [comment]
Ok, turns out it was indeed not loading correctly. Should have checked that. I had wrong version installed. Thanks for your help it is working correctly now.

**Comment by Piotrekq** [comment]
Hello,
Is there any instruction how to enable full text search?

**Comment by max-nextcloud** [comment]
> Hello, Is there any instruction how to enable full text search?

For full-text search to work the sqlite and pdo PHP extensions must be installed.
* Enabled pdo_sqlite.
* check with `php -m` if it's active
* Test in the top bar search on the right to see if you can find pages based on content.

**Comment by Piotrekq** [comment]
Hello, it seems that pdo_sqlite is loaded but page content search still not working:
![image](https://github.com/nextcloud/collectives/assets/45997512/da009233-a58f-45a8-a30f-c38f478ddd2c)

![image](https://github.com/nextcloud/collectives/assets/45997512/c212d808-9892-4705-93e8-4576e884706e)

**Comment by max-nextcloud** [comment]
@Piotrekq could you try with a word that is not in a table?

I wonder if the table somehow interferes here.

**Comment by max-nextcloud** [comment]
@Piotrekq do page titles show up? (They are using a different search provider so this will allow us determine if the collectives search providers work at all)

**Comment by juliushaertl** [comment]
Not fully sure but you might need the `sqlite` module in addition to `pdo_sqlite`

**Comment by spoonerarthur** [comment]
Hello everyone,
I have a freshly installed Nextcloud on an Ubuntu server and the full text search in collectives doesn't work:

php -m:

`
[PHP Modules]
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
`

I wait a night, but nothing. 

I don’t know where is the problem.

Regards Arthur

**Comment by spoonerarthur** [comment]
I found the problem and the solution

I don't have a cronjob

I created it and run the job and now it works
