### ISSUE TITLE
Crash on Nextcloud 26 Beta 3

### ISSUE THREAD

**Issue by cayetano** [nextcloud/collectives#563]
**Describe the bug**
Update to Nextcloud 16 Beta 3, generate "error 500"

**To Reproduce**
1. Update to Nextcloud 26 Beta 3
**Expected behavior**
Work .... at a time !

** error from apache error.log
[Tue Feb 14 11:12:18.111214 2023] [php:error] [pid 436784] [client 192.168.168.5:34404] PHP Fatal error:  Declaration of OCA\\Collectives\\ACL\\ACLStorageWrapper::filesize($path) must be compatible with OC\\Files\\Storage\\Wrapper\\Wrapper::filesize($path): int|float|false in /var/www/html/cloud/apps/collectives/lib/ACL/ACLStorageWrapper.php on line 180

** temporary solucion:
Disable Collectives ;-(

**Comment by mejo-** [comment]
Dear @cayetano, thanks for your report. This is already fixed in development branch: https://github.com/nextcloud/collectives/pull/540

Related remark: The latest release of Collectives is not marked as compatible with Nextcloud 26 for a reason :wink:
