### ISSUE TITLE
Naming a folder Readme.md makes the webinterface unusable

### ISSUE THREAD

**Issue by bbx-github** [nextcloud/collectives#604]
**Describe the bug**
I am mostly working from within the files that are synchronized with the desktop client. I wanted to create a new folder and create the Readme.md for it. But I misclicked and by accident created  a folder with the same name. After it was uploaded I realized that the webinterface was starting producing errors. The main collective page is still working but clicking on the collective itself makes it hang and it will never show anything else then spinning circles. There are 2 error messages appearing: "Could not fetch pagesFailed to get index page" - 2 times the same one. 

**To Reproduce**
1. Go to your synchronized Nextcloud files in any filebrowser
2. Create a new subfolder in your Collectives Folder
3. Create anew folder in there named "Readme.md"
4. Click Synchronize in your Desktop Client
5. Log in the webinterface and click on the Collectives tab.
6. Click on the Collective that contains the Readme.md folder 

**Expected behavior**
Error catching and ignoring the folder

**Screenshots**
![image](https://user-images.githubusercontent.com/53237674/225660893-206538bf-da57-4fd6-ab04-ed5dfe89f28e.png)

**Client details:**
 - OS: Linux
 - Browser: Firefox
 - Version: 24.0.10
 - Device: Desktop

<details>
<summary>Server details</summary>

**Collectives app version:**  1.6.3

**Operating system:** Debian 11

**Web server:** nginx

**Database:** PostgreSQL 11.14

**PHP version:** 7.4.33

**Nextcloud version:** 24.0.10

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"m0KAw64HWC5GtFi2b5Um","level":0,"time":"2023-03-16T15:19:30+00:00","remoteAddr":"X.X.X.X","user":"xxxx","app":"collectives","method":"GET","url":"/apps/collectives/_api/1/_pages","message":"Collectives App NotFound Error: Failed to get index page","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0","version":"24.0.10.1","exception":{"Exception":"OCA\\Collectives\\Service\\NotFoundException","Message":"Failed to get index page","Code":0,"Trace":[{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":160,"function":"getIndexPageFile","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":247,"function":"getParentPageId","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":447,"function":"newPage","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":456,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":456,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":456,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":475,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Controller/PageController.php","line":52,"function":"findAll","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Controller/ErrorHelper.php","line":25,"function":"OCA\\Collectives\\Controller\\{closure}","class":"OCA\\Collectives\\Controller\\PageController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Controller/PageController.php","line":56,"function":"handleErrorResponse","class":"OCA\\Collectives\\Controller\\PageController","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\Collectives\\Controller\\PageController","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/fast/nextcloud/htdocs/lib/base.php","line":1030,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/fast/nextcloud/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","Line":351,"message":"Collectives App NotFound Error: Failed to get index page","exception":{},"CustomMessage":"Collectives App NotFound Error: Failed to get index page"}}
{"reqId":"sRAgvsThnKEceHuefEBi","level":0,"time":"2023-03-16T15:19:30+00:00","remoteAddr":"X.X.X.X","user":"xxx","app":"collectives","method":"GET","url":"/apps/collectives/_api/1/_pages","message":"Collectives App NotFound Error: Failed to get index page","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0","version":"24.0.10.1","exception":{"Exception":"OCA\\Collectives\\Service\\NotFoundException","Message":"Failed to get index page","Code":0,"Trace":[{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":160,"function":"getIndexPageFile","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":247,"function":"getParentPageId","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":447,"function":"newPage","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":456,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":456,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":456,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","line":475,"function":"recurseFolder","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Controller/PageController.php","line":52,"function":"findAll","class":"OCA\\Collectives\\Service\\PageService","type":"->"},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Controller/ErrorHelper.php","line":25,"function":"OCA\\Collectives\\Controller\\{closure}","class":"OCA\\Collectives\\Controller\\PageController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/fast/nextcloud/htdocs/apps/collectives/lib/Controller/PageController.php","line":56,"function":"handleErrorResponse","class":"OCA\\Collectives\\Controller\\PageController","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"index","class":"OCA\\Collectives\\Controller\\PageController","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/fast/nextcloud/htdocs/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/fast/nextcloud/htdocs/lib/base.php","line":1030,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/fast/nextcloud/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/fast/nextcloud/htdocs/apps/collectives/lib/Service/PageService.php","Line":351,"message":"Collectives App NotFound Error: Failed to get index page","exception":{},"CustomMessage":"Collectives App NotFound Error: Failed to get index page"}}

```

#### Browser log
```
I can provide it if it is needed
```

</details>

**Comment by max-nextcloud** [comment]
Nice one! Excellent find.

**Comment by mejo-** [comment]
Dear @bbx-github, thanks for your report. I was unable to reproduce the issue with the latest version of Collectives. Could you see whether you're still able to reproduce the bug with Collectives 2.5.0? You probably have to upgrade to Nextcloud 25 in order to upgrade Collectives.

Also, where exactly did you create the folder named `Readme.md`?  In the folder called `Collectives` (or respectively the localized version of it), or in the folder of a collective (e.g. `Collectives/mycollective`)? I tried both, and neither of them lead to issues.

**Comment by bbx-github** [comment]
Hi @mejo-, I am also unable to reproduce it in 2.5.0 like I was able to in the version before. The webinterface stays usable whatever I try :) so thats good.

But in general the app is not super stable when you edit your files and folders manually (outside of the Collectives app). It is very easy to break things, or ending up with a Collective that you can fix only with creating the appropriate folders and files etc. For example by naming folders readme.md and then having a readme.md inside that folder. It gets ignored and nothing changes in the webinterface until you create any new file or folder and then you have strange things like an empty folder that says "Readme.md (2)". Or deleting every file in a collective. You are unable to create anything now using only the webinterface.

But thats a different thing I think. I think we can close this issue here specifically. The other ones I am unsure about. Should I create new ones for all those small finds?

**Comment by bbx-github** [comment]
> Also, where exactly did you create the folder named `Readme.md`? In the folder called `Collectives` (or respectively the localized version of it), or in the folder of a collective (e.g. `Collectives/mycollective`)? I tried both, and neither of them lead to issues.

Sorry forgot to answer that. I think I created it in another folder. Yes I remember. When it first appeared it was a folder some levels below the first one.

**Comment by mejo-** [comment]
Dear @bbx-github,

> But in general the app is not super stable when you edit your files and folders manually (outside of the Collectives app). It is very easy to break things, or ending up with a Collective that you can fix only with creating the appropriate folders and files etc. For example by naming folders readme.md and then having a readme.md inside that folder. It gets ignored and nothing changes in the webinterface until you create any new file or folder and then you have strange things like an empty folder that says "Readme.md (2)". Or deleting every file in a collective. You are unable to create anything now using only the webinterface.

Sure! If you face issues with the Collectives app, please don't hesitate to report it on Github. Please always try to reproduce a clear step-by-step description of how to reproduce the issue. And if possible, please report different issues seperately. That way it's easier to look into them and work on a fix for us. In any case, feedback is always appreciated :blush:
