### ISSUE TITLE
Creating a subpage fails for user that should have the right to create one

### ISSUE THREAD

**Issue by moan0s** [nextcloud/collectives#610]
**Describe the bug**
Creating a subpage fails for user that should have the right to create one

**To Reproduce**
1. Create a Collective from Account A and add pages/subpages
2. Add account A and B to a circle
3. Share the collective with the circle
4. Log in on Account B
5. Try to create subpage -> fails with `Could not create the page`

**Expected behavior**
A subpage is created

**Debugging steps**
I tried to create a subpage using the Files app (manually create the markdown document in the shared folder). That works but is not user intetive

**Client details:**
 - OS: independent (tested on windows and Linux
 - Browser: tested on Firefox
 - Version: 25.0.4
 - Device: irrelevant
 
<details>
<summary>Server details</summary>

**Collectives app version:** 2.3.0

**Operating system:** Docker

**Web server:** Traefik

**Database:** Postgresql

**PHP version:** Whatever the docker image uses :)

**Nextcloud version:** 25.0.4

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Mar 22 17:37:09 hostname nextcloud-apache[976102]: <ip> - - [22/Mar/2023:17:37:08 +0000] "POST /apps/collectives/_api/2/_pages/parent/30612 HTTP/1.0" 404 783 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"

```

#### Browser log
```
XHRPOSThttps://example.org/apps/collectives/_api/2/_pages/parent/30612
[HTTP/2 404 Not Found 542ms]

	
POST
	https://example.org/apps/collectives/_api/2/_pages/parent/30612
Status
404
Not Found
VersionHTTP/2
Transferred765 B (23 B size)
Referrer Policyno-referrer
Request PriorityHighest

    	
    cache-control
    	no-cache, no-store, must-revalidate
    content-length
    	23
    content-security-policy
    	default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
    content-type
    	application/json; charset=utf-8
    date
    	Wed, 22 Mar 2023 17:39:05 GMT
    expires
    	Thu, 19 Nov 1981 08:52:00 GMT
    feature-policy
    	autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
    pragma
    	no-cache
    referrer-policy
    	no-referrer
    server
    	nginx
    x-content-type-options
    	nosniff
    X-Firefox-Spdy
    	h2
    x-frame-options
    	SAMEORIGIN
    x-permitted-cross-domain-policies
    	none
    x-powered-by
    	PHP/8.1.16
    x-request-id
    	2fsa7a7BDuP7xHUzNGRM
    x-robots-tag
    	none
    x-xss-protection
    	1; mode=block
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-US,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	37
    Content-Type
    	application/json
    Cookie
    	nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=moanos; nc_token=6xufFB79wellnotsofastuSq4lhef%2F6WXXD7j; nc_session_id=0d71dd332070175tesme682c902; oca3u82rt0wl=af73d335welld518d0d358f5519; oc_sessionPassphrase=rvsk44Enottherealone61AO71cFIfwq; oc69m7zjten6=2cab57a10e4whateverde945d32d7ad2; oc07b0vit3cm=0dada752fcb1e6499682c902
    DNT
    	1
    Host
    	example.org
    Origin
    	https://example.org
    requesttoken
    	zxa6GK28wWUj9Y9QHPnotrealBPlXMk=:+mzSLpXrsVVSuuMdadaMrYqJ+6Mp0U9tUFdodoGqs=
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0
```

</details>

**Comment by mejo-** [comment]
Dear @moan0s, thanks for your report.

I'm unable to reproduce the issue with latest Collectives (version 2.5.0), but maybe I'm missing something. What exactly do you mean with "3. Share the collective with the circle"? Could you elaborate on how you did this?

What I tried:

1. Create a new collective "mycollective" as user jane
2. Create a new circle "mycircle" as user jane
3. Add user bob as member to circle "mycircle"
4. Add circle "mycircle" as member to circle "mycollective"
5. Browse the collective "mycollective" as user bob and create new pages + subpages

**Comment by mejo-** [comment]
Closing due to lack of further information. Feel free to reopen with the requested information if you still face this issue.
