### ISSUE TITLE
WARNING: Data vanishes when circle is deleted

### ISSUE THREAD

**Issue by ludenticus** [nextcloud/collectives#613]
Using `Collectives` now in a production environment is extremely risky. It should be warned that **the app will wipe out all your data** whenever you delete its associated circle. If you have a backup of your Documents, you will recover the `.md` files, but you will inevitably lose your Collective.

It's a mayor design flaw. At least the owner should be able to _recreate_ the Collective.

**Comment by mejo-** [comment]
Dear @ludenticus, thanks for your report. I agree with your assessment. There's also #314 to track this problem. I hope to find time to work on this in the upcoming weeks.
