### ISSUE TITLE
PDF-Attachments are previewed as broken images when clicked in view mode on Nextcloud 26

### ISSUE THREAD

**Issue by niklas-englert** [nextcloud/collectives#620]
**Describe the bug**
Although bug #396 is now fixed (attachments are rendered as broken images in view mode), the behavior when clicking attachments remains the same: They're previewed as broken images.

**To Reproduce**
1. Drag & drop a PDF in a Collectives page
2. Change to view mode (/exit edit mode)
3. Click on the PDF box (grey outline, red PDF file icon, filename, size)
4. See a broken image being displayed

**Expected behavior**
A PDF correct working preview or iframe (or a file download starting).

**Screenshots**
![Collectives_Bug_Preview_PDF](https://user-images.githubusercontent.com/24723486/228192099-8052bf13-66bd-4652-b2f4-37b526768d77.PNG)

**Client details:**
 - OS: any
 - Browser: any
 - Version: Nextcloud 26.0.0 / Collectives 2.4.0
 - Device: any

**Comment by mejo-** [comment]
Thanks for your report @niklas-englert. It's a bug in Nextcloud Text, being tracked in nextcloud/text#3849 and being worked on in nextcloud/text#3924.

**Comment by Jeefongithub** [comment]
I'm experiencing a similar issue in 2.9.2

**Comment by mejo-** [comment]
@Jeefongithub the fix requires Nextcloud 27.1.5 (due date 14. Dec) or 28.0.0 (due date 12. Dec) to be installed. Please report back if you still face this issue after upgrading.

**Comment by Jeefongithub** [comment]
upgraded to 27.1.5 rc1 and issue is no longer present
