### ISSUE TITLE
Opening page in view mode updates last modified date

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/collectives#621]
**Describe the bug**
When you open any collective page in the view mode (set as default in the collective settings), the page will get a new last modified date, so that these files will e.g. also show up in the recommended files list. According to the network tab in the dev tools it might also be Text related

**To Reproduce**
1. Go to any collective page in view mode
2. See last edit timestamp
3. Reload page
4. See last modified date has changed

**Expected behavior**
Not updating the timestamp when just viewing a page

**Screenshots**
First visit in view mode:
![image](https://user-images.githubusercontent.com/16020496/228225344-929dd150-746b-48fd-a57a-bfaaad4275c9.png)

After reload:
![image](https://user-images.githubusercontent.com/16020496/228225519-6641db6f-f53c-4faf-afe2-892ef34a3905.png)

**Client details:**
 - OS: independent
 - Browser: Firefox/Chrome
 - Version: latest
 - Device: Desktop

<details>
<summary>Server details</summary>

**Collectives app version:** 2.4.0

**Operating system:** official Docker

**Web server:** official Docker

**Database:** PG 14

**PHP version:** official Docker

**Nextcloud version:** 26.0.0

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
lots of sync / push events to the Text app:
![image](https://user-images.githubusercontent.com/16020496/228226189-54c1e85d-bd26-49dd-80b5-f60a83389ad0.png)

</details>

**Comment by mejo-** [comment]
Thanks for your report @Chartman123. Does this happen with all pages, or just with pages that contain headings? This is a known issue on Nextcloud 26.0.0 and will hopefully be fixed in Nextcloud 26.0.1 (nextcloud/text#3972 should bring a fix for it).

**Comment by Chartman123** [comment]
I can confirm that this does not happen for pages without headings... So probably the known bug 👍🏻

**Comment by Chartman123** [comment]
The issue is fixed with the latest maintenance releases (26.0.1 in my case).
