### ISSUE TITLE
Collectives is very buggy on Firefox

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/collectives#625]
**Describe the bug**
I'm testing Collectives on Firefox and Chromium since yesterday. So far, everything works fine on Chromium, but it's very complicated on Firefox. On FF, creating/renaming/saving pages and sub-pages almost never works right away: I have to wait 10, 15 seconds, or somtime to choose an emoticon, in order to see the sidebar and the pages titles updated. Note that I tried with `firefox --safemode` (without extension) with the same result.

**Expected behavior**
Everything is almost directly updated (that's the behavior I got with Chromium)

**Screenshots**

https://user-images.githubusercontent.com/34077099/228467835-ffb62d54-1081-4d0f-8a76-47c7b1b5d62c.mp4

**Client details:**
 - OS: Arch
 - Browser: Firefox
 - Version: 111
 - Device: desktop

**Collectives app version:** 2.4.0

**Operating system:** Debian

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** 25.0.5

#### Nextcloud log (data/nextcloud.log)
nothing relevant

#### Browser log
nothing relevant

**Comment by mejo-** [comment]
Dear @Ornanovitch, thanks for your report. It's the first time I hear that people have issues with Collectives on Firefox. In fact I develop Collectives on Firefox all the time and know of several people who use Collectives daily with Firefox.

Is there anything special about your setup? How did you install the app? From the app store, or did you build it yourself?

Please also capture a log of your network requests to help with debugging.

You can do so the following way:
1. Open the developer tools of your browser, navigating to the "Network" tab
2. Do whatever reproduces the issue you reported
3. In the settings menu (rack-wheel button), select "Save as HAR"

Please note that the HAR file might contain personal data. It contains all network requests that your browser did in the open tab, i.e. URLs, page metadata and page content.

**Comment by Ornanovitch** [comment]
> Is there anything special about your setup? How did you install the app? From the app store, or did you build it yourself?

Nothing special I guess: it's a random NC 25 on a Debian LXC container. I installed the app from the app store.

**Comment by mejo-** [comment]
Also, two more questions:

Do you by chance have another Nextcloud instance available where you could test whether it behaves similarily?

Could you downgrade Collectives to 2.3.0 on your instance and see whether this makes a difference? There were no backwards-incompatible changes in the 2.4.0 release. All you have to do is:
1. Move `apps/collectives` somewhere else
2. Unpack the [2.3.0 release tarball](https://github.com/nextcloud/collectives/releases/download/v2.3.0/collectives-2.3.0.tar.gz) into the `apps/` folder
3. Force-reload the Collectives page in browser (<kbd>Ctrl</kbd>-<kdb>F5</kbd>)
4. After your tests you can remove `apps/collectives` and move back the old Collectives 2.4.0 directory into place

**Comment by Ornanovitch** [comment]
> Could you open the task manager (about: performance) in a separate Firefox window and see how energy and memory consumption behaves in the tab with laggy Collectives?

There's nothing suspicious here, perfs are similar to other JS pages, even when the bugs occur

> Also, do you experience similar issues in other Nextcloud apps, or just in Collectives?

Not at all, it's our first problem since a long time (we use Calendar, Tasks, Contacts, Office, Group folders...)

> Do you by chance have another Nextcloud instance available where you could test whether it behaves similarily?

No but I'll try to setup a local env in order to try!

> Could you downgrade Collectives to 2.3.0 on your instance and see whether this makes a difference?

I do it right away and I let you know :)

**Comment by Ornanovitch** [comment]
version 2.3.0 makes no difference (it's somehow good news though)

**Comment by Ornanovitch** [comment]
We had a really strange experience yesterday with 3 comrades, after I introduced Collectives to them. We were on a video  meeting, 3 are in France and 1 is in Sweden. All 4 of us are on Linux/Firefox, but only 1 of us had no bug at all when manipulating Collectives (the one in Sweden). The rest of us had the same buggy behavior. I don't know what to think about this x_X.

I'll try to setup a local NC env in a few days. But is there a demo instance somewhere, on which I could do some tests?

**Comment by Ornanovitch** [comment]
OH WAIT @mejo- I just find a nice clue! 

- In the developer tools, navigating to the network tab
- Check "Disable cache"
- Hard refresh

Result: everything is running smoothly! Look at this:


https://user-images.githubusercontent.com/34077099/228790016-cd789df2-5826-4ceb-a160-4987382247f8.mp4

So, this seems to be a browser cache problem?

**Comment by juliushaertl** [comment]
Glad to hear that. In general we have a cache buster on all javascript and CSS files that get fetched so after a version upgrade the URL would be different and those should be fetched again, so I cannot really explain why that was a problem here. Maybe indeed some browser oddness. You could probably check if your Nextcloud was in debug mode, which would disable the cache buster iirc and this would not be recommended on production instances anyways. Are you fine to close this issue then?

**Comment by Ornanovitch** [comment]
> You could probably check if your Nextcloud was in debug mode, which would disable the cache buster iirc and this would not be recommended on production instances anyways. Are you fine to close this issue then?

Our NC was (and is) not in debug mode, so I think this is something else. Maybe some browser oddness, but we are at least 4 having this bug with different Firefox versions, so I think there is something else. The problem is not resolved because we have to disable our browser's cache with the dev tools in order for Collectives to work. This is far from a normal solution... So I would prefer if we could keep this issue open, and in the meantime, we need to try Collectives on other Nextcloud instances.

**Comment by Ornanovitch** [comment]
OK, after further investigations, it appears it's totally our fault! We left a non-recommended parameter in our Nginx config:

```conf
    # Default Cache-Control policy
    expires 1m;
```

Thanks (and sorry) for your time :)

**Comment by juliushaertl** [comment]
Good to hear that and thanks for sharing the solution here as well :)
