### ISSUE TITLE
You're not part of a collective with that name

### ISSUE THREAD

**Issue by jvantslot** [nextcloud/collectives#642]
Since the latest upgrade to Collectives 2.4.0 All of my links within my Collectives to other files within the same collective stopped working.  When I click the links to files within the Collective, I get the error

Collective not found: [Name of Collective Redacted]
You're not part of a collective with that name. 

An example URL that doesn't work looks like the following.
https://nextcloud.example.com/index.php/apps/files/?dir=/&openfile=102531734#relPath=Filename.md

I have yet to find one that does work.

**To Reproduce**
1. Edit a page in a collective
2. Add a new link to another file within the collective.
3. Click the DONE button to complete the page edit

**Expected behavior**
The Link should open the linked page or file

**Client details:**
 - OS: Linux (Ubuntu), Windows 10
 - Browser: Chrome, Firefox

**Collectives app version:**
24.0

**Operating system:**
Rocky Linux 9.1

**Web server:**
Apache/2.4.53 (Rocky Linux)

**Database:**
10.5.16-MariaDB MariaDB Server

**PHP version:**
PHP 8.0.28

**Nextcloud version:** 
25.0.5

**Comment by 42ske** [comment]
same here. but I also don't have any idea.
