### ISSUE TITLE
Search highlight

### ISSUE THREAD

**Issue by vdtoorn** [nextcloud/collectives#648]
**Is your feature request related to a problem? Please describe.**
When using collectives with somewhat large pages, it is very hard to find a searched text, because the search only every shows the page and does not highlight the text. Also, ctrl-F to search in the browser window does not work, because that is overruled by the global search option, and '/' to search is crippled somehow too.

**Describe the solution you'd like**
At the minimal it would be advantageous to highlight the current search terms in the current collective window. Alternatively, going through the result list could jump to the correct location within the collective page.

**Describe alternatives you've considered**
I can't think of alternatives other than '/', but that also does not work for me if the search term is in the pages list for instance.

**Additional context**
-

**Comment by juliushaertl** [comment]
https://github.com/ueberdosis/tiptap/pull/2075 could be some useful inspiration for implementing highlights in text
