### ISSUE TITLE
Could not fetch collectives

### ISSUE THREAD

**Issue by FesTGig** [nextcloud/collectives#676]
When switching back and forth between pages of the collectives, suddenly this bug occurs:
Nextcloud reports:
```
Could not fetch collectives from trash[object Object]
Could not fetch collectives folder
Could not fetch collectives [object Object]
```

Reloading the page does not help. When logging out of Nextcloud the following error get reported:
`Access forbidden CSRF check failed`

The Log shows:
```
[PHP] Error: TypeError: OCA\Collectives\Controller\SettingsController::__construct(): Argument #5 ($userId) must be of type string, null given at /var/www/nextcloud/apps/collectives/lib/Controller/SettingsController.php#22

GET /ocs/v2.php/apps/collectives/api/v1.0/settings/user/user_folder
```

<details>
<summary>Server details</summary>
**Collectives app version:** (see Nextcloud apps page)
Collectives 2.4.0

**Operating system:**
Ubuntu 22.04.

**Web server:**
nginx

**Database:**
maria DB 10.8.

**PHP version:**
8.1.2

**Nextcloud version:**
26.0.1
</details>

**Comment by mejo-** [comment]
Dear @FesTGig, thanks for your report.

The error message suggests that your user got logged out of Nextcloud. Could this be the reason? Is the error gone after you logged in again?

Also, are you able to reproduce the bug reliably? If so, could you please provide a detailed step by step instruction how to reproduce it?

**Comment by FesTGig** [comment]
yes it definitely has something to do with logging out. when the error occurs, I am in the document, to fix the error, I have to log out, but after logging out once and reloading the browser window, I do not get to the login screen. Only after the second logout it seems to work correctly.

Also I see in the document, often the display as if someone else is working on it, but from the same user in which I am logged in. As if the same user was more times in the document. But I have checked it, I have the document open only once.

currently I can not reproduce the error with certainty.

**Comment by mejo-** [comment]
Dear @FesTGig, do you still encounter this issue? I'll close the report for now, but feel free to comment with further details if you still encounter the problem.

**Comment by Pipazoul** [comment]
I've got the same problem after having changed my nextcloud domain name
