### ISSUE TITLE
Not able to make hyperlinks

### ISSUE THREAD

**Issue by Sveske-Juice** [nextcloud/collectives#677]
**Description**
There is no button to make hyperlinks to either external or internal sites. There used to be a button which would pop-up when highlighting text.

**To Reproduce**
1. Create some text
2. Hover over the text
3. Observe no button to create hyperlink

**Expected behavior**
The button is expected to show when selecting text

**Client details:**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 112.0
 - Device: Desktop

<details>
<summary>Server details</summary>

**Collectives app version:**
2.4.0

**Operating system:**
Arch Linux (kernel: linux 6.1.12.arch1-1)

**Web server:**
Nginx reverse proxy setup

**Database:**
mysql (mariadb)

**PHP version:**
8.1.15

**Nextcloud version:**
26.0.1
</details>

**Comment by mejo-** [comment]
Dear @Sveske-Juice, thanks for your feedback. With Nextcloud 26, the option to create links was moved into the toolbar menu. You find it behind the hyperlink button there.

The bubble menu that popped up when selecting text caused too much confusion for users, that's why we moved it to the toolbar menu.

**Comment by Sveske-Juice** [comment]
Thanks for your reply. Using the toolbar option works great but it doesn't seem to be possible to make hyperlinks, where you can specify a custom name for the link. In markdown it would be equivalent to `[link] (url)`. The link option from the toolbar inserts the whole link without any formatting:
![image](https://github.com/nextcloud/collectives/assets/66884216/49f964f2-2db7-4f3c-8aae-910af6a48738)

Also making internal links to other pages within the collective looks like this, but can't be re-named or the link will disappear.

**Comment by mejo-** [comment]
> but it doesn't seem to be possible to make hyperlinks, where you can specify a custom name for the link.

If you first select some text and then go to the toolbar to create the link, the selected text will be the title of the link. Also you should be able to edit this text later on by simply moving the cursor there and typing the changes, no?

**Comment by Sveske-Juice** [comment]
Thank you, that worked :D

**Comment by isaw1** [comment]
@mejo- 

> you should be able to edit this text later on by simply moving the cursor there and typing the changes

Regarding this, I've tried to edit text multiple times and whenever I take out the last / the link is removed. its annoying when trying to link to other pages usinfg the smartpicker

Ideally, if you highlight text, then create a link if should keep the highlighted text.  Perhaps add a "Edit Text" option in the Link menu?  or have the ability to do the standard [Text](Link.to/page)

**Comment by mejo-** [comment]
> Regarding this, I've tried to edit text multiple times and whenever I take out the last / the link is removed. its annoying when trying to link to other pages using the smartpicker

Dear @isaw1, this sounds like a bug. The relevant code is in Nextcloud Text though. Could you open a new issue [here](https://github.com/nextcloud/text/issues/new/choose) about it along with some screenshots and exact explanation of how to reproduce the issue?
