### ISSUE TITLE
rights management / be able to prohibit deleting pages by users 

### ISSUE THREAD

**Issue by cringwald** [nextcloud/collectives#689]
We lost pages because users did delete pages / subpages by accident. 

It would be great to have the possiblitie that user are allowed to create a page but not to delete. 
(Deleting of pages only possible by the owner of the circle or a mod.)

**Comment by joshtrichards** [comment]
A little bit related to #601.

**Comment by cringwald** [comment]
It is a help but it would be much better to allow deleting only for the administrator or moderator of the collective.

**Comment by mejo-** [comment]
Dear @cringwald, after further discussing this with the design team we decided to not implement such a feature. Even if you prohibit to delete pages, there's nothing that stops your users from accidentally deleting page content. Instead, we'll think about adding a undo button to the "Page deleted" notification toast that allows easy restoring of accidentally deleted pages. This feature will be tracked here: https://github.com/nextcloud/collectives/issues/794
