### ISSUE TITLE
Illegal use of server 3rdparty (symfony/event-dispatcher) 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/collectives#710]
This app is directly using classes of the `symfony/event-dispatcher` package in server. Please migrate to the official OCP wrappers.

**Comment by mejo-** [comment]
Thanks for raising this @nickvergessen.

In [CacheListener.php](https://github.com/nextcloud/collectives/blob/cedaedccc198121ca09abcb5718681983bda4d65/lib/CacheListener.php#L12) this is pretty straight-forward. Just replace `Symfony\Component\EventDispatcher\EventDispatcher` with `OCP\EventDispatcher\IEventDispatcher`.

But in [Versions/CollectiveVersionsExpireManager.php](https://github.com/nextcloud/collectives/blob/cedaedccc198121ca09abcb5718681983bda4d65/lib/Versions/CollectiveVersionsExpireManager.php#L30) I'm not sure about the solution. [`new User()`](https://github.com/nextcloud/collectives/blob/cedaedccc198121ca09abcb5718681983bda4d65/lib/Versions/CollectiveVersionsExpireManager.php#L122) expects `Symfony\Component\EventDispatcher\EventDispatcherInterface` as argument, and `IEventDispatcher` doesn't provide that.

**Comment by nickvergessen** [comment]
Might be needed that server is modified before this. But not entirely sure.

**Comment by nickvergessen** [comment]
> But in [Versions/CollectiveVersionsExpireManager.php](https://github.com/nextcloud/collectives/blob/cedaedccc198121ca09abcb5718681983bda4d65/lib/Versions/CollectiveVersionsExpireManager.php#L30) I'm not sure about the solution. [new User()](https://github.com/nextcloud/collectives/blob/cedaedccc198121ca09abcb5718681983bda4d65/lib/Versions/CollectiveVersionsExpireManager.php#L122) expects Symfony\Component\EventDispatcher\EventDispatcherInterface as argument, and IEventDispatcher doesn't provide that.

https://github.com/nextcloud/server/pull/39595 has you covered... Or well that creates the problem for you. But now you can give it IEventDispatcher.

**Comment by max-nextcloud** [comment]
Checked in with jonas and the two aspects were addressed separately - one with the commits listed above on Jun 5 and the linked PR above just addressed what was left afterwards.
