### ISSUE TITLE
hide the collectives folder in the files app

### ISSUE THREAD

**Issue by FesTGig** [nextcloud/collectives#712]
could you add the option to hide the collectives folder in the files app?
Currently, the handling is very unclear, users of the Nextcloud instance repeatedly go directly to the folder structure instead of the app and try to edit there. This leads to users storing data or creating files there, which are not visible to the users who use the app.

Perhaps an important change is for the folder use of other apps in Nextcloud in general, to avoid the confusion between the data from the apps and the productive projects files.

**Comment by mejo-** [comment]
Dear @FesTGig, thanks for your info. Which versions of Collectives to you have installed? With recent versions, there should be an infobox saying "The content of this folder is best viewed in the Collectives app." with a button to switch to the Collectives app when browsing the Collectives folders. Does this address the issue for you?

**Comment by FesTGig** [comment]
The current version 2.5.0 is running. The infobox also appears, but this does not seem to stop users from messing up the folders... :see_no_evil:
So I think still this would be a major improvement to have the possibility to hide the collectives folder in the files app in terms of keeping things easy and organised.
