### ISSUE TITLE
The SVG-File is only directly visible in Edit Mode

### ISSUE THREAD

**Issue by devsick** [nextcloud/collectives#720]
When I embed a svg file in Edit mode, the file is directly visible. When I publish the site, only a link is visible. This is uncomfortable for things, someone want to see directly.

**Comment by tatrapikao** [comment]
confirmed in Collectives 2.7.0 in firefox 116.0.2. Also when i remove the given svg from the Document and afterwards drag it back in from the side-panels attatchment-section it renders as this:
![Bildschirmfoto_2023-09-09_00-38-12](https://github.com/nextcloud/collectives/assets/77448960/a81de12a-3d8a-435a-8a95-139e45f4c0ff)

**Comment by mejo-** [comment]
This should be fixed by now. SVGs are also displayed in view mode.
