### ISSUE TITLE
missing slash at the end of the menu link

### ISSUE THREAD

**Issue by quenenni** [nextcloud/collectives#727]
**Describe the bug**
The menu link to Collectives is the only one that does not finish with a /
Because of this, it gets a wrong address from the server (the port switches from 443 to 4431) and tries to enter the Collective page on the port 4431.

If I put the same address but with a / at the end, I enter the collectives page without problem.

I recently had to check my nginx configuratin to fix things with nextcloud v26, so I know I have the last version.

My setup is using Haproxy in front of Nginx and the port 4431 that the collective app gets to forge the address comes from somewhere there as Haproxy send requests to Nginx on port 4431.

I tried to force the port 443 in nginx configuration (with a `fastcgi_param SERVER_PORT 443;`), but no change.

Can't the solution be simply to add the slash at the end like all other menu points?

**To Reproduce**
1. Click on Collectives menu
2. Timeout error and we cn see in the addressbar that the port switched to 4431 (`https://cloud.xxx.yyy:4431/apps/collectives/`)

**Client details:**
Several browsers, several Os

<details>
<summary>Server details</summary>

**Collectives app version: v2.5.0** (see Nextcloud apps page)

**Operating system: Debian v11.7**

**Web server: Nginx v1.18.0-6.1+deb11u3**

**Database: Mariadb-server v1:10.5.19-0+deb11u2**

**PHP version: v8.1.8**

**Nextcloud version: v26.0.2** (see Nextcloud admin page)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
nothing in nextcloud.log in debug mode.
nothing in nginx log.
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The network log
When I click on the menu, I can see a fist request to https://cloud...../apps/collective  (without the slash)
just after, a second line that does a GET request to https://cloud....:4431/apps/collectives/
Then nothing (except the notifications requests) until the error.

```

</details>

**Comment by mejo-** [comment]
Thanks @quenenni for your report. Seems like the same problem reported in #411. I developed a fix at #733.

**Comment by quenenni** [comment]
Hello,

Thanks a lot for your quick reaction.
I tested your patch and the problem is no more.

Much appreciated.

**Comment by nunoleite** [comment]
Sorry to open this, but i think this created a new bug.
Now in search the link has 2 backslashes and it doesn't open
https://xxx.xxx.com/apps/collectives//something?fileId=32324

**Comment by mejo-** [comment]
Thanks for your report @nunoleite. I opened a new issue #762 to track the bug you describe. It's indeed a regression with Collectives version 2.6.0.
