### ISSUE TITLE
Corrupted Database. Cannot delete move page

### ISSUE THREAD

**Issue by trvrcr** [nextcloud/collectives#734]
Iwas setting up QOwnNotes on the desktop and it was not clear you need to make the local folder the same as the sync folder.
So due to some moving around after i made notes something messed up.

And now my Notes.Sqlite is corrupted i think.

Is there a way to rebuild the database?

**Comment by mejo-** [comment]
Dear @trvrcr. Seems like you're talking about the Notes app, not about Collectives, right? Also this sounds more like you missconfigured something and need to fix it now. The Nextcloud Forum over at https://help.nextcloud.com/ is the best place for these kind of questions.
