### ISSUE TITLE
A Usable Shortcut for Saving Files

### ISSUE THREAD

**Issue by SpamMusubi153** [nextcloud/collectives#742]
**Describe the bug**
Currently, users can use the Control + S shortcut to save the currently open page in a Collective. However, in most cases, this also causes a copy of the page to be downloaded, making this shortcut much less useful.

**To Reproduce**
1. Open a page in a Collective
2. Make a change to the page
3. Press the Control button or Command button and the "S" key

**Expected behavior**
The collective page saves without downloading an HTML copy of the page.

**Comment by juliushaertl** [comment]
Related to https://github.com/nextcloud/text/issues/4244 it may be sensible to also catch the shortcut in collectives for the whole app container and trigger just a page save then.

**Comment by mejo-** [comment]
Thanks @SpamMusubi153 for your report. This actually got fixed in the Text app with https://github.com/nextcloud/text/pull/4400 recently. The fix will be released with the next point releases of Nextcloud 25, 26 and 27.

**Comment by SpamMusubi153** [comment]
Thank you!
