### ISSUE TITLE
Sharing a site with public link possible? 

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/collectives#757]
I search a simple way to share public some content like a easy website containing of headlines, some text, pictures and links. 
Is it possible to share an entry with a public link (without the possibility to edit something of course) ?

Absolutely amazing would be to have the possibility to embed a video with an iframe (youtube or vimeo)

Greetings, Stefan

**Comment by mejo-** [comment]
Dear @stefan-franz. Collectives can already be shared publically with a link. See the "Share link" option in the three-dot menu of a Collective. Editing is not allowed per default for these public share links (but can be allowed). I guess that's what you're looking for?
