### ISSUE TITLE
Search links broken due to superfluous slash

### ISSUE THREAD

**Issue by mejo-** [nextcloud/collectives#762]
With Collectives 2.6.0, links from the collectives search results as well as the smartpicker for collectives pages are broken.

The problem is that the links now contain two slashes instead of one between app URL and the collective name.

> Now in search the link has 2 backslashes and it doesn't open https://xxx.xxx.com/apps/collectives//something?fileId=32324
>
> note: smartpicker doesn't work for collectives and backlinks are not working too. I think this is all related with those 2 slashes in the url
_Originally posted by @nunoleite in https://github.com/nextcloud/collectives/issues/727#issuecomment-1620839375_

**Comment by mejo-** [comment]
@nunoleite I have prepared a fix for this here: https://github.com/nextcloud/collectives/pull/763. If you feel capable of applying a patch to the collectives app, could you imagine to apply https://github.com/nextcloud/collectives/pull/763.patch and see whether this fixes all your issues (also with smart picker and backlinks)?

**Comment by nunoleite** [comment]
Have applied the fix manually and it's working ✔

**Comment by danielcommesse** [comment]
@nunoleite I've found the issue to be because of this https://github.com/nextcloud/collectives/pull/763#pullrequestreview-1519024441

**Comment by nunoleite** [comment]
> @nunoleite I've found the issue to be because of this [#763 (review)](https://github.com/nextcloud/collectives/pull/763#pullrequestreview-1519024441)

Just tested and it's ok
