### ISSUE TITLE
No copying of tables possible

### ISSUE THREAD

**Issue by Weltenstoeberer** [nextcloud/collectives#765]
It is not possible to copy tables or export them as csv. If you use the app as a wiki, like in our project, this is a functionality that I miss....

**Comment by mejo-** [comment]
Dear @Weltenstoeberer, could you elaborate on what you mean with "copying of tables"? Copying tables by selecting it and then using copy + paste should work, I just tested this.

You can also select a table and paste it into a spreadsheet application (like LibreOffice Calc) and it works as expected. Why would you need an extra "export to CSV" feature?

**Comment by mejo-** [comment]
Closing this due to lack of further information.
