### ISSUE TITLE
After Update to 26.0.3 we see this Error

### ISSUE THREAD

**Issue by JochenKanta** [nextcloud/collectives#767]
After our Hoster did an Update to the NC Version 26.0.3 (version: 26.0.3.2
  - versionstring: 26.0.3) we are no longer able to see our collectives.

![Bildschirmfoto 2023-07-06 um 22 24 35](https://github.com/nextcloud/collectives/assets/57183517/50921bc4-0ca7-41d8-88d4-c95f71d7d331)

**Client details:**
 - OS: [MacOS 13.4.1]
 - Browser: [Firefox]
 - Version: [114.0.2]
 - Device: [desktop]

<details>
<summary>version: 26.0.3.2
  - versionstring: 26.0.3</summary>

**Collectives app version:** 2.6.0

**Operating system: is hosted

**Web server: is hosted

**Database:mysql 10.5

**PHP version:8.2

**Nextcloud version:** 26.0.3

</details>

**Comment by mejo-** [comment]
Dear @JochenKanta, thanks for your report. Could you elaborate a bit on the error you see? The screenshot only shows parts of the messages, there's no real error message in it.

Did the error occur after upgrading Nextcloud to 26.0.3, or after upgrading Collectives to 2.6.0? Do all other apps still work?

Please provide a full screenshot of the broken Collectives app.

Also, please open the developer console of your browser (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>I</kbd> on Firefox/Chrome), open the collectives app and see whether you see any errors or warnings being logged.

And please take a look into the `nextcloud.log` logfile on your server and see whether you see relevant errors there when trying to open the Collectives app.

**Comment by mejo-** [comment]
Dear @JochenKanta, glad to hear that you could solve the problem on your side. Closing the issue then.
