### ISSUE TITLE
Smart Picker Links adding extra / in URL

### ISSUE THREAD

**Issue by isaw1** [nextcloud/collectives#770]
**Describe the bug**
When using smart picker to add links to local collectives pages an extra / is added to the URL, and as such does not open correctly.

**To Reproduce**
1. create page 1 and page 2
2. using smart picker create a link to page 2
3. click link
Note the url in the shortcut is https://linkto.url/apps/collectives**//**Example/Page2?fileId=858

Page does not open correctly. 

**Expected behavior**
link should have single / only  eg
https://linkto.url/apps/collectives/Example/Page2?fileId=858

**Client details:**
 - OS: [e.g. iOS] docker AIO
 - Browser: [e.g. chrome, safari] Edge
 - Version: [e.g. 24]  NC 27.0.0   /  Collectives  2.6.0

**Comment by mejo-** [comment]
Thanks @isaw1 for the report. This already got reported in #762 and got fixed in #763. I will publish a bugfix release soon.

**Comment by isaw1** [comment]
Awesome.
Thanks.
