### ISSUE TITLE
Feature: Allow to disable the files integration

### ISSUE THREAD

**Issue by susnux** [nextcloud/collectives#773]
**Is your feature request related to a problem? Please describe.**
Some users do not get that collectives is an app and therefor edit files in the files view which does not provide all features and also always opens the file as writeable.

**Describe the solution you'd like**
Config option to disable the files integration for non owners of a circle.

**Describe alternatives you've considered**
Teach users how to use the app.

**Comment by mejo-** [comment]
@susnux as discussed in a private conversation, that's unfortunately not feasible technically. The Collectives app requires the folder to be mounted in the home directory.

We could think about other solutions to "hide" the Collectives folder to users, but I'd prefer to discuss this in a separate issue. Let's close this one for now.
