### ISSUE TITLE
Remove the notification "The contacts app is required to manage members"

### ISSUE THREAD

**Issue by AIlkiv** [nextcloud/collectives#779]
**Is your feature request related to a problem? Please describe.**

I provide access to the App Contacts through a group because it's an unnecessary module for most users. Only admins of the "Collective" have access to it. As a result, all users who don't have access to the App Contacts constantly encounter the error message "The contacts app is required to manage members," which is disruptive.

![Screenshot 2023-07-11 095305](https://github.com/nextcloud/collectives/assets/5858915/992471bb-3854-44d1-a83c-22ca6078dd83)

**Describe the solution you'd like**

Remove the existing notification. Add the text "You don't have access to the Contacts App. Please contact the Administrator" to the Collective card.

![Screenshot 2023-07-11 100551](https://github.com/nextcloud/collectives/assets/5858915/a59fff5d-2b40-4f28-b42a-6bba50038367)

**Additional context**

If the proposed solution is suitable, I can implement it.

**Comment by juliushaertl** [comment]
Could also be addressed by #308, do you think that would be suitable for your use case already?

**Comment by AIlkiv** [comment]
Yes, that will solve the problem. But this is a big task, which I think will take a long time to implement.
