### ISSUE TITLE
Public link to Nextcloud Collective does not display content

### ISSUE THREAD

**Issue by Zockersee** [nextcloud/collectives#780]
**Describtion**
We are using the Nextcloud Collective as a wiki. However, for the past two days, nothing has been displayed on the page when the public link to the Collective is opened. We are using Nextcloud version 27.0.0 on an Ubuntu 22.04.2 LTS VM. Everything was working before the error occurred and no changes were made.

When I am logged in with an account and access the Collective directly, I do not receive any errors and everything is displayed correctly.

**Screenshots**

With the public Link

![image](https://github.com/nextcloud/collectives/assets/122356660/3eacd983-5b07-48f4-9b6d-64677cd5ddd4)

When I am logged in

![image](https://github.com/nextcloud/collectives/assets/122356660/3db1717d-7240-4ac3-a8e7-831e21cf21cf)

**Client details:**
 - OS: Windows 11 & Windows 10
 - Browser: All
<details>

<summary>Server details</summary>

**Collectives app version:** (see Nextcloud apps page)
2.6.1

**Operating system:**
Ubuntu 22.04.2 LTS 

**Web server:**
Apache 

**Database:**
MySQL 

**PHP version:**
PHP 8.1.2-1ubuntu2.13

**Nextcloud version:** (see Nextcloud admin page)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"W7ofqWMmBJydOkuh1vvn","level":3,"time":"2023-07-11T08:15:02+00:00","remoteAddr":"192.168.3.235","user":"admin.edv","app":"collectives","method":"DELETE","url":"/index.php/apps/collectives/_api/1/share/ejyWr9eQnxoHtYZ","message":"Collectives App Error: OCA\\Photos\\Album\\AlbumMapper::removeFileWithOwner(): Argument #2 ($ownerId) must be of type string, null given, called in /var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php on line 55","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36","version":"27.0.0.8","exception":{"Exception":"TypeError","Message":"OCA\\Photos\\Album\\AlbumMapper::removeFileWithOwner(): Argument #2 ($ownerId) must be of type string, null given, called in /var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php on line 55","Code":0,"Trace":[{"file":"/var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php","line":55,"function":"removeFileWithOwner","class":"OCA\\Photos\\Album\\AlbumMapper","type":"->"},{"file":"/var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php","line":105,"function":"OCA\\Photos\\Listener\\{closure}","class":"OCA\\Photos\\Listener\\AlbumsManagementEventListener","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php","line":98,"function":"forEachSubNode","class":"OCA\\Photos\\Listener\\AlbumsManagementEventListener","type":"->"},{"file":"/var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php","line":98,"function":"forEachSubNode","class":"OCA\\Photos\\Listener\\AlbumsManagementEventListener","type":"->"},{"file":"/var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php","line":55,"function":"forEachSubNode","class":"OCA\\Photos\\Listener\\AlbumsManagementEventListener","type":"->"},{"file":"/var/www/html/lib/private/EventDispatcher/ServiceEventListener.php","line":86,"function":"handle","class":"OCA\\Photos\\Listener\\AlbumsManagementEventListener","type":"->"},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":87,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":99,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/html/lib/private/Share20/Manager.php","line":1244,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/html/apps/collectives/lib/Service/CollectiveShareService.php","line":231,"function":"deleteShare","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/html/apps/collectives/lib/Service/CollectiveShareService.php","line":256,"function":"deleteFileShare","class":"OCA\\Collectives\\Service\\CollectiveShareService","type":"->"},{"file":"/var/www/html/apps/collectives/lib/Controller/CollectiveController.php","line":262,"function":"deleteShare","class":"OCA\\Collectives\\Service\\CollectiveShareService","type":"->"},{"file":"/var/www/html/apps/collectives/lib/Controller/ErrorHelper.php","line":27,"function":"OCA\\Collectives\\Controller\\{closure}","class":"OCA\\Collectives\\Controller\\CollectiveController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/collectives/lib/Controller/CollectiveController.php","line":68,"function":"handleErrorResponse","class":"OCA\\Collectives\\Controller\\CollectiveController","type":"->"},{"file":"/var/www/html/apps/collectives/lib/Controller/CollectiveController.php","line":266,"function":"prepareResponse","class":"OCA\\Collectives\\Controller\\CollectiveController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"deleteShare","class":"OCA\\Collectives\\Controller\\CollectiveController","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/lib/base.php","line":1064,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/apps/photos/lib/Album/AlbumMapper.php","Line":296,"message":"Collectives App Error: OCA\\Photos\\Album\\AlbumMapper::removeFileWithOwner(): Argument #2 ($ownerId) must be of type string, null given, called in /var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php on line 55","exception":{},"CustomMessage":"Collectives App Error: OCA\\Photos\\Album\\AlbumMapper::removeFileWithOwner(): Argument #2 ($ownerId)must be of type string, null given, called in /var/www/html/apps/photos/lib/Listener/AlbumsManagementEventListener.php on line 55"}}
```

</details>

**Comment by Zockersee** [comment]
> Dear @Zockersee, So far, I fail to reproduce the problem you describe. If you allow editing in the public link share and switch to edit mode in a page there, do you the the content then? Also, did you try Ctrl-F5 for a force-reload of the page?
> 
> Do several users have the problem of not being able to access the public share link, or is it only one user (with several browsers)?
> 
> Also, please open the web console of your browser (Ctrl-Shift-I on Firefox/Chrome) in a private tab, open the public share link there and send us any errors or warnings being logged there.

Dear @mejo- ,  thank you for the quick response.
Every user is experiencing the same problem with every browser. I just gave editing permission to the public link, but unfortunately without success. Forcing a reload also did not work. 
Here is the browser log:

<details>
<summary>Logs</summary>

#### Browser log
```
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.1
index.es.js:2337  Proxying an event bus of version 3.0.2 with 1.3.0
e @ index.es.js:2337
globals.js:59  jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
globals.js:59  $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
ConsoleLogger.js:56  [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config Object
value @ ConsoleLogger.js:56
globals.js:59  oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
An @ globals.js:59
index.es.js:2337  Proxying an event bus of version 3.0.2 with 1.3.0
e @ index.es.js:2337
globals.js:59  oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
An @ globals.js:59
index.es.js:2337  Proxying an event bus of version 3.0.2 with 1.3.0
e @ index.es.js:2337
globals.js:59  jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
globals.js:59  jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
globals.js:59  $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
globals.js:59  $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
globals.js:59  $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
session-heartbeat.js:103 session heartbeat polling started
ConsoleLogger.js:59  [ERROR] Files_PDFViewer: But this does not appear to be a public page Object
value @ ConsoleLogger.js:59
index.module.js:2  The `name` prop is required. Please migrate away from the deprecated `title` prop.
nameTitleFallback @ index.module.js:2
index.module.js:2  You need to add a label to the NcInputField component. Either use the prop label or use an external one, as per the example in the documentation.
isValidLabel @ index.module.js:2
/public.php/webdav/Readme.md:1 
        
        
        Failed to load resource: the server responded with a status of 401 (Unauthorized)
pageContentMixin.js:35  Failed to fetch content of page i
fetchPageContent @ pageContentMixin.js:35
vue.runtime.esm.js:3049  Error: Input data should be a String
    at b.parse (index.js:519:11)
    at b.render (index.js:544:36)
    at o.renderHtml (index.js:4191:25)
    at o.htmlContent (index.js:561:19)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.htmlContent (vue.runtime.esm.js:5537:25)
    at o.createEditor (index.js:582:23)
    at o.created (index.js:573:25)
    at Tn (vue.runtime.esm.js:3017:61)
kn @ vue.runtime.esm.js:3049
globals.js:59  $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59


</details>

**Comment by mejo-** [comment]
> /public.php/webdav/Readme.md:1 
>         Failed to load resource: the server responded with a status of 401 (Unauthorized)
> pageContentMixin.js:35  Failed to fetch content of page i

For some reason, the permissions are missing to load the page content. I wonder why.

Does this happen with several/all shares of a collective, or only with one?

Have you tried creating a new share for a new collective to see whether the issue appears there as well?

**Comment by Zockersee** [comment]
> > /public.php/webdav/Readme.md:1
> > Failed to load resource: the server responded with a status of 401 (Unauthorized)
> > pageContentMixin.js:35  Failed to fetch content of page i
> 
> For some reason, the permissions are missing to load the page content. I wonder why.
> 
> Does this happen with several/all shares of a collective, or only with one?
> 
> Have you tried creating a new share for a new collective to see whether the issue appears there as well?

I have already tried all options, including creating a new collective, but unfortunately without success. Creating a collective via another user also does not work as the same error occurs.

**Comment by mejo-** [comment]
Could it be that you have set something like enforced password protection on shares on your Nextcloud instance?

Do normal file shares via link (without password protection) work as expected?

And if you open a shared collective with editing permissions and click on the 'Edit' button, does the editor open? Can you send me again the output of the browser developers console after trying this?

**Comment by Zockersee** [comment]
> Could it be that you have set something like enforced password protection on shares on your Nextcloud instance?
> 
> Do normal file shares via link (without password protection) work as expected?
> 
> And if you open a shared collective with editing permissions and click on the 'Edit' button, does the editor open? Can you send me again the output of the browser developers console after trying this?

No password enforcement for sharing has been set in the settings. 
Sharing documents without a password works as expected. As soon as I share the link to the collective with editing permissions, no “Edit” button appears. The collective is not callable again. ,

Attached are the logs:

jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.4.1
ConsoleLogger.js:56 [WARN] viewer: Some mimes were ignored because they are not enabled in the server previews config Object
value @ ConsoleLogger.js:56
globals.js:59 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
An @ globals.js:59
globals.js:59 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
An @ globals.js:59
index.es.js:2337 Proxying an event bus of version 3.0.2 with 1.3.0
e @ index.es.js:2337
globals.js:59 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
An @ globals.js:59
globals.js:59 oc_appswebroots is deprecated: use OC.appswebroots instead, this will be removed in Nextcloud 20
An @ globals.js:59
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59
session-heartbeat.js:103 session heartbeat polling started
index.module.js:2 The `name` prop is required. Please migrate away from the deprecated `title` prop.
nameTitleFallback @ index.module.js:2
index.module.js:2 You need to add a label to the NcInputField component. Either use the prop label or use an external one, as per the example in the documentation.
isValidLabel @ index.module.js:2
/public.php/webdav/Readme.md:1     Failed to load resource: the server responded with a status of 401 (Unauthorized)
pageContentMixin.js:35 Failed to fetch content of page i
fetchPageContent @ pageContentMixin.js:35
vue.runtime.esm.js:3049 Error: Input data should be a String
    at b.parse (index.js:519:11)
    at b.render (index.js:544:36)
    at o.renderHtml (index.js:4191:25)
    at o.htmlContent (index.js:561:19)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.htmlContent (vue.runtime.esm.js:5537:25)
    at o.createEditor (index.js:582:23)
    at o.created (index.js:573:25)
    at Tn (vue.runtime.esm.js:3017:61)
kn @ vue.runtime.esm.js:3049
globals.js:59 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
An @ globals.js:59

**Comment by punkyard** [comment]
thanks @Zockersee for the tips
Also, defining the Collective settings can open the permission to share by users (no admin or mods)
