### ISSUE TITLE
Almost there but not quite yet

### ISSUE THREAD

**Issue by lafiel** [nextcloud/collectives#786]
**Is your feature request related to a problem? Please describe.**
We'd like to use the collective to document our processes. But at the moment it's missing some important things

**Describe the solution you'd like**
* allow long titles without them being cut or shortened
* use _all_ the real estate with a responsive design, it wastes too much free space on the left and right side of the content at the moment
* allow cover images (on top) on the first page of the collective
* allow blog/news like entries displayed as timeline in the dashboard (and not just small box) and in the collective
* make the edit button not so eye catching
* show the old revisions and make it possible to move back to them
* show more details of the markdown like who worked on it
* allow comments in the content
* allow someone external to view and/or change the doc (same as the files)

Keep up the good work

**Comment by mejo-** [comment]
Dear @lafiel, thanks for your feedback. It's highly appreciated. Let's go through your suggestions:

> allow long titles without them being cut or shortened

Are you talking about the title being displayed in the page list navigation? The navigation sidebar can be resized. Or do you mean page titles as displayed in the page header above the editor?

> use all the real estate with a responsive design, it wastes too much free space on the left and right side of the content at the moment

There's already https://github.com/nextcloud/collectives/issues/242 to track this. Unfortunately there's no good solution to it yet from a design perspective.

> allow cover images (on top) on the first page of the collective

Would you mind to open a separate feature request for this?

> allow blog/news like entries displayed as timeline in the dashboard (and not just small box) and in the collective

We'll improve the landing page soon and add an overview about recently changed pages to it. See the mockup here: https://github.com/nextcloud/collectives/issues/311#issuecomment-1647995034 Would this solve your issue?

> make the edit button not so eye catching

Could you elaborate on why it's too present for you currently?

> show the old revisions and make it possible to move back to them

This is already possible. You can open the page sidebar on the right side, navigate to the versions tab, open old versions and revert to them. Anything missing there from your perspective?

> show more details of the markdown like who worked on it

We already show who and when did the last changes above the file if you're in view mode. What else would you expect?

> allow comments in the content

This is already been tracked in https://github.com/nextcloud/text/issues/185

> allow someone external to view and/or change the doc (same as the files)

You can share a Collective via public link, see the "Share link" option in the three-dots menu of each Collective.

**Comment by mejo-** [comment]
I'm closing this issue due to lack of further information.
