### ISSUE TITLE
Emojis not rendered in sidebar/page title

### ISSUE THREAD

**Issue by l-mb** [nextcloud/collectives#798]
**Describe the bug**
Emojis for pages don't render in the collectives sidebar/page title, even though they show fine in the emoji picker, and are visible in the inspector/page source.

This affects my Linux desktop with Nextcloud 25.0.8, both for Chrome and Firefox. It renders fine on Firefox for mobile.

After a lot of swearing, I traced it down to the `font-family: var(--font-face)` attribute on `body` in the CSS.

If I disable that, it'll use `font-family: serif` and show the emojis fine.

If left at the default, `font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Cantarell, Ubuntu, "Helvetica Neue", Arial, sans-serif, "Noto Color Emoji", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"` does not render the emojis.

**To Reproduce**
1. Go to any page in your collective
2. Edit the page name and `Select emoji`
3. Pick any emoji
4. It'll either render in the side bar and the page title - or not.

**Expected behavior**
Emoji displayed.

**Client details:**
 - OS: Linux
 - Browser: Firefox and Chrome both
 - Version: 25.0.8 as hosted by Hosting.de
 - Device: Desktop

**Nextcloud version:** 25.0.8

(Since this is a hosted instance I can't provide all the details.)

**Comment by mejo-** [comment]
Hey @l-mb, thanks for your report. This sounds like a local browser/font problem to me. Do you see emojis being rendered in other Nextcloud apps? Also, if you use the emoji picker in the Text editor (e.g. within Collectives), do you see the inserted emoji being rendered?

**Comment by l-mb** [comment]
My bad, I dropped the ball here.

I just want to add in closing that I've now noticed this on other sites as well, and even though I've not yet resolved it, I don't think it's a Nextcloud issue but somehow with Firefox's own configuration that's very non-obvious.

So yes, let's keep this closed.
