### ISSUE TITLE
no content of the page is displayed

### ISSUE THREAD

**Issue by FW-NC** [nextcloud/collectives#799]
If you call up the Icon Collective in the menu bar, no content of the page is displayed. The error has been occurring since last week.

 - Browser: Firefox 
 - Version: 115.0.2 64-Bit
 - Device: Desktop
- Collectives app version: 2.6.1
- Nextcloud version: 26.03

**Comment by mejo-** [comment]
Dear @FW-NC, thanks for your report.

To get a better understanding of your issue, we need further information.

Can you send us a screenshot to visualize your problem?

Also, please open the web console of your browser (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>I</kbd> on Firefox/Chrome), open the Collectives app and send us any errors or warnings being logged there.

Furthermore, please send us relevant logs from the `nextcloud.log` file on your server that appear while experiencing the issue.
