### ISSUE TITLE
Links within document dont work

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/collectives#825]
**Describe the bug**
Links within a document - e.g. to create your own index - don't work in the usage-view:
- In the edit-view, they work as expected
- Between edit-view and usage-view, the heading-id's change from e.g. `#title` to `#h-title`. 
- Even when considering the final link-id, clicking the link in the usage view, does not have any effect on clicking. (Respective no effect on first click, completely disappearing collectives-app on second click)

**To Reproduce**
1. Add page to collectives, which contains the following plain MD:
```
Page with an index:

* [link to heading](#h-heading)

and

some

text

to

have

a

long

page

which

should

move

when

clicking

a

link

that

is

linked

to

the

follwing

heading

# heading
```

3. Open file in collectives
4. Click on 'link to heading'
5. Nothing moves.
6. Changing the link to (#heading) and clicking in edit-view, it works as expected.

**Client details:**
 - OS: Win10
 - Browser: Firefox 116
 - Device: Desktop

<details>
<summary>Server details</summary>

**Collectives app version:** 2.7.0

**Nextcloud version:** 25.0.9

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing relevant
```

#### Browser log
```
Error - Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/JDAV%20Wiki/New%20page#h-heading".
```

</details>

**Comment by mejo-** [comment]
I'm pretty sure this is fixed by now. the `h-` prefix should be there in both cases, and clicking on anchor links works as expected. Please don't hesitate to comment with further information if you still experience this issue with a recent Nextcloud + Collectives release.
