### ISSUE TITLE
Improved landing page clutters the view of the landing page

### ISSUE THREAD

**Issue by matthiastaeschner** [nextcloud/collectives#835]
**Describe the bug**
With Collectives version 2.7.0, recent pages and collective members are listed on top of the landing page (#311). 
Both the recent pages and the collective members move important information in the actual landing page far down, on small monitors these are no longer directly visible and it must be scrolled down first. For the little information that the recent pages offer, they simply take up too much space and therefore should be able to be deactivated / removed.
This is activated by default for all existing collectives and can neither be switched off in the settings nor removed in the edit mode.

**To Reproduce**
1. Install and activate Collectives version 2.7.0
2. Try to deactivate or remove the "Recent pages" or "Collective members"

**Expected behavior**
At least the option for deactivation or the possibility to remove those views in edit mode should be available.

**Collectives app version:**
Version 2.7.0

**Nextcloud version:**
Version 27.0.2

**Comment by juliushaertl** [comment]
pinging @nextcloud/designers for feedback

**Comment by szaimen** [comment]
What would be the motivation why this should be made deactivatable?

**Comment by matthiastaeschner** [comment]
For us, it simply clutters the view of the landing page. Both the recent paged and the collective members move important information in the actual landing page far down, on small monitors these are no longer directly visible and it must be scrolled down first. For the little information that the recent pages offer, they simply take up too much space and therefore should be able to be deactivated / removed.
In addition, on our side, not all readers of a Collective should be able to see which others accounts and groups have access it.

**Comment by pascalBokBok** [comment]
Hey. We just upgraded. Now the content is only half the page. While this information could be interesting it overshadows the content which is why you're there :-)

**Comment by max-nextcloud** [comment]
> In addition, on our side, not all readers of a Collective should be able to see which others accounts and groups have access to it.

My understanding is that they would be able to see the member list in the contacts app in the corresponding circle anyway. Or is there a way to disable that?

**Comment by max-nextcloud** [comment]
I tried to change the title to describe the problem rather than the solution. I think there can be various ways of dealing with this and a configuration toggle is just one of them.
We try to solve the underlying issue rather than adding configuration options because otherwise we end up with a UI full of toggles.

**Comment by matthiastaeschner** [comment]
> > In addition, on our side, not all readers of a Collective should be able to see which others accounts and groups have access to it.
> 
> My understanding is that they would be able to see the member list in the contacts app in the corresponding circle anyway. Or is there a way to disable that?

You are right...a member with now further rights in the Collective is able to view other accounts and groups with access rights to it via the Contacts app and the Circles listed there. My fault

**Comment by max-nextcloud** [comment]
Quick sketch reducing the height from ~800px to 500px: 

![grafik](https://github.com/nextcloud/collectives/assets/97337118/ba6b0994-d4e1-4cb4-8297-a74ea01fc8fe)

* left out captions for members and content
* only display 2 1/2 recent pages instead of 3 1/2
* make recent pages more wide and less high (current ellipses also cuts the names very early).

As i said - this is a quick sketch for an alternative positioning. Looks somewhat cluttered though.

**Comment by pascalBokBok** [comment]
While it's nice info I think it takes way to much attention. It could be in a foldout called "Recent edits" or moved into the sidebar.

**Comment by hansimausisteffiwurstbrot** [comment]
Yes.
PLEASE remove this or enable the deactivation.

I was about to introduce collectives into several projects but this is a deal breaker for me.

And as mentioned there is privacy issue, too.

**Comment by hansimausisteffiwurstbrot** [comment]
Is money an issue? Could we support the enhancement of the app (ergo the fix of this bug) with financial means?

**Comment by Mannshoch** [comment]
For the Record. I get feedback about this page. Users try to remove the recent part and ask me why it can't be removed.
On Public link I get questions from guests what they should do with that part. (There is no use for them)

If you think there is a need for that put it into the right panel.

I'm more and more disappointed by this app. At first a not needed Link [preview](https://github.com/nextcloud/collectives/issues/579) That Publish the IP on  every opening of the page to the links inside the page and clutter  the content and now this. 
I would not have a problem if you could simply deactivate this. And don't need config.php and css Hacks.

**Comment by pascalBokBok** [comment]
An Example of content being only 1/8th of the page in a full HD resolution.
![image](https://github.com/nextcloud/collectives/assets/639487/d6ffcce5-7e76-4d04-bf31-80d620a88f64)
It's also keeping me from moving my company wiki over.

**Comment by hansimausisteffiwurstbrot** [comment]
@mejo- @azul are you still involved in this app?
I would love to read a reaction of the team.

**Comment by mejo-** [comment]
Thanks for the feedback everyone. We understand that the landing page widgets are inconvenient for some usecases. We'll evaluate options to address this :relaxed:

**Comment by jancborchardt** [comment]
@mejo- @max-nextcloud the height reduction experiment Max posted above is nice.

Another step could be to simply move the text content above the other elements. If something important is there, it always takes precedence.

**Comment by mejo-** [comment]
> Another step could be to simply move the text content above the other elements. If something important is there, it always takes precedence.

How much vertical space would you grant the text content then? For a landing page with very long introductory text the other information would move far down and probably would not even be discovered by most users. On the other hand, limiting the height for the editor could be cumbersome for long documents as well, no?

**Comment by mejo-** [comment]
I agree that the height reduction suggestions by @max-nextcloud are a good first step.

But maybe we should allow to remove recent pages and memberlist widgets from the langingpage nevertheless? I just wonder whether this should be a per-user change or a per-collective admin setting. If the change would be per user, how would be allow to restore the elements?

**Comment by pascalBokBok** [comment]
I honestly just want to be able to get a solution ASAP both for the existing users and so new users don't have to choose something else in the meantime. 
Can't we just have a drop down in collective settings to "Show Collective info on landing page:" [Above content / Below content] ?

**Comment by Mannshoch** [comment]
My current CSS overwrite:

```
/* remove linkpreview  https://github.com/nextcloud/server/issues/35840#issuecomment-1676504721 */
.ProseMirror .widgets--list{
    display: none;
}

/* Remove Recent document */
[class='landing-page-widgets'] {
    display: none !important;
}

```

**Comment by pascalBokBok** [comment]
> My current [CSS overwrite](https://apps.nextcloud.com/apps/theming_customcss):
Thanks for sharing a good workaround until a solution is shipped.

**Comment by mejo-** [comment]
We just discussed this topic in a design call and will do the following changes:

* Make recent pages widget collapsible. This will persist in the database for user and collective, so collapsing it once will keep it collapsed across page reloads and different devices.
* Move members list to the top and remove its caption.

**Comment by hansimausisteffiwurstbrot** [comment]
sounds good. 

just to be sure: it's stored in the database for each user and by default it will not be collapsed?
having the users in mind that are not so "digitally native"t would be better if it were collapsed by default.

looking forward to the changes.

**Comment by mejo-** [comment]
> just to be sure: it's stored in the database for each user and by default it will not be collapsed?

Exactly.

> having the users in mind that are not so "digitally native"t would be better if it were collapsed by default.

Well, it's a matter of perspective :blush: We introduced the overview about pages with recent changes because there was a demand for it and it helps people that come back to a collaboratively used collective to get an overview on what happened lately. And there, collapsing it by default would hide it from users who don't discover the possibility to expand it.

**Comment by hansimausisteffiwurstbrot** [comment]
> Well, it's a matter of perspective :blush: We introduced the overview about pages with recent changes because there was a demand for it and it helps people that come back to a collaboratively used collective to get an overview on what happened lately. And there, collapsing it by default would hide it from users who don't discover the possibility to expand it.

Yeah, my perspective is, that those who work regularly with cooperatives know how to click in order to show the latest changes.

Whereas those who go to a collective to retrieve dinner information and are not directly involved in there continuous work on it rather don't know/lack the intuition to do so.

I guess it's a matter of use cases: I use collectives as mini pages/simple Wikis where most users won't change anything and don't care about latest changes..

In any case: thanks for agreeing on the improvement.

😀

**Comment by punkyard** [comment]
Hi
yes please, move these functions to the left menu
or make it activable in settings
it's a big disappointment for us.. our public pages are ruined when they are supposed to be easily accessed by readers
thanks

(please also remove the title frame at the buttom of the public pages - the title is already in the top menu bar!!)
