### ISSUE TITLE
When editing documents, clicking links will open a new Markdown editor

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/collectives#845]
**Describe the bug**
When editing a document and clicking a link to another document in it to **select** the link, the link will open a new markdown editor for the document. This is very confusing.

**To Reproduce**
1. Create two pages in a collective - page 1 and page 2.
2. Go to page 1 and create a link to page 2 in that page.
3. After you have created the link, click on it.
4. Now page 2 will open in a new markdown editor which has nothing to do with collectives at all.

**Expected behavior**
Clicking links in edit mode will be ignored since it makes no sense at all to open a link while editing. One clicks a link to position the text cursor there but not to open it.

**Screenshots**

Page 1 with a link to page 2:

![image](https://github.com/nextcloud/collectives/assets/6613614/b428b6cc-fb28-4ada-9107-ef0b54e165c3)

Now editing page 1:

![image](https://github.com/nextcloud/collectives/assets/6613614/055857fd-288e-4aa1-8784-147ce0a380ad)

And this happens, when you click the link while the edit mode is still active - page 2 will open in a markdown editor outside of collectives:

![image](https://github.com/nextcloud/collectives/assets/6613614/b4b827f6-4fe7-4836-912b-676fb60153dc)

**Client details:**
Not relevant, happens with all tested clients (Windows, Linux, macOS, Chrome, Firefox, Safari).

**Collectives app version:** (see Nextcloud apps page)
2.7.0

**Operating system:**
Ubuntu 22.04

**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
8.1

**Nextcloud version:** (see Nextcloud admin page)
27.0.2
</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
not relevant
```

#### Browser log
```
not relevant
```

</details>

**Comment by arnowelzel** [comment]
As a workaround I added the following custom CSS rule with [CustomCSS](https://apps.nextcloud.com/apps/theming_customcss), so links will not open when in editing mode:

```
.ProseMirror-focused a
{
   pointer-events: none;
}
```

**Comment by max-nextcloud** [comment]
I think we had a custom link handler implemented that would open the page in question in collectives. This probably broke with the last release. Interesting because we have a lot of tests for links these days.

**Comment by arnowelzel** [comment]
To avoid any misunderstanding: when clicking a link in editing mode, the link should not open at all - also not as page in Collectives - because while **editing** a document it makes no sense to open the link. The normal usecase when **editing** a document is to place the text cursor in a link by clicking it to be able to change or remove a link. If you want to open a link, you should leave the editing mode first. That's one of the reasons to have a "view" mode and an "editing" mode: one is to **view** the content which also includes opening links if needed and the other one is to **edit** content, which means links will not open but can only be **edited.**

Just compare that with Nextcloud Office: when you insert a link to a text document there, the link will be visible as link, but it will not open automatically when clicking it:

![image](https://github.com/nextcloud/collectives/assets/6613614/d5fc35a8-5654-40cc-baf4-f936a0a8e2c9)

Instead when you click it, there will be a little popup which offers to open, edit or remove it:

![image](https://github.com/nextcloud/collectives/assets/6613614/065fea1f-1dea-4137-99c3-aebb4d4b3e00)

This makes much more sense then automatically opening the link and confusing people about what just happend.

**Comment by mejo-** [comment]
To be honest, I'm not sure whether we want to change the current behaviour. Some collectives are configured to use the edit mode as default and people expect to be able to open links from the document in edit mode.

I took a look at how other do it:
- In Notion, links are opened directly when clicking at them in edit mode
- In Google Docs, clicking on a link opens a popup that allows to edit or open the link
- In Collabora Office it's similar to Google Docs.

@nextcloud/designers what do you think?

**Comment by arnowelzel** [comment]
I understand the issue with "editing mode by default" - which is also the case for the text editor in Nextcloud outside Collectives.

However in my opinion having a little popup to decide wether you want to open a link or edit it when in editing mode (similar to Google Docs or Collabora), would be the most logical solution. Otherwise it is nearly impossible to edit or remove a link in editing mode, since you can not click it without opening the link target. One has to manually move the cursor into the link using the keyboard arrow keys and then you can use the "Insert link" toolbar button to decide what to do with the link.

Also keep in mind that not all devices have a keyboard, like tablets. With the current behaviour it is usually impossible to move the cursor into a link in editing mode without opening it.

**Comment by fezoeller** [comment]
I also find it very cumbersome to first click next to the link and then run back into the text with the arrow keys. Sometimes I forget and then the link opens. ggrrrrrr......

**Comment by nimishavijay** [comment]
Interesting problem! I also took a look at the behaviour of other products and almost all of them have a popup appear at some point. Notion has a popup appear on hover and Gdocs, Confluence and Collabora has one appear on click like @mejo- mentioned. This makes me think we could have better link management in general (Mail actually also has a popup that appears on click). 

However, previously I think we did have a popup for link management in Text and it had a lot of issues with positioning, responsiveness, etc (https://github.com/nextcloud/text/issues/2211#issuecomment-1063094981). I am afraid introducing something like that again will be a regression. what do you think? @jancborchardt

**Comment by jancborchardt** [comment]
@nimishavijay previously we did not have a popover for this, but for inserting links – which we moved to the action bar.
Editing vs viewing links is indeed something we need to handle via popover though, and as you say this is an established standard across text editing apps.
