### ISSUE TITLE
Links do not work as expected

### ISSUE THREAD

**Issue by tatrapikao** [nextcloud/collectives#854]
**Describe the bug**
if i Link something in a collectives page i get e nice little preview box below the given Link that contains a favicon, a Headline ect.. As long as i am in Edit Mode this Box is clickable and works fine. As soon as i  go back to viewing, the Box stops working as a link. The Link above it is still functional and i can even middle click the Preview (open in new Tab). Also the Cursor changes on hover to indicate a Link.

**To Reproduce**
1. create Page
2. paste a link
3. leave Edit
4. try to click the Link

**Expected behavior**
cllicking the Preview should open the linked Page in anew Tab.

**Client details:**
 - OS: [-]
 - Browser: [firefox]
 - Version: [116.0.2]
 - Device: [desktop]

**Collectives app version:**  2.7.0

**Nextcloud version:**  26.0.5

**Comment by perkm** [comment]
Similar issue: https://github.com/nextcloud/collectives/issues/844

**Comment by mejo-** [comment]
This is fixed in the upcoming Nextcloud 29 release thanks to the new link bubble feature in Nextcloud Text.
