### ISSUE TITLE
collectives activation - pop up window prevents usage 

### ISSUE THREAD

**Issue by amsel54** [nextcloud/collectives#881]
in hosted Nextcloud 26.0.5 I downloaded and activated Collectives.
When I choose the Collectives App, the corresponding window opens but two pop up windows occur with unreadable text. They disappear after a few seconds. I open create new collective. I give Name and circle and click create. Again a pop up window with unreadable text opens, but that window does not disappear. I can close it manually, but I am still in the former create dialog. Hitting create again reopens the pop up window.

So in my case collectives is unusable.

Do you have any hints whats going wrong.

Used Firefox from debian and Windows, same behaviour.

Thanks
![NC_collectives](https://github.com/nextcloud/collectives/assets/101837309/7adb0c23-c91f-40e1-bd90-1d7f92333655)

**Comment by max-nextcloud** [comment]
Hi @amsel54 

Thanks for your report. I have not seen this before.

Could you provide us with some more debugging information?
1. Which version of collectives did you install?
2. Is the Provider hosting Nextcloud for you or just the Operating system and you installed Nextcloud yourself?
3. If they are hosting Nextcloud please also file a ticket with them. This looks like it might be a configuration issue. If they are a Nextcloud partner or have a Nextcloud contract please tell them to contact support.
4. Do you have access to the nextcloud.log file? It's usually stored in the data folder of the Nextcloud directory.

**Comment by mejo-** [comment]
Let's close this issue due to lack of further infomration. @amsel54 feel free to comment and reopen with further details.
