### ISSUE TITLE
Collectives are not shared with LDAP group members in Nextcloud

### ISSUE THREAD

**Issue by elephantastyczny** [nextcloud/collectives#890]
**Describe the bug**
When you'll add an LDAP group to Circle, members of that group cannot see collective.

**Expected behavior**
Once LDAP group is added to a circle, members of that group should see collective.

<summary>Nextcloud AIO 7.2.1 - NC 27.1.0 - Collectives 2.7.1</summary>

**Comment by elephantastyczny** [comment]
Quick update.
I've noticed that some of LDAP users are able to see created and shared collectives, but some of those users, can't see any.
Can you help me with how to track what is happening?

**Comment by Thatoo** [comment]
I face the same issue

**Comment by mejo-** [comment]
There is an open pull request in the circles app that might solve this issue: https://github.com/nextcloud/circles/pull/1421

Could you please apply [the patch](https://github.com/nextcloud/circles/pull/1421.patch) against the circles app and see whether it solves the issue for you?

**Comment by mejo-** [comment]
To anyone still facing this problem, please run the following commands and report back if they fix the problem:

```
occ circles:sync
occ circles:memberships --all
```
