### ISSUE TITLE
Update to v2.8.1 crashed

### ISSUE THREAD

**Issue by koebi80** [nextcloud/collectives#917]
**Describe the bug**
The update newest release v2.8.1 of the collective app crashed.

The following error message apears: 
Exception: Database error when running migration 020800Date20230911000000 for app collectives An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'settings' can't have a default value

**To Reproduce**
- Start update from v2.7.1 to v2.8.1 within the admin app panel.

**Expected behavior**

**Screenshots**
![Bildschirmfoto 2023-10-02 um 21 15 01](https://github.com/nextcloud/collectives/assets/106907779/7d1ec042-3689-41ee-8226-94cca6b83821)

**Client details:**

<details>
<summary>Server details</summary>

**Collectives app version:** (see Nextcloud apps page)
Update from v2.7.1 to v2.8.1

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
26.0.2 or 27.1.1

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nolens** [comment]
I have exactly the same issue.

**Comment by nolens** [comment]
> I have exactly the same issue.
@max-nextcloud 
mysql 8.0.33-25 in my case. 

PS: 
I have downgraded to an earlier version as a workaround for now.

Thanks for taking care of this!

**Comment by afgeissler** [comment]
i have the same problem with NC 27.1.1 and mysql 8.0.34

**Comment by koebi80** [comment]
On System with NC 27.1.1 is MySQL 5.7.42

On System with NC 26.0.2 (managed system, no access to console or server infos)

**Comment by max-nextcloud** [comment]
The 2.8.0 and 2.8.1 releases have been removed from the appstore to prevent others from running into this issue.

We also have a failing test for the upgrade with mysql now #923 here.

**Comment by max-nextcloud** [comment]
> On System with NC 27.1.1 is MySQL 5.7.42

Independent of this issue - Please check if you can update your mysql version. The last nextcloud version to support mysql 5.7 is Nextcloud 20. So it's been a while since we don't test mysql 5.7 compatibility anymore.

**Comment by mejo-** [comment]
To those who got caught by this bug and have a broken Collectives app now: installing Collectives version 2.8.2 should fix your problems.

**Comment by koebi80** [comment]
Thank you very much for fixing the problem so fast!
It works in my test system with NC 27.1.1/MySQL 5.7.42 (running on a hosting server, so I can't Change the MySQL Version by myself)
