### ISSUE TITLE
content is not displayed in public share

### ISSUE THREAD

**Issue by punkyard** [nextcloud/collectives#919]
**To Reproduce**
1. Copy share link
2. Open a different browser in which no user is logged in
3. Paste link
4. No content in the page

**Expected behavior**
normal display of pages content 

**Screenshots**

edit page in collectives
<img width="271" alt="Capture d’écran 2023-10-04 à 00 40 49" src="https://github.com/nextcloud/collectives/assets/59349105/8d918487-df9d-4cbd-b28f-01124033ccd7">

public page - no content - even after changing permissions 
even when logged in with the owner account of the collective
<img width="305" alt="Capture d’écran 2023-10-04 à 00 40 28" src="https://github.com/nextcloud/collectives/assets/59349105/0dd41088-0040-4442-9a04-07cc2afe75a8">

when editing, sometimes a whole page disappears, but can be found in the version list
No specific logs in the log reader

**Client details:**
AiO 7 2 1

**Collectives app version:** (see Nextcloud apps page)
2.8.1

#### Nextcloud log (data/nextcloud.log)

Insert your Nextcloud log here

Error | core | OC\User\NoUserException: Backends provided no user object |   | 2023-10-03T13:42:34+0200

Error | files | OC\User\NoUserException: Backends provided no user object

**Comment by mejo-** [comment]
Dear @punkyard, could it be that you have “Allow users on this server to send shares to other servers (This option also enables WebDAV access to public shares)” disabled under “Sharing -> Federated Cloud Sharing”? This option must be enabled in order for public collective shares to work. See https://nextcloud.github.io/collectives/administration/#public-shares

**Comment by punkyard** [comment]
hi @mejo- thanks a lot for your concern. 
unfortunately, deactivating or activating this option doesn't change the lack of content display.

![Capture d’écran 2023-10-05 à 00 08 41](https://github.com/nextcloud/collectives/assets/59349105/7c421a9a-0160-476c-92a8-1ed1eb63ba5e)

It seems to be loading ..
![Capture d’écran 2023-10-05 à 00 09 15 (2)](https://github.com/nextcloud/collectives/assets/59349105/aa20f258-b6dd-4173-be15-9569c1c210d2)

but it doesn't ..
![Capture d’écran 2023-10-05 à 00 09 19 (2)](https://github.com/nextcloud/collectives/assets/59349105/12a5efdd-e8f4-4e70-b5ba-269b3f582a39)

**Comment by mejo-** [comment]
Dear @punkyard, please open the web console of your browser (<kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>I</kbd> on Firefox/Chrome), open the public share (with the pages without content) and send us any errors or warnings being logged there.

Furthermore, please send us relevant logs from the `nextcloud.log` file on your server that appear while experiencing the issue.

**Comment by punkyard** [comment]
Hi @mejo- and thanks for your concern
I don't have access to the log file at the moment
This problem occured when Recent pages, Contributors and Landing page were introduced.
Do you know how I could get read of these?

In safari inspector(where the problem is), I can read:
`The `name` prop is required. Please migrate away from the deprecated `title` prop.
Failed to load resource: the server responded with a status of 401 ()
Unhandled Promise Rejection: AxiosError: Request failed with status code 401
[ERROR] Files_PDFViewer: But this does not appear to be a public page

`

**Comment by mejo-** [comment]
These logs from the inspector seem relevant

> Failed to load resource: the server responded with a status of 401 ()
> Unhandled Promise Rejection: AxiosError: Request failed with status code 401
> [...]
> 
> Failed to load resource: the server responded with a status of 404 ()
> Failed to fetch content of page
> Error: Input data should be a String
> Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.davContent.trim')

Please open the "Network" tab of Safari inspector, open a public without content in the public share and see whether there's a failed request with return code 401 and/or 404.

Please send a screenshot of the network console **and** of the console log (so that I see it formatted and not in one big blob like you pasted it above).

**Comment by punkyard** [comment]
hi @mejo- 
I've updated NC AiO last night, and Collectives app, and it seems that the bug has been fix.

thanks a lot
