### ISSUE TITLE
Preview images are not shown when attaching images

### ISSUE THREAD

**Issue by DavidMndz** [nextcloud/collectives#952]
**Describe the bug**
When you are attaching an image into a Collective, it does not show the preview of the image in the select menu as it was before. It happens the same inserting from Files (Nextcloud) or from computer.

**To Reproduce**
1. Open a collective in Edit mode.
2. Insert an image from Files
3. Search for the picture you want to attach.
4. The previews are not shown.

**Expected behavior**
The preview of the image should be shown, otherwise it is very difficult to know the photo you select.

**Screenshots**

**Client details:**
 - OS: Debian and Android
 - Browser: Brave
 - Version: Latest
 - Device: Pixel 7 Pro and desktop
 - 
<details>
<summary>Server details</summary>

**Collectives app version:** 2.8.2

**Operating system:** Debian

**Web server:** Apache2

**Database:** myswl

**PHP version:** 8.2

**Nextcloud version:** 27.1.2

</details>

<details>
<summary>Logs</summary>

No errors are reported in logs.

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by mejo-** [comment]
Dear @DavidMndz, thanks for your report. Can you please provide a screenshot of the problem? The dialog that's opened by "Upload from computer" is provided by your browser and not specific to Nextcloud. Unfortunately we cannot do anything about this dialog. But the "Insert from files" dialog is Nextcloud specific. I'd need a screenshot to better understand your problem though.

**Comment by DavidMndz** [comment]
Hello @mejo- ,

thanks for checking the issue.

I was testing again and I can see the same issue with the files that I try to attach from my computer or from the Nextcloud files directly. I attach the screenshot from the option 'Attach from Nextcloud files'.

![Screenshot from 2023-11-08 14-41-11](https://github.com/nextcloud/collectives/assets/46326706/83cd2de3-a8cb-4afd-a6e9-cf11395408e9)

I hope this clarifies, if you need further details let me know please. Also, if you could please give it a try on your side to see if in your installation it happens the same, I think it could be useful.

Thanks again!

**Comment by mejo-** [comment]
Now I see, you mean Nextclouds file picker. The file picker indeed changed recently in Nextcloud 27.1. Apparently the new version doesn't display previews any longer. This would need to get changed in [nextcloud-libraries/dialogs](https://github.com/nextcloud-libraries/nextcloud-dialogs/).

**Comment by mejo-** [comment]
This already got fixed upstream in https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/1015, but a new stable4 release of [nextcloud-libraries/dialogs](https://github.com/nextcloud-libraries/nextcloud-dialogs/) is needed.
