### ISSUE TITLE
Icons get lost 

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/collectives#956]
The icons of collectives get lost. A questionmark ist shown instead after each reload.

I can chose an icon and it's shown as long as I don't reload the pace

Collectives 2.8.2
Nextcloud 25.0.10

**Comment by juliushaertl** [comment]
Please check if your database properly supports storing emojis https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by mejo-** [comment]
@hansimausisteffiwurstbrot did you find time to check 4byte support of your database?

**Comment by hansimausisteffiwurstbrot** [comment]
I asked the person that should be able to tell me and will ask again.
:)


I noticed, that not all icons have issues.

Anyway, I'll let you know as soon as I find out.

**Comment by hansimausisteffiwurstbrot** [comment]
> Please check if your database properly supports storing emojis https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html

It doesn't. :)

Thanks for the hint.
