### ISSUE TITLE
Collectives App cause nextcloud's cron.php to fail with exception

### ISSUE THREAD

**Issue by andwei** [nextcloud/collectives#968]
**Describe the bug**
Running the nextcloud cron job causes an exception from Collectives Code
```
ArgumentCountError: Too few arguments to function OCA\Collectives\BackgroundJob\ExpirePageTrash::__construct(), 0 passed in /var/www/html/lib/private/BackgroundJob/JobList.php on line 322 and exactly 3 expected in /var/www/html/custom_apps/collectives/lib/BackgroundJob/ExpirePageTrash.php:18
Stack trace:
#0 /var/www/html/lib/private/BackgroundJob/JobList.php(322): OCA\Collectives\BackgroundJob\ExpirePageTrash->__construct()
#1 /var/www/html/lib/private/BackgroundJob/JobList.php(227): OC\BackgroundJob\JobList->buildJob(Array)
#2 /var/www/html/cron.php(145): OC\BackgroundJob\JobList->getNext(false)
#3 {main}
```

**To Reproduce**
`/usr/local/bin/php -f /var/www/html/cron.php`

**Expected behavior**
The cronjob does not throw an exception. Deactivating the Collectives App using the admin menu makes cron.php to run wihtout errors.

<details>

**Collectives app version:** 2.8.2

**Operating system:** Debian bullseye

**Web server:** nginx version: nginx/1.25.3

**Database:** /usr/bin/mariadb from 11.1.2-MariaDB

**PHP version:** PHP 8.2.11 (cli) (built: Oct 21 2023 04:44:42) (NTS)

**Nextcloud version:** Nextcloud Hub 6 (27.1.2)  (Docker official nextcloud Image tagged nextcloud:stable-fpm-alpine)

</details>

**Comment by mejo-** [comment]
Apparently this happens if the `files_trashbin` app is disabled.
