### ISSUE TITLE
pictures in view mode not loading

### ISSUE THREAD

**Issue by R4U5CH1337** [nextcloud/collectives#969]
**Describe the bug**
Hi there,

I'm not able to see pictures in view mode of a share collective.

I tried embedding via upload or picked a file from the cloud. In edit mode I can see the picture, but after hitting "done" there's only an infinite loading circle to see.

Is there any setting missing on my side?
Thanks a lot for your hints.

**To Reproduce**
1. Go to a page upload a picture file in a groud page
2. Click on "done"
3. View mode
4. no picture to see

**Expected behavior**
To see the picture from the upload and edit form.

**Client details:**
 - OS: Linux and Windows
 - Browser: Firefox or Edge
 - Device: desktop

**Collectives app version:** (see Nextcloud apps page)
current

**Operating system:**
Linux 5.15.0-71

**Web server:**
nginx 1.21.6

**Database:**
mysql 10.11.4

**PHP version:**
8.2.11

**Nextcloud version:** (see Nextcloud admin page)
27.1.2.1

</details>

**Comment by R4U5CH1337** [comment]
Thanks a lot for the latest update. 
Unfortunately I'm still not able to see pictures in view mode. Is it working on yours? Thanks a lot!

**Comment by mejo-** [comment]
@R4U5CH1337 which Nextcloud server version are you running?

**Comment by R4U5CH1337** [comment]
> @R4U5CH1337 which Nextcloud server version are you running?

Nextcloud 27.1.3.2 atm

**Comment by R4U5CH1337** [comment]
Hi, is there any update on this?
I'm still not able to see uploaded pictures in view mode. 
Some other weird error was when I'm at the editor and like to upload a picture from PC there's a message "Toastify is awesome!". Oh?

Thanks a lot.

**Comment by R4U5CH1337** [comment]
Hi, 
sorry for bothering you. After some tests it looks like an issue on our NC providers side. **So it's not a bug or problem of yours!**

Do you know by any chance if there's any special permission (firewall, filesystem,..) necessary? It's still strange to see the picture in edit mode and even in the NC markdown editor, but not in view mode in the collectives app.

Thank you and sorry again! :)

**Comment by mejo-** [comment]
I'm glad to hear that you were able to sort out the issue yourself. I'm not aware of special constraints for viewing attachments in view mode that would only apply there.
