### ISSUE TITLE
Accidentaly created the same Collectives as before

### ISSUE THREAD

**Issue by Byter3** [nextcloud/collectives#977]
I migrated between two Nextcloud instances and I brought all the containments of the previous Collectives folder with me. I accidentally created the same collectives as it were on the previouse server and now all my files from the folder are lost and the clam-av constantly complaining about the old files.
```
{"reqId":"sBnMwTs8swk0MbO8ntDg","level":3,"time":"2023-11-01T04:37:16+00:00","remoteAddr":"","user":"--","app":"files_antivirus","method":"","url":"--","message":"Can not open for reading. File: 20830 Account: ** Path: /**/files/Collectives/**/**/**/**.md","userAgent":"--","version":"27.1.2.1","data":{"app":"files_antivirus"},"id":"6541d6533f91c"}
```

What to do now?

**Comment by mejo-** [comment]
Dear @Byter3,

you mean that you created the "Collectives" folder with all contents in your home folder? That won't work as the files of Collectives live in `appdata` and are only mounted into your home folder. If you're admin on the Nextcloud instance, you could add a new user to the newly created collective and remove your old user from the collective. That way, the mountpoint should disappear from the users home folder and the files that you copied over should be visible again.

So I'd suggest to do the following:

1. Add another user to all the newly created collectives.
2. Remove your user from the collectives. Now the files you copied to the "Collectives" folder should be visible again.
3. Move all folders/files from the "Collectives" folder that you copied there somewhere else.
4. Add your user back to the newly created collectives.
5. Now you can copy/move the folders/files from your backup into the collectives folders (`Collectives/<collective_name>`) again.
6. You should see all the pages that you copied inside your collectives.
