### ISSUE TITLE
Easy Page Linking

### ISSUE THREAD

**Issue by DeadSuperHero** [nextcloud/collectives#979]
**Is your feature request related to a problem? Please describe.**
Right now, linking between various documents is kind of unwieldy: the smart picker forces the user to click around a bit to find the exact location they wanted, and the whole experience can be subject to misclicks and accidental closing of the popup. Even then, the link preview and card combo looks kind of weird. The alternative is that a user just tries to use the regular link tool, and has to know the exact URL of where the target is.

**Describe the solution you'd like**
One solution that I think would be a lot simpler would be a MediaWiki-style syntax for linking. Using something like `[[Mastodon]]` with a direct link to a document with matching title could be extremely useful in associating different pages together. If a page doesn't exist, the resulting link would be colored red, and offer the option to create the target page upon being clicked.

**Describe alternatives you've considered**
A simple and different approach may be to enable an `@mention` functionality in pages, allowing people to easily link to documents that already exist. A simple drop-down picker with potential matches could help a user rapidly find the place that they need to link to.

**Additional context**
One part of Collectives that I feel falls a little bit short currently involves linking pages together. What I would love to see is an easy, unobtrusive solution that allows me to do this very quickly, and create internal structures within my Collective based on association and references.

**Comment by max-nextcloud** [comment]
@DeadSuperHero drag & drop of the pages from the page list should be another option. Does that work for you?
